// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package rag

import (
	"context"
	"fmt"
)

type RAGDocument struct {
	Id             int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	OwnerId        int64  `thrift:"owner_id,2" frugal:"2,default,i64" json:"owner_id"`
	Title          string `thrift:"title,3" frugal:"3,default,string" json:"title"`
	Source         string `thrift:"source,4" frugal:"4,default,string" json:"source"`
	SourceType     string `thrift:"source_type,5" frugal:"5,default,string" json:"source_type"`
	Visibility     string `thrift:"visibility,6" frugal:"6,default,string" json:"visibility"`
	GroupId        int64  `thrift:"group_id,7" frugal:"7,default,i64" json:"group_id"`
	ConversationId int64  `thrift:"conversation_id,8" frugal:"8,default,i64" json:"conversation_id"`
	Status         string `thrift:"status,9" frugal:"9,default,string" json:"status"`
	CreatedAt      string `thrift:"created_at,10" frugal:"10,default,string" json:"created_at"`
	UpdatedAt      string `thrift:"updated_at,11" frugal:"11,default,string" json:"updated_at"`
	ChunkCount     int64  `thrift:"chunk_count,12" frugal:"12,default,i64" json:"chunk_count"`
}

func NewRAGDocument() *RAGDocument {
	return &RAGDocument{}
}

func (p *RAGDocument) InitDefault() {
}

func (p *RAGDocument) GetId() (v int64) {
	return p.Id
}

func (p *RAGDocument) GetOwnerId() (v int64) {
	return p.OwnerId
}

func (p *RAGDocument) GetTitle() (v string) {
	return p.Title
}

func (p *RAGDocument) GetSource() (v string) {
	return p.Source
}

func (p *RAGDocument) GetSourceType() (v string) {
	return p.SourceType
}

func (p *RAGDocument) GetVisibility() (v string) {
	return p.Visibility
}

func (p *RAGDocument) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *RAGDocument) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *RAGDocument) GetStatus() (v string) {
	return p.Status
}

func (p *RAGDocument) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *RAGDocument) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *RAGDocument) GetChunkCount() (v int64) {
	return p.ChunkCount
}
func (p *RAGDocument) SetId(val int64) {
	p.Id = val
}
func (p *RAGDocument) SetOwnerId(val int64) {
	p.OwnerId = val
}
func (p *RAGDocument) SetTitle(val string) {
	p.Title = val
}
func (p *RAGDocument) SetSource(val string) {
	p.Source = val
}
func (p *RAGDocument) SetSourceType(val string) {
	p.SourceType = val
}
func (p *RAGDocument) SetVisibility(val string) {
	p.Visibility = val
}
func (p *RAGDocument) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *RAGDocument) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *RAGDocument) SetStatus(val string) {
	p.Status = val
}
func (p *RAGDocument) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *RAGDocument) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}
func (p *RAGDocument) SetChunkCount(val int64) {
	p.ChunkCount = val
}

func (p *RAGDocument) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGDocument(%+v)", *p)
}

var fieldIDToName_RAGDocument = map[int16]string{
	1:  "id",
	2:  "owner_id",
	3:  "title",
	4:  "source",
	5:  "source_type",
	6:  "visibility",
	7:  "group_id",
	8:  "conversation_id",
	9:  "status",
	10: "created_at",
	11: "updated_at",
	12: "chunk_count",
}

type RAGSource struct {
	DocumentId int64   `thrift:"document_id,1" frugal:"1,default,i64" json:"document_id"`
	ChunkId    int64   `thrift:"chunk_id,2" frugal:"2,default,i64" json:"chunk_id"`
	Title      string  `thrift:"title,3" frugal:"3,default,string" json:"title"`
	Content    string  `thrift:"content,4" frugal:"4,default,string" json:"content"`
	Source     string  `thrift:"source,5" frugal:"5,default,string" json:"source"`
	Score      float64 `thrift:"score,6" frugal:"6,default,double" json:"score"`
	Reason     string  `thrift:"reason,7" frugal:"7,default,string" json:"reason"`
}

func NewRAGSource() *RAGSource {
	return &RAGSource{}
}

func (p *RAGSource) InitDefault() {
}

func (p *RAGSource) GetDocumentId() (v int64) {
	return p.DocumentId
}

func (p *RAGSource) GetChunkId() (v int64) {
	return p.ChunkId
}

func (p *RAGSource) GetTitle() (v string) {
	return p.Title
}

func (p *RAGSource) GetContent() (v string) {
	return p.Content
}

func (p *RAGSource) GetSource() (v string) {
	return p.Source
}

func (p *RAGSource) GetScore() (v float64) {
	return p.Score
}

func (p *RAGSource) GetReason() (v string) {
	return p.Reason
}
func (p *RAGSource) SetDocumentId(val int64) {
	p.DocumentId = val
}
func (p *RAGSource) SetChunkId(val int64) {
	p.ChunkId = val
}
func (p *RAGSource) SetTitle(val string) {
	p.Title = val
}
func (p *RAGSource) SetContent(val string) {
	p.Content = val
}
func (p *RAGSource) SetSource(val string) {
	p.Source = val
}
func (p *RAGSource) SetScore(val float64) {
	p.Score = val
}
func (p *RAGSource) SetReason(val string) {
	p.Reason = val
}

func (p *RAGSource) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGSource(%+v)", *p)
}

var fieldIDToName_RAGSource = map[int16]string{
	1: "document_id",
	2: "chunk_id",
	3: "title",
	4: "content",
	5: "source",
	6: "score",
	7: "reason",
}

type RAGGraphNode struct {
	Id          int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name        string  `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Type        string  `thrift:"type,3" frugal:"3,default,string" json:"type"`
	Summary     string  `thrift:"summary,4" frugal:"4,default,string" json:"summary"`
	CommunityId int64   `thrift:"community_id,5" frugal:"5,default,i64" json:"community_id"`
	Score       float64 `thrift:"score,6" frugal:"6,default,double" json:"score"`
}

func NewRAGGraphNode() *RAGGraphNode {
	return &RAGGraphNode{}
}

func (p *RAGGraphNode) InitDefault() {
}

func (p *RAGGraphNode) GetId() (v int64) {
	return p.Id
}

func (p *RAGGraphNode) GetName() (v string) {
	return p.Name
}

func (p *RAGGraphNode) GetType() (v string) {
	return p.Type
}

func (p *RAGGraphNode) GetSummary() (v string) {
	return p.Summary
}

func (p *RAGGraphNode) GetCommunityId() (v int64) {
	return p.CommunityId
}

func (p *RAGGraphNode) GetScore() (v float64) {
	return p.Score
}
func (p *RAGGraphNode) SetId(val int64) {
	p.Id = val
}
func (p *RAGGraphNode) SetName(val string) {
	p.Name = val
}
func (p *RAGGraphNode) SetType(val string) {
	p.Type = val
}
func (p *RAGGraphNode) SetSummary(val string) {
	p.Summary = val
}
func (p *RAGGraphNode) SetCommunityId(val int64) {
	p.CommunityId = val
}
func (p *RAGGraphNode) SetScore(val float64) {
	p.Score = val
}

func (p *RAGGraphNode) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGGraphNode(%+v)", *p)
}

var fieldIDToName_RAGGraphNode = map[int16]string{
	1: "id",
	2: "name",
	3: "type",
	4: "summary",
	5: "community_id",
	6: "score",
}

type RAGGraphEdge struct {
	Id         int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	SourceId   int64   `thrift:"source_id,2" frugal:"2,default,i64" json:"source_id"`
	TargetId   int64   `thrift:"target_id,3" frugal:"3,default,i64" json:"target_id"`
	Relation   string  `thrift:"relation,4" frugal:"4,default,string" json:"relation"`
	Weight     float64 `thrift:"weight,5" frugal:"5,default,double" json:"weight"`
	Evidence   string  `thrift:"evidence,6" frugal:"6,default,string" json:"evidence"`
	DocumentId int64   `thrift:"document_id,7" frugal:"7,default,i64" json:"document_id"`
}

func NewRAGGraphEdge() *RAGGraphEdge {
	return &RAGGraphEdge{}
}

func (p *RAGGraphEdge) InitDefault() {
}

func (p *RAGGraphEdge) GetId() (v int64) {
	return p.Id
}

func (p *RAGGraphEdge) GetSourceId() (v int64) {
	return p.SourceId
}

func (p *RAGGraphEdge) GetTargetId() (v int64) {
	return p.TargetId
}

func (p *RAGGraphEdge) GetRelation() (v string) {
	return p.Relation
}

func (p *RAGGraphEdge) GetWeight() (v float64) {
	return p.Weight
}

func (p *RAGGraphEdge) GetEvidence() (v string) {
	return p.Evidence
}

func (p *RAGGraphEdge) GetDocumentId() (v int64) {
	return p.DocumentId
}
func (p *RAGGraphEdge) SetId(val int64) {
	p.Id = val
}
func (p *RAGGraphEdge) SetSourceId(val int64) {
	p.SourceId = val
}
func (p *RAGGraphEdge) SetTargetId(val int64) {
	p.TargetId = val
}
func (p *RAGGraphEdge) SetRelation(val string) {
	p.Relation = val
}
func (p *RAGGraphEdge) SetWeight(val float64) {
	p.Weight = val
}
func (p *RAGGraphEdge) SetEvidence(val string) {
	p.Evidence = val
}
func (p *RAGGraphEdge) SetDocumentId(val int64) {
	p.DocumentId = val
}

func (p *RAGGraphEdge) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGGraphEdge(%+v)", *p)
}

var fieldIDToName_RAGGraphEdge = map[int16]string{
	1: "id",
	2: "source_id",
	3: "target_id",
	4: "relation",
	5: "weight",
	6: "evidence",
	7: "document_id",
}

type RAGGraphCommunity struct {
	Id      int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name    string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Summary string `thrift:"summary,3" frugal:"3,default,string" json:"summary"`
	Level   int64  `thrift:"level,4" frugal:"4,default,i64" json:"level"`
}

func NewRAGGraphCommunity() *RAGGraphCommunity {
	return &RAGGraphCommunity{}
}

func (p *RAGGraphCommunity) InitDefault() {
}

func (p *RAGGraphCommunity) GetId() (v int64) {
	return p.Id
}

func (p *RAGGraphCommunity) GetName() (v string) {
	return p.Name
}

func (p *RAGGraphCommunity) GetSummary() (v string) {
	return p.Summary
}

func (p *RAGGraphCommunity) GetLevel() (v int64) {
	return p.Level
}
func (p *RAGGraphCommunity) SetId(val int64) {
	p.Id = val
}
func (p *RAGGraphCommunity) SetName(val string) {
	p.Name = val
}
func (p *RAGGraphCommunity) SetSummary(val string) {
	p.Summary = val
}
func (p *RAGGraphCommunity) SetLevel(val int64) {
	p.Level = val
}

func (p *RAGGraphCommunity) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGGraphCommunity(%+v)", *p)
}

var fieldIDToName_RAGGraphCommunity = map[int16]string{
	1: "id",
	2: "name",
	3: "summary",
	4: "level",
}

type IngestDocumentReq struct {
	OwnerId        int64  `thrift:"owner_id,1" frugal:"1,default,i64" json:"owner_id"`
	Title          string `thrift:"title,2" frugal:"2,default,string" json:"title"`
	Content        string `thrift:"content,3" frugal:"3,default,string" json:"content"`
	Source         string `thrift:"source,4" frugal:"4,default,string" json:"source"`
	SourceType     string `thrift:"source_type,5" frugal:"5,default,string" json:"source_type"`
	Visibility     string `thrift:"visibility,6" frugal:"6,default,string" json:"visibility"`
	GroupId        int64  `thrift:"group_id,7" frugal:"7,default,i64" json:"group_id"`
	ConversationId int64  `thrift:"conversation_id,8" frugal:"8,default,i64" json:"conversation_id"`
}

func NewIngestDocumentReq() *IngestDocumentReq {
	return &IngestDocumentReq{}
}

func (p *IngestDocumentReq) InitDefault() {
}

func (p *IngestDocumentReq) GetOwnerId() (v int64) {
	return p.OwnerId
}

func (p *IngestDocumentReq) GetTitle() (v string) {
	return p.Title
}

func (p *IngestDocumentReq) GetContent() (v string) {
	return p.Content
}

func (p *IngestDocumentReq) GetSource() (v string) {
	return p.Source
}

func (p *IngestDocumentReq) GetSourceType() (v string) {
	return p.SourceType
}

func (p *IngestDocumentReq) GetVisibility() (v string) {
	return p.Visibility
}

func (p *IngestDocumentReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *IngestDocumentReq) GetConversationId() (v int64) {
	return p.ConversationId
}
func (p *IngestDocumentReq) SetOwnerId(val int64) {
	p.OwnerId = val
}
func (p *IngestDocumentReq) SetTitle(val string) {
	p.Title = val
}
func (p *IngestDocumentReq) SetContent(val string) {
	p.Content = val
}
func (p *IngestDocumentReq) SetSource(val string) {
	p.Source = val
}
func (p *IngestDocumentReq) SetSourceType(val string) {
	p.SourceType = val
}
func (p *IngestDocumentReq) SetVisibility(val string) {
	p.Visibility = val
}
func (p *IngestDocumentReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *IngestDocumentReq) SetConversationId(val int64) {
	p.ConversationId = val
}

func (p *IngestDocumentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IngestDocumentReq(%+v)", *p)
}

var fieldIDToName_IngestDocumentReq = map[int16]string{
	1: "owner_id",
	2: "title",
	3: "content",
	4: "source",
	5: "source_type",
	6: "visibility",
	7: "group_id",
	8: "conversation_id",
}

type IngestDocumentResp struct {
	Success       bool         `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Document      *RAGDocument `thrift:"document,2" frugal:"2,default,RAGDocument" json:"document"`
	ChunkCount    int64        `thrift:"chunk_count,3" frugal:"3,default,i64" json:"chunk_count"`
	EntityCount   int64        `thrift:"entity_count,4" frugal:"4,default,i64" json:"entity_count"`
	RelationCount int64        `thrift:"relation_count,5" frugal:"5,default,i64" json:"relation_count"`
	Msg           string       `thrift:"msg,6" frugal:"6,default,string" json:"msg"`
}

func NewIngestDocumentResp() *IngestDocumentResp {
	return &IngestDocumentResp{}
}

func (p *IngestDocumentResp) InitDefault() {
}

func (p *IngestDocumentResp) GetSuccess() (v bool) {
	return p.Success
}

var IngestDocumentResp_Document_DEFAULT *RAGDocument

func (p *IngestDocumentResp) GetDocument() (v *RAGDocument) {
	if !p.IsSetDocument() {
		return IngestDocumentResp_Document_DEFAULT
	}
	return p.Document
}

func (p *IngestDocumentResp) GetChunkCount() (v int64) {
	return p.ChunkCount
}

func (p *IngestDocumentResp) GetEntityCount() (v int64) {
	return p.EntityCount
}

func (p *IngestDocumentResp) GetRelationCount() (v int64) {
	return p.RelationCount
}

func (p *IngestDocumentResp) GetMsg() (v string) {
	return p.Msg
}
func (p *IngestDocumentResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *IngestDocumentResp) SetDocument(val *RAGDocument) {
	p.Document = val
}
func (p *IngestDocumentResp) SetChunkCount(val int64) {
	p.ChunkCount = val
}
func (p *IngestDocumentResp) SetEntityCount(val int64) {
	p.EntityCount = val
}
func (p *IngestDocumentResp) SetRelationCount(val int64) {
	p.RelationCount = val
}
func (p *IngestDocumentResp) SetMsg(val string) {
	p.Msg = val
}

func (p *IngestDocumentResp) IsSetDocument() bool {
	return p.Document != nil
}

func (p *IngestDocumentResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IngestDocumentResp(%+v)", *p)
}

var fieldIDToName_IngestDocumentResp = map[int16]string{
	1: "success",
	2: "document",
	3: "chunk_count",
	4: "entity_count",
	5: "relation_count",
	6: "msg",
}

type SearchReq struct {
	ViewerId       int64  `thrift:"viewer_id,1" frugal:"1,default,i64" json:"viewer_id"`
	Query          string `thrift:"query,2" frugal:"2,default,string" json:"query"`
	Mode           string `thrift:"mode,3" frugal:"3,default,string" json:"mode"`
	Limit          int64  `thrift:"limit,4" frugal:"4,default,i64" json:"limit"`
	GroupId        int64  `thrift:"group_id,5" frugal:"5,default,i64" json:"group_id"`
	ConversationId int64  `thrift:"conversation_id,6" frugal:"6,default,i64" json:"conversation_id"`
	DocumentId     int64  `thrift:"document_id,7" frugal:"7,default,i64" json:"document_id"`
}

func NewSearchReq() *SearchReq {
	return &SearchReq{}
}

func (p *SearchReq) InitDefault() {
}

func (p *SearchReq) GetViewerId() (v int64) {
	return p.ViewerId
}

func (p *SearchReq) GetQuery() (v string) {
	return p.Query
}

func (p *SearchReq) GetMode() (v string) {
	return p.Mode
}

func (p *SearchReq) GetLimit() (v int64) {
	return p.Limit
}

func (p *SearchReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *SearchReq) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *SearchReq) GetDocumentId() (v int64) {
	return p.DocumentId
}
func (p *SearchReq) SetViewerId(val int64) {
	p.ViewerId = val
}
func (p *SearchReq) SetQuery(val string) {
	p.Query = val
}
func (p *SearchReq) SetMode(val string) {
	p.Mode = val
}
func (p *SearchReq) SetLimit(val int64) {
	p.Limit = val
}
func (p *SearchReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *SearchReq) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *SearchReq) SetDocumentId(val int64) {
	p.DocumentId = val
}

func (p *SearchReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchReq(%+v)", *p)
}

var fieldIDToName_SearchReq = map[int16]string{
	1: "viewer_id",
	2: "query",
	3: "mode",
	4: "limit",
	5: "group_id",
	6: "conversation_id",
	7: "document_id",
}

type SelfRAGCheckpoints struct {
	Retrieve bool   `thrift:"retrieve,1" frugal:"1,default,bool" json:"retrieve"`
	IsRel    bool   `thrift:"is_rel,2" frugal:"2,default,bool" json:"is_rel"`
	IsSup    bool   `thrift:"is_sup,3" frugal:"3,default,bool" json:"is_sup"`
	IsUse    bool   `thrift:"is_use,4" frugal:"4,default,bool" json:"is_use"`
	Note     string `thrift:"note,5" frugal:"5,default,string" json:"note"`
}

func NewSelfRAGCheckpoints() *SelfRAGCheckpoints {
	return &SelfRAGCheckpoints{}
}

func (p *SelfRAGCheckpoints) InitDefault() {
}

func (p *SelfRAGCheckpoints) GetRetrieve() (v bool) {
	return p.Retrieve
}

func (p *SelfRAGCheckpoints) GetIsRel() (v bool) {
	return p.IsRel
}

func (p *SelfRAGCheckpoints) GetIsSup() (v bool) {
	return p.IsSup
}

func (p *SelfRAGCheckpoints) GetIsUse() (v bool) {
	return p.IsUse
}

func (p *SelfRAGCheckpoints) GetNote() (v string) {
	return p.Note
}
func (p *SelfRAGCheckpoints) SetRetrieve(val bool) {
	p.Retrieve = val
}
func (p *SelfRAGCheckpoints) SetIsRel(val bool) {
	p.IsRel = val
}
func (p *SelfRAGCheckpoints) SetIsSup(val bool) {
	p.IsSup = val
}
func (p *SelfRAGCheckpoints) SetIsUse(val bool) {
	p.IsUse = val
}
func (p *SelfRAGCheckpoints) SetNote(val string) {
	p.Note = val
}

func (p *SelfRAGCheckpoints) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SelfRAGCheckpoints(%+v)", *p)
}

var fieldIDToName_SelfRAGCheckpoints = map[int16]string{
	1: "retrieve",
	2: "is_rel",
	3: "is_sup",
	4: "is_use",
	5: "note",
}

type SearchResp struct {
	Success    bool                `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Answer     string              `thrift:"answer,2" frugal:"2,default,string" json:"answer"`
	Sources    []*RAGSource        `thrift:"sources,3" frugal:"3,default,list<RAGSource>" json:"sources"`
	GraphNodes []*RAGGraphNode     `thrift:"graph_nodes,4" frugal:"4,default,list<RAGGraphNode>" json:"graph_nodes"`
	GraphEdges []*RAGGraphEdge     `thrift:"graph_edges,5" frugal:"5,default,list<RAGGraphEdge>" json:"graph_edges"`
	Route      string              `thrift:"route,6" frugal:"6,default,string" json:"route"`
	CragAction string              `thrift:"crag_action,7" frugal:"7,default,string" json:"crag_action"`
	SelfCheck  *SelfRAGCheckpoints `thrift:"self_check,8" frugal:"8,default,SelfRAGCheckpoints" json:"self_check"`
	Msg        string              `thrift:"msg,9" frugal:"9,default,string" json:"msg"`
}

func NewSearchResp() *SearchResp {
	return &SearchResp{}
}

func (p *SearchResp) InitDefault() {
}

func (p *SearchResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *SearchResp) GetAnswer() (v string) {
	return p.Answer
}

func (p *SearchResp) GetSources() (v []*RAGSource) {
	return p.Sources
}

func (p *SearchResp) GetGraphNodes() (v []*RAGGraphNode) {
	return p.GraphNodes
}

func (p *SearchResp) GetGraphEdges() (v []*RAGGraphEdge) {
	return p.GraphEdges
}

func (p *SearchResp) GetRoute() (v string) {
	return p.Route
}

func (p *SearchResp) GetCragAction() (v string) {
	return p.CragAction
}

var SearchResp_SelfCheck_DEFAULT *SelfRAGCheckpoints

func (p *SearchResp) GetSelfCheck() (v *SelfRAGCheckpoints) {
	if !p.IsSetSelfCheck() {
		return SearchResp_SelfCheck_DEFAULT
	}
	return p.SelfCheck
}

func (p *SearchResp) GetMsg() (v string) {
	return p.Msg
}
func (p *SearchResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *SearchResp) SetAnswer(val string) {
	p.Answer = val
}
func (p *SearchResp) SetSources(val []*RAGSource) {
	p.Sources = val
}
func (p *SearchResp) SetGraphNodes(val []*RAGGraphNode) {
	p.GraphNodes = val
}
func (p *SearchResp) SetGraphEdges(val []*RAGGraphEdge) {
	p.GraphEdges = val
}
func (p *SearchResp) SetRoute(val string) {
	p.Route = val
}
func (p *SearchResp) SetCragAction(val string) {
	p.CragAction = val
}
func (p *SearchResp) SetSelfCheck(val *SelfRAGCheckpoints) {
	p.SelfCheck = val
}
func (p *SearchResp) SetMsg(val string) {
	p.Msg = val
}

func (p *SearchResp) IsSetSelfCheck() bool {
	return p.SelfCheck != nil
}

func (p *SearchResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchResp(%+v)", *p)
}

var fieldIDToName_SearchResp = map[int16]string{
	1: "success",
	2: "answer",
	3: "sources",
	4: "graph_nodes",
	5: "graph_edges",
	6: "route",
	7: "crag_action",
	8: "self_check",
	9: "msg",
}

type GraphReq struct {
	ViewerId   int64  `thrift:"viewer_id,1" frugal:"1,default,i64" json:"viewer_id"`
	Query      string `thrift:"query,2" frugal:"2,default,string" json:"query"`
	Limit      int64  `thrift:"limit,3" frugal:"3,default,i64" json:"limit"`
	DocumentId int64  `thrift:"document_id,4" frugal:"4,default,i64" json:"document_id"`
	Hops       int64  `thrift:"hops,5" frugal:"5,default,i64" json:"hops"`
}

func NewGraphReq() *GraphReq {
	return &GraphReq{}
}

func (p *GraphReq) InitDefault() {
}

func (p *GraphReq) GetViewerId() (v int64) {
	return p.ViewerId
}

func (p *GraphReq) GetQuery() (v string) {
	return p.Query
}

func (p *GraphReq) GetLimit() (v int64) {
	return p.Limit
}

func (p *GraphReq) GetDocumentId() (v int64) {
	return p.DocumentId
}

func (p *GraphReq) GetHops() (v int64) {
	return p.Hops
}
func (p *GraphReq) SetViewerId(val int64) {
	p.ViewerId = val
}
func (p *GraphReq) SetQuery(val string) {
	p.Query = val
}
func (p *GraphReq) SetLimit(val int64) {
	p.Limit = val
}
func (p *GraphReq) SetDocumentId(val int64) {
	p.DocumentId = val
}
func (p *GraphReq) SetHops(val int64) {
	p.Hops = val
}

func (p *GraphReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GraphReq(%+v)", *p)
}

var fieldIDToName_GraphReq = map[int16]string{
	1: "viewer_id",
	2: "query",
	3: "limit",
	4: "document_id",
	5: "hops",
}

type GraphResp struct {
	Success     bool                 `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Nodes       []*RAGGraphNode      `thrift:"nodes,2" frugal:"2,default,list<RAGGraphNode>" json:"nodes"`
	Edges       []*RAGGraphEdge      `thrift:"edges,3" frugal:"3,default,list<RAGGraphEdge>" json:"edges"`
	Communities []*RAGGraphCommunity `thrift:"communities,4" frugal:"4,default,list<RAGGraphCommunity>" json:"communities"`
	Msg         string               `thrift:"msg,5" frugal:"5,default,string" json:"msg"`
}

func NewGraphResp() *GraphResp {
	return &GraphResp{}
}

func (p *GraphResp) InitDefault() {
}

func (p *GraphResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *GraphResp) GetNodes() (v []*RAGGraphNode) {
	return p.Nodes
}

func (p *GraphResp) GetEdges() (v []*RAGGraphEdge) {
	return p.Edges
}

func (p *GraphResp) GetCommunities() (v []*RAGGraphCommunity) {
	return p.Communities
}

func (p *GraphResp) GetMsg() (v string) {
	return p.Msg
}
func (p *GraphResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *GraphResp) SetNodes(val []*RAGGraphNode) {
	p.Nodes = val
}
func (p *GraphResp) SetEdges(val []*RAGGraphEdge) {
	p.Edges = val
}
func (p *GraphResp) SetCommunities(val []*RAGGraphCommunity) {
	p.Communities = val
}
func (p *GraphResp) SetMsg(val string) {
	p.Msg = val
}

func (p *GraphResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GraphResp(%+v)", *p)
}

var fieldIDToName_GraphResp = map[int16]string{
	1: "success",
	2: "nodes",
	3: "edges",
	4: "communities",
	5: "msg",
}

type ListDocumentsReq struct {
	ViewerId int64 `thrift:"viewer_id,1" frugal:"1,default,i64" json:"viewer_id"`
	Limit    int64 `thrift:"limit,2" frugal:"2,default,i64" json:"limit"`
	Offset   int64 `thrift:"offset,3" frugal:"3,default,i64" json:"offset"`
}

func NewListDocumentsReq() *ListDocumentsReq {
	return &ListDocumentsReq{}
}

func (p *ListDocumentsReq) InitDefault() {
}

func (p *ListDocumentsReq) GetViewerId() (v int64) {
	return p.ViewerId
}

func (p *ListDocumentsReq) GetLimit() (v int64) {
	return p.Limit
}

func (p *ListDocumentsReq) GetOffset() (v int64) {
	return p.Offset
}
func (p *ListDocumentsReq) SetViewerId(val int64) {
	p.ViewerId = val
}
func (p *ListDocumentsReq) SetLimit(val int64) {
	p.Limit = val
}
func (p *ListDocumentsReq) SetOffset(val int64) {
	p.Offset = val
}

func (p *ListDocumentsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListDocumentsReq(%+v)", *p)
}

var fieldIDToName_ListDocumentsReq = map[int16]string{
	1: "viewer_id",
	2: "limit",
	3: "offset",
}

type ListDocumentsResp struct {
	Success   bool           `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Documents []*RAGDocument `thrift:"documents,2" frugal:"2,default,list<RAGDocument>" json:"documents"`
	Total     int64          `thrift:"total,3" frugal:"3,default,i64" json:"total"`
	Msg       string         `thrift:"msg,4" frugal:"4,default,string" json:"msg"`
}

func NewListDocumentsResp() *ListDocumentsResp {
	return &ListDocumentsResp{}
}

func (p *ListDocumentsResp) InitDefault() {
}

func (p *ListDocumentsResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *ListDocumentsResp) GetDocuments() (v []*RAGDocument) {
	return p.Documents
}

func (p *ListDocumentsResp) GetTotal() (v int64) {
	return p.Total
}

func (p *ListDocumentsResp) GetMsg() (v string) {
	return p.Msg
}
func (p *ListDocumentsResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *ListDocumentsResp) SetDocuments(val []*RAGDocument) {
	p.Documents = val
}
func (p *ListDocumentsResp) SetTotal(val int64) {
	p.Total = val
}
func (p *ListDocumentsResp) SetMsg(val string) {
	p.Msg = val
}

func (p *ListDocumentsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListDocumentsResp(%+v)", *p)
}

var fieldIDToName_ListDocumentsResp = map[int16]string{
	1: "success",
	2: "documents",
	3: "total",
	4: "msg",
}

type DeleteDocumentReq struct {
	ViewerId   int64 `thrift:"viewer_id,1" frugal:"1,default,i64" json:"viewer_id"`
	DocumentId int64 `thrift:"document_id,2" frugal:"2,default,i64" json:"document_id"`
}

func NewDeleteDocumentReq() *DeleteDocumentReq {
	return &DeleteDocumentReq{}
}

func (p *DeleteDocumentReq) InitDefault() {
}

func (p *DeleteDocumentReq) GetViewerId() (v int64) {
	return p.ViewerId
}

func (p *DeleteDocumentReq) GetDocumentId() (v int64) {
	return p.DocumentId
}
func (p *DeleteDocumentReq) SetViewerId(val int64) {
	p.ViewerId = val
}
func (p *DeleteDocumentReq) SetDocumentId(val int64) {
	p.DocumentId = val
}

func (p *DeleteDocumentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteDocumentReq(%+v)", *p)
}

var fieldIDToName_DeleteDocumentReq = map[int16]string{
	1: "viewer_id",
	2: "document_id",
}

type DeleteDocumentResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Msg     string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewDeleteDocumentResp() *DeleteDocumentResp {
	return &DeleteDocumentResp{}
}

func (p *DeleteDocumentResp) InitDefault() {
}

func (p *DeleteDocumentResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *DeleteDocumentResp) GetMsg() (v string) {
	return p.Msg
}
func (p *DeleteDocumentResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *DeleteDocumentResp) SetMsg(val string) {
	p.Msg = val
}

func (p *DeleteDocumentResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteDocumentResp(%+v)", *p)
}

var fieldIDToName_DeleteDocumentResp = map[int16]string{
	1: "success",
	2: "msg",
}

type DeleteGraphReq struct {
	ViewerId   int64 `thrift:"viewer_id,1" frugal:"1,default,i64" json:"viewer_id"`
	DocumentId int64 `thrift:"document_id,2" frugal:"2,default,i64" json:"document_id"`
}

func NewDeleteGraphReq() *DeleteGraphReq {
	return &DeleteGraphReq{}
}

func (p *DeleteGraphReq) InitDefault() {
}

func (p *DeleteGraphReq) GetViewerId() (v int64) {
	return p.ViewerId
}

func (p *DeleteGraphReq) GetDocumentId() (v int64) {
	return p.DocumentId
}
func (p *DeleteGraphReq) SetViewerId(val int64) {
	p.ViewerId = val
}
func (p *DeleteGraphReq) SetDocumentId(val int64) {
	p.DocumentId = val
}

func (p *DeleteGraphReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteGraphReq(%+v)", *p)
}

var fieldIDToName_DeleteGraphReq = map[int16]string{
	1: "viewer_id",
	2: "document_id",
}

type DeleteGraphResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Msg     string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewDeleteGraphResp() *DeleteGraphResp {
	return &DeleteGraphResp{}
}

func (p *DeleteGraphResp) InitDefault() {
}

func (p *DeleteGraphResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *DeleteGraphResp) GetMsg() (v string) {
	return p.Msg
}
func (p *DeleteGraphResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *DeleteGraphResp) SetMsg(val string) {
	p.Msg = val
}

func (p *DeleteGraphResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteGraphResp(%+v)", *p)
}

var fieldIDToName_DeleteGraphResp = map[int16]string{
	1: "success",
	2: "msg",
}

type RAGService interface {
	IngestDocument(ctx context.Context, req *IngestDocumentReq) (r *IngestDocumentResp, err error)

	Search(ctx context.Context, req *SearchReq) (r *SearchResp, err error)

	GetGraph(ctx context.Context, req *GraphReq) (r *GraphResp, err error)

	ListDocuments(ctx context.Context, req *ListDocumentsReq) (r *ListDocumentsResp, err error)

	DeleteDocument(ctx context.Context, req *DeleteDocumentReq) (r *DeleteDocumentResp, err error)

	DeleteDocumentGraph(ctx context.Context, req *DeleteGraphReq) (r *DeleteGraphResp, err error)
}

type RAGServiceIngestDocumentArgs struct {
	Req *IngestDocumentReq `thrift:"req,1" frugal:"1,default,IngestDocumentReq" json:"req"`
}

func NewRAGServiceIngestDocumentArgs() *RAGServiceIngestDocumentArgs {
	return &RAGServiceIngestDocumentArgs{}
}

func (p *RAGServiceIngestDocumentArgs) InitDefault() {
}

var RAGServiceIngestDocumentArgs_Req_DEFAULT *IngestDocumentReq

func (p *RAGServiceIngestDocumentArgs) GetReq() (v *IngestDocumentReq) {
	if !p.IsSetReq() {
		return RAGServiceIngestDocumentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceIngestDocumentArgs) SetReq(val *IngestDocumentReq) {
	p.Req = val
}

func (p *RAGServiceIngestDocumentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceIngestDocumentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceIngestDocumentArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceIngestDocumentArgs = map[int16]string{
	1: "req",
}

type RAGServiceIngestDocumentResult struct {
	Success *IngestDocumentResp `thrift:"success,0,optional" frugal:"0,optional,IngestDocumentResp" json:"success,omitempty"`
}

func NewRAGServiceIngestDocumentResult() *RAGServiceIngestDocumentResult {
	return &RAGServiceIngestDocumentResult{}
}

func (p *RAGServiceIngestDocumentResult) InitDefault() {
}

var RAGServiceIngestDocumentResult_Success_DEFAULT *IngestDocumentResp

func (p *RAGServiceIngestDocumentResult) GetSuccess() (v *IngestDocumentResp) {
	if !p.IsSetSuccess() {
		return RAGServiceIngestDocumentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceIngestDocumentResult) SetSuccess(x interface{}) {
	p.Success = x.(*IngestDocumentResp)
}

func (p *RAGServiceIngestDocumentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceIngestDocumentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceIngestDocumentResult(%+v)", *p)
}

var fieldIDToName_RAGServiceIngestDocumentResult = map[int16]string{
	0: "success",
}

type RAGServiceSearchArgs struct {
	Req *SearchReq `thrift:"req,1" frugal:"1,default,SearchReq" json:"req"`
}

func NewRAGServiceSearchArgs() *RAGServiceSearchArgs {
	return &RAGServiceSearchArgs{}
}

func (p *RAGServiceSearchArgs) InitDefault() {
}

var RAGServiceSearchArgs_Req_DEFAULT *SearchReq

func (p *RAGServiceSearchArgs) GetReq() (v *SearchReq) {
	if !p.IsSetReq() {
		return RAGServiceSearchArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceSearchArgs) SetReq(val *SearchReq) {
	p.Req = val
}

func (p *RAGServiceSearchArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceSearchArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceSearchArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceSearchArgs = map[int16]string{
	1: "req",
}

type RAGServiceSearchResult struct {
	Success *SearchResp `thrift:"success,0,optional" frugal:"0,optional,SearchResp" json:"success,omitempty"`
}

func NewRAGServiceSearchResult() *RAGServiceSearchResult {
	return &RAGServiceSearchResult{}
}

func (p *RAGServiceSearchResult) InitDefault() {
}

var RAGServiceSearchResult_Success_DEFAULT *SearchResp

func (p *RAGServiceSearchResult) GetSuccess() (v *SearchResp) {
	if !p.IsSetSuccess() {
		return RAGServiceSearchResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceSearchResult) SetSuccess(x interface{}) {
	p.Success = x.(*SearchResp)
}

func (p *RAGServiceSearchResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceSearchResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceSearchResult(%+v)", *p)
}

var fieldIDToName_RAGServiceSearchResult = map[int16]string{
	0: "success",
}

type RAGServiceGetGraphArgs struct {
	Req *GraphReq `thrift:"req,1" frugal:"1,default,GraphReq" json:"req"`
}

func NewRAGServiceGetGraphArgs() *RAGServiceGetGraphArgs {
	return &RAGServiceGetGraphArgs{}
}

func (p *RAGServiceGetGraphArgs) InitDefault() {
}

var RAGServiceGetGraphArgs_Req_DEFAULT *GraphReq

func (p *RAGServiceGetGraphArgs) GetReq() (v *GraphReq) {
	if !p.IsSetReq() {
		return RAGServiceGetGraphArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceGetGraphArgs) SetReq(val *GraphReq) {
	p.Req = val
}

func (p *RAGServiceGetGraphArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceGetGraphArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceGetGraphArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceGetGraphArgs = map[int16]string{
	1: "req",
}

type RAGServiceGetGraphResult struct {
	Success *GraphResp `thrift:"success,0,optional" frugal:"0,optional,GraphResp" json:"success,omitempty"`
}

func NewRAGServiceGetGraphResult() *RAGServiceGetGraphResult {
	return &RAGServiceGetGraphResult{}
}

func (p *RAGServiceGetGraphResult) InitDefault() {
}

var RAGServiceGetGraphResult_Success_DEFAULT *GraphResp

func (p *RAGServiceGetGraphResult) GetSuccess() (v *GraphResp) {
	if !p.IsSetSuccess() {
		return RAGServiceGetGraphResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceGetGraphResult) SetSuccess(x interface{}) {
	p.Success = x.(*GraphResp)
}

func (p *RAGServiceGetGraphResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceGetGraphResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceGetGraphResult(%+v)", *p)
}

var fieldIDToName_RAGServiceGetGraphResult = map[int16]string{
	0: "success",
}

type RAGServiceListDocumentsArgs struct {
	Req *ListDocumentsReq `thrift:"req,1" frugal:"1,default,ListDocumentsReq" json:"req"`
}

func NewRAGServiceListDocumentsArgs() *RAGServiceListDocumentsArgs {
	return &RAGServiceListDocumentsArgs{}
}

func (p *RAGServiceListDocumentsArgs) InitDefault() {
}

var RAGServiceListDocumentsArgs_Req_DEFAULT *ListDocumentsReq

func (p *RAGServiceListDocumentsArgs) GetReq() (v *ListDocumentsReq) {
	if !p.IsSetReq() {
		return RAGServiceListDocumentsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceListDocumentsArgs) SetReq(val *ListDocumentsReq) {
	p.Req = val
}

func (p *RAGServiceListDocumentsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceListDocumentsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceListDocumentsArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceListDocumentsArgs = map[int16]string{
	1: "req",
}

type RAGServiceListDocumentsResult struct {
	Success *ListDocumentsResp `thrift:"success,0,optional" frugal:"0,optional,ListDocumentsResp" json:"success,omitempty"`
}

func NewRAGServiceListDocumentsResult() *RAGServiceListDocumentsResult {
	return &RAGServiceListDocumentsResult{}
}

func (p *RAGServiceListDocumentsResult) InitDefault() {
}

var RAGServiceListDocumentsResult_Success_DEFAULT *ListDocumentsResp

func (p *RAGServiceListDocumentsResult) GetSuccess() (v *ListDocumentsResp) {
	if !p.IsSetSuccess() {
		return RAGServiceListDocumentsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceListDocumentsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListDocumentsResp)
}

func (p *RAGServiceListDocumentsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceListDocumentsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceListDocumentsResult(%+v)", *p)
}

var fieldIDToName_RAGServiceListDocumentsResult = map[int16]string{
	0: "success",
}

type RAGServiceDeleteDocumentArgs struct {
	Req *DeleteDocumentReq `thrift:"req,1" frugal:"1,default,DeleteDocumentReq" json:"req"`
}

func NewRAGServiceDeleteDocumentArgs() *RAGServiceDeleteDocumentArgs {
	return &RAGServiceDeleteDocumentArgs{}
}

func (p *RAGServiceDeleteDocumentArgs) InitDefault() {
}

var RAGServiceDeleteDocumentArgs_Req_DEFAULT *DeleteDocumentReq

func (p *RAGServiceDeleteDocumentArgs) GetReq() (v *DeleteDocumentReq) {
	if !p.IsSetReq() {
		return RAGServiceDeleteDocumentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceDeleteDocumentArgs) SetReq(val *DeleteDocumentReq) {
	p.Req = val
}

func (p *RAGServiceDeleteDocumentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceDeleteDocumentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceDeleteDocumentArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceDeleteDocumentArgs = map[int16]string{
	1: "req",
}

type RAGServiceDeleteDocumentResult struct {
	Success *DeleteDocumentResp `thrift:"success,0,optional" frugal:"0,optional,DeleteDocumentResp" json:"success,omitempty"`
}

func NewRAGServiceDeleteDocumentResult() *RAGServiceDeleteDocumentResult {
	return &RAGServiceDeleteDocumentResult{}
}

func (p *RAGServiceDeleteDocumentResult) InitDefault() {
}

var RAGServiceDeleteDocumentResult_Success_DEFAULT *DeleteDocumentResp

func (p *RAGServiceDeleteDocumentResult) GetSuccess() (v *DeleteDocumentResp) {
	if !p.IsSetSuccess() {
		return RAGServiceDeleteDocumentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceDeleteDocumentResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteDocumentResp)
}

func (p *RAGServiceDeleteDocumentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceDeleteDocumentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceDeleteDocumentResult(%+v)", *p)
}

var fieldIDToName_RAGServiceDeleteDocumentResult = map[int16]string{
	0: "success",
}

type RAGServiceDeleteDocumentGraphArgs struct {
	Req *DeleteGraphReq `thrift:"req,1" frugal:"1,default,DeleteGraphReq" json:"req"`
}

func NewRAGServiceDeleteDocumentGraphArgs() *RAGServiceDeleteDocumentGraphArgs {
	return &RAGServiceDeleteDocumentGraphArgs{}
}

func (p *RAGServiceDeleteDocumentGraphArgs) InitDefault() {
}

var RAGServiceDeleteDocumentGraphArgs_Req_DEFAULT *DeleteGraphReq

func (p *RAGServiceDeleteDocumentGraphArgs) GetReq() (v *DeleteGraphReq) {
	if !p.IsSetReq() {
		return RAGServiceDeleteDocumentGraphArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceDeleteDocumentGraphArgs) SetReq(val *DeleteGraphReq) {
	p.Req = val
}

func (p *RAGServiceDeleteDocumentGraphArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceDeleteDocumentGraphArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceDeleteDocumentGraphArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceDeleteDocumentGraphArgs = map[int16]string{
	1: "req",
}

type RAGServiceDeleteDocumentGraphResult struct {
	Success *DeleteGraphResp `thrift:"success,0,optional" frugal:"0,optional,DeleteGraphResp" json:"success,omitempty"`
}

func NewRAGServiceDeleteDocumentGraphResult() *RAGServiceDeleteDocumentGraphResult {
	return &RAGServiceDeleteDocumentGraphResult{}
}

func (p *RAGServiceDeleteDocumentGraphResult) InitDefault() {
}

var RAGServiceDeleteDocumentGraphResult_Success_DEFAULT *DeleteGraphResp

func (p *RAGServiceDeleteDocumentGraphResult) GetSuccess() (v *DeleteGraphResp) {
	if !p.IsSetSuccess() {
		return RAGServiceDeleteDocumentGraphResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceDeleteDocumentGraphResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteGraphResp)
}

func (p *RAGServiceDeleteDocumentGraphResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceDeleteDocumentGraphResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceDeleteDocumentGraphResult(%+v)", *p)
}

var fieldIDToName_RAGServiceDeleteDocumentGraphResult = map[int16]string{
	0: "success",
}
