// Code generated by Kitex v0.16.2. DO NOT EDIT.

package adminservice

import (
	admin "ClaranAIM/kitex_gen/admin"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetDashboard(ctx context.Context, req *admin.DashboardReq, callOptions ...callopt.Option) (r *admin.DashboardResp, err error)
	ListUsers(ctx context.Context, req *admin.ListUsersReq, callOptions ...callopt.Option) (r *admin.ListUsersResp, err error)
	ListGroups(ctx context.Context, req *admin.ListGroupsReq, callOptions ...callopt.Option) (r *admin.ListGroupsResp, err error)
	ListFiles(ctx context.Context, req *admin.ListFilesReq, callOptions ...callopt.Option) (r *admin.ListFilesResp, err error)
	ListAgents(ctx context.Context, req *admin.ListAgentsReq, callOptions ...callopt.Option) (r *admin.ListAgentsResp, err error)
	ListBilling(ctx context.Context, req *admin.ListBillingReq, callOptions ...callopt.Option) (r *admin.ListBillingResp, err error)
	ListReviews(ctx context.Context, req *admin.ListReviewsReq, callOptions ...callopt.Option) (r *admin.ListReviewsResp, err error)
	ReviewItem(ctx context.Context, req *admin.ReviewReq, callOptions ...callopt.Option) (r *admin.ReviewResp, err error)
	ListMCPTraces(ctx context.Context, req *admin.ListMCPTracesReq, callOptions ...callopt.Option) (r *admin.ListMCPTracesResp, err error)
	SaveNotice(ctx context.Context, req *admin.SaveNoticeReq, callOptions ...callopt.Option) (r *admin.NoticeResp, err error)
	ListNotices(ctx context.Context, req *admin.ListNoticesReq, callOptions ...callopt.Option) (r *admin.ListNoticesResp, err error)
	ListAuditLogs(ctx context.Context, req *admin.ListAuditLogsReq, callOptions ...callopt.Option) (r *admin.ListAuditLogsResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAdminServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAdminServiceClient struct {
	*kClient
}

func (p *kAdminServiceClient) GetDashboard(ctx context.Context, req *admin.DashboardReq, callOptions ...callopt.Option) (r *admin.DashboardResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDashboard(ctx, req)
}

func (p *kAdminServiceClient) ListUsers(ctx context.Context, req *admin.ListUsersReq, callOptions ...callopt.Option) (r *admin.ListUsersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListUsers(ctx, req)
}

func (p *kAdminServiceClient) ListGroups(ctx context.Context, req *admin.ListGroupsReq, callOptions ...callopt.Option) (r *admin.ListGroupsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListGroups(ctx, req)
}

func (p *kAdminServiceClient) ListFiles(ctx context.Context, req *admin.ListFilesReq, callOptions ...callopt.Option) (r *admin.ListFilesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFiles(ctx, req)
}

func (p *kAdminServiceClient) ListAgents(ctx context.Context, req *admin.ListAgentsReq, callOptions ...callopt.Option) (r *admin.ListAgentsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAgents(ctx, req)
}

func (p *kAdminServiceClient) ListBilling(ctx context.Context, req *admin.ListBillingReq, callOptions ...callopt.Option) (r *admin.ListBillingResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListBilling(ctx, req)
}

func (p *kAdminServiceClient) ListReviews(ctx context.Context, req *admin.ListReviewsReq, callOptions ...callopt.Option) (r *admin.ListReviewsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListReviews(ctx, req)
}

func (p *kAdminServiceClient) ReviewItem(ctx context.Context, req *admin.ReviewReq, callOptions ...callopt.Option) (r *admin.ReviewResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReviewItem(ctx, req)
}

func (p *kAdminServiceClient) ListMCPTraces(ctx context.Context, req *admin.ListMCPTracesReq, callOptions ...callopt.Option) (r *admin.ListMCPTracesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListMCPTraces(ctx, req)
}

func (p *kAdminServiceClient) SaveNotice(ctx context.Context, req *admin.SaveNoticeReq, callOptions ...callopt.Option) (r *admin.NoticeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SaveNotice(ctx, req)
}

func (p *kAdminServiceClient) ListNotices(ctx context.Context, req *admin.ListNoticesReq, callOptions ...callopt.Option) (r *admin.ListNoticesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListNotices(ctx, req)
}

func (p *kAdminServiceClient) ListAuditLogs(ctx context.Context, req *admin.ListAuditLogsReq, callOptions ...callopt.Option) (r *admin.ListAuditLogsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAuditLogs(ctx, req)
}
