// Code generated by Kitex v0.16.2. DO NOT EDIT.

package userservice

import (
	user "ClaranAIM/kitex_gen/user"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *user.RegisterReq, callOptions ...callopt.Option) (r *user.RegisterResp, err error)
	Login(ctx context.Context, req *user.LoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error)
	GetUserInfo(ctx context.Context, req *user.GetUserInfoReq, callOptions ...callopt.Option) (r *user.GetUserInfoResp, err error)
	UpdateUserInfo(ctx context.Context, req *user.UpdateUserInfoReq, callOptions ...callopt.Option) (r *user.UpdateUserInfoResp, err error)
	UpdateAvatar(ctx context.Context, req *user.UpdateAvatarReq, callOptions ...callopt.Option) (r *user.UpdateAvatarResp, err error)
	UpdateStatus(ctx context.Context, req *user.UpdateStatusReq, callOptions ...callopt.Option) (r *user.UpdateStatusResp, err error)
	UpdateRole(ctx context.Context, req *user.UpdateRoleReq, callOptions ...callopt.Option) (r *user.UpdateRoleResp, err error)
	AddFriend(ctx context.Context, req *user.AddFriendReq, callOptions ...callopt.Option) (r *user.AddFriendResp, err error)
	DeleteFriend(ctx context.Context, req *user.DeleteFriendReq, callOptions ...callopt.Option) (r *user.DeleteFriendResp, err error)
	GetFriendList(ctx context.Context, req *user.GetFriendListReq, callOptions ...callopt.Option) (r *user.GetFriendListResp, err error)
	UpdateFriendRemark(ctx context.Context, req *user.UpdateFriendRemarkReq, callOptions ...callopt.Option) (r *user.UpdateFriendRemarkResp, err error)
	CreateFriendGroup(ctx context.Context, req *user.CreateFriendGroupReq, callOptions ...callopt.Option) (r *user.CreateFriendGroupResp, err error)
	MoveFriendGroup(ctx context.Context, req *user.MoveFriendGroupReq, callOptions ...callopt.Option) (r *user.MoveFriendGroupResp, err error)
	GetFriendGroups(ctx context.Context, req *user.GetFriendGroupsReq, callOptions ...callopt.Option) (r *user.GetFriendGroupsResp, err error)
	BatchGetUserInfo(ctx context.Context, req *user.BatchGetUserInfoReq, callOptions ...callopt.Option) (r *user.BatchGetUserInfoResp, err error)
	AdminListUsers(ctx context.Context, req *user.AdminListUsersReq, callOptions ...callopt.Option) (r *user.AdminListUsersResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Register(ctx context.Context, req *user.RegisterReq, callOptions ...callopt.Option) (r *user.RegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kUserServiceClient) Login(ctx context.Context, req *user.LoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kUserServiceClient) GetUserInfo(ctx context.Context, req *user.GetUserInfoReq, callOptions ...callopt.Option) (r *user.GetUserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInfo(ctx, req)
}

func (p *kUserServiceClient) UpdateUserInfo(ctx context.Context, req *user.UpdateUserInfoReq, callOptions ...callopt.Option) (r *user.UpdateUserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserInfo(ctx, req)
}

func (p *kUserServiceClient) UpdateAvatar(ctx context.Context, req *user.UpdateAvatarReq, callOptions ...callopt.Option) (r *user.UpdateAvatarResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateAvatar(ctx, req)
}

func (p *kUserServiceClient) UpdateStatus(ctx context.Context, req *user.UpdateStatusReq, callOptions ...callopt.Option) (r *user.UpdateStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateStatus(ctx, req)
}

func (p *kUserServiceClient) UpdateRole(ctx context.Context, req *user.UpdateRoleReq, callOptions ...callopt.Option) (r *user.UpdateRoleResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateRole(ctx, req)
}

func (p *kUserServiceClient) AddFriend(ctx context.Context, req *user.AddFriendReq, callOptions ...callopt.Option) (r *user.AddFriendResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddFriend(ctx, req)
}

func (p *kUserServiceClient) DeleteFriend(ctx context.Context, req *user.DeleteFriendReq, callOptions ...callopt.Option) (r *user.DeleteFriendResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteFriend(ctx, req)
}

func (p *kUserServiceClient) GetFriendList(ctx context.Context, req *user.GetFriendListReq, callOptions ...callopt.Option) (r *user.GetFriendListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFriendList(ctx, req)
}

func (p *kUserServiceClient) UpdateFriendRemark(ctx context.Context, req *user.UpdateFriendRemarkReq, callOptions ...callopt.Option) (r *user.UpdateFriendRemarkResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateFriendRemark(ctx, req)
}

func (p *kUserServiceClient) CreateFriendGroup(ctx context.Context, req *user.CreateFriendGroupReq, callOptions ...callopt.Option) (r *user.CreateFriendGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateFriendGroup(ctx, req)
}

func (p *kUserServiceClient) MoveFriendGroup(ctx context.Context, req *user.MoveFriendGroupReq, callOptions ...callopt.Option) (r *user.MoveFriendGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MoveFriendGroup(ctx, req)
}

func (p *kUserServiceClient) GetFriendGroups(ctx context.Context, req *user.GetFriendGroupsReq, callOptions ...callopt.Option) (r *user.GetFriendGroupsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFriendGroups(ctx, req)
}

func (p *kUserServiceClient) BatchGetUserInfo(ctx context.Context, req *user.BatchGetUserInfoReq, callOptions ...callopt.Option) (r *user.BatchGetUserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchGetUserInfo(ctx, req)
}

func (p *kUserServiceClient) AdminListUsers(ctx context.Context, req *user.AdminListUsersReq, callOptions ...callopt.Option) (r *user.AdminListUsersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminListUsers(ctx, req)
}
