// Code generated by Kitex v0.16.2. DO NOT EDIT.

package userservice

import (
	user "ClaranAIM/kitex_gen/user"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserServiceRegisterArgs,
		newUserServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserServiceLoginArgs,
		newUserServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserInfo": kitex.NewMethodInfo(
		getUserInfoHandler,
		newUserServiceGetUserInfoArgs,
		newUserServiceGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUserInfo": kitex.NewMethodInfo(
		updateUserInfoHandler,
		newUserServiceUpdateUserInfoArgs,
		newUserServiceUpdateUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateAvatar": kitex.NewMethodInfo(
		updateAvatarHandler,
		newUserServiceUpdateAvatarArgs,
		newUserServiceUpdateAvatarResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateStatus": kitex.NewMethodInfo(
		updateStatusHandler,
		newUserServiceUpdateStatusArgs,
		newUserServiceUpdateStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddFriend": kitex.NewMethodInfo(
		addFriendHandler,
		newUserServiceAddFriendArgs,
		newUserServiceAddFriendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteFriend": kitex.NewMethodInfo(
		deleteFriendHandler,
		newUserServiceDeleteFriendArgs,
		newUserServiceDeleteFriendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFriendList": kitex.NewMethodInfo(
		getFriendListHandler,
		newUserServiceGetFriendListArgs,
		newUserServiceGetFriendListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateFriendRemark": kitex.NewMethodInfo(
		updateFriendRemarkHandler,
		newUserServiceUpdateFriendRemarkArgs,
		newUserServiceUpdateFriendRemarkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateFriendGroup": kitex.NewMethodInfo(
		createFriendGroupHandler,
		newUserServiceCreateFriendGroupArgs,
		newUserServiceCreateFriendGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MoveFriendGroup": kitex.NewMethodInfo(
		moveFriendGroupHandler,
		newUserServiceMoveFriendGroupArgs,
		newUserServiceMoveFriendGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFriendGroups": kitex.NewMethodInfo(
		getFriendGroupsHandler,
		newUserServiceGetFriendGroupsArgs,
		newUserServiceGetFriendGroupsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BatchGetUserInfo": kitex.NewMethodInfo(
		batchGetUserInfoHandler,
		newUserServiceBatchGetUserInfoArgs,
		newUserServiceBatchGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AdminListUsers": kitex.NewMethodInfo(
		adminListUsersHandler,
		newUserServiceAdminListUsersArgs,
		newUserServiceAdminListUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceRegisterArgs)
	realResult := result.(*user.UserServiceRegisterResult)
	success, err := handler.(user.UserService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegisterArgs() interface{} {
	return user.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return user.NewUserServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceLoginArgs)
	realResult := result.(*user.UserServiceLoginResult)
	success, err := handler.(user.UserService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginArgs() interface{} {
	return user.NewUserServiceLoginArgs()
}

func newUserServiceLoginResult() interface{} {
	return user.NewUserServiceLoginResult()
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetUserInfoArgs)
	realResult := result.(*user.UserServiceGetUserInfoResult)
	success, err := handler.(user.UserService).GetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserInfoArgs() interface{} {
	return user.NewUserServiceGetUserInfoArgs()
}

func newUserServiceGetUserInfoResult() interface{} {
	return user.NewUserServiceGetUserInfoResult()
}

func updateUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateUserInfoArgs)
	realResult := result.(*user.UserServiceUpdateUserInfoResult)
	success, err := handler.(user.UserService).UpdateUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateUserInfoArgs() interface{} {
	return user.NewUserServiceUpdateUserInfoArgs()
}

func newUserServiceUpdateUserInfoResult() interface{} {
	return user.NewUserServiceUpdateUserInfoResult()
}

func updateAvatarHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateAvatarArgs)
	realResult := result.(*user.UserServiceUpdateAvatarResult)
	success, err := handler.(user.UserService).UpdateAvatar(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateAvatarArgs() interface{} {
	return user.NewUserServiceUpdateAvatarArgs()
}

func newUserServiceUpdateAvatarResult() interface{} {
	return user.NewUserServiceUpdateAvatarResult()
}

func updateStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateStatusArgs)
	realResult := result.(*user.UserServiceUpdateStatusResult)
	success, err := handler.(user.UserService).UpdateStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateStatusArgs() interface{} {
	return user.NewUserServiceUpdateStatusArgs()
}

func newUserServiceUpdateStatusResult() interface{} {
	return user.NewUserServiceUpdateStatusResult()
}

func addFriendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceAddFriendArgs)
	realResult := result.(*user.UserServiceAddFriendResult)
	success, err := handler.(user.UserService).AddFriend(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceAddFriendArgs() interface{} {
	return user.NewUserServiceAddFriendArgs()
}

func newUserServiceAddFriendResult() interface{} {
	return user.NewUserServiceAddFriendResult()
}

func deleteFriendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceDeleteFriendArgs)
	realResult := result.(*user.UserServiceDeleteFriendResult)
	success, err := handler.(user.UserService).DeleteFriend(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceDeleteFriendArgs() interface{} {
	return user.NewUserServiceDeleteFriendArgs()
}

func newUserServiceDeleteFriendResult() interface{} {
	return user.NewUserServiceDeleteFriendResult()
}

func getFriendListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetFriendListArgs)
	realResult := result.(*user.UserServiceGetFriendListResult)
	success, err := handler.(user.UserService).GetFriendList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetFriendListArgs() interface{} {
	return user.NewUserServiceGetFriendListArgs()
}

func newUserServiceGetFriendListResult() interface{} {
	return user.NewUserServiceGetFriendListResult()
}

func updateFriendRemarkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateFriendRemarkArgs)
	realResult := result.(*user.UserServiceUpdateFriendRemarkResult)
	success, err := handler.(user.UserService).UpdateFriendRemark(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateFriendRemarkArgs() interface{} {
	return user.NewUserServiceUpdateFriendRemarkArgs()
}

func newUserServiceUpdateFriendRemarkResult() interface{} {
	return user.NewUserServiceUpdateFriendRemarkResult()
}

func createFriendGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCreateFriendGroupArgs)
	realResult := result.(*user.UserServiceCreateFriendGroupResult)
	success, err := handler.(user.UserService).CreateFriendGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCreateFriendGroupArgs() interface{} {
	return user.NewUserServiceCreateFriendGroupArgs()
}

func newUserServiceCreateFriendGroupResult() interface{} {
	return user.NewUserServiceCreateFriendGroupResult()
}

func moveFriendGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceMoveFriendGroupArgs)
	realResult := result.(*user.UserServiceMoveFriendGroupResult)
	success, err := handler.(user.UserService).MoveFriendGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceMoveFriendGroupArgs() interface{} {
	return user.NewUserServiceMoveFriendGroupArgs()
}

func newUserServiceMoveFriendGroupResult() interface{} {
	return user.NewUserServiceMoveFriendGroupResult()
}

func getFriendGroupsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetFriendGroupsArgs)
	realResult := result.(*user.UserServiceGetFriendGroupsResult)
	success, err := handler.(user.UserService).GetFriendGroups(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetFriendGroupsArgs() interface{} {
	return user.NewUserServiceGetFriendGroupsArgs()
}

func newUserServiceGetFriendGroupsResult() interface{} {
	return user.NewUserServiceGetFriendGroupsResult()
}

func batchGetUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceBatchGetUserInfoArgs)
	realResult := result.(*user.UserServiceBatchGetUserInfoResult)
	success, err := handler.(user.UserService).BatchGetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceBatchGetUserInfoArgs() interface{} {
	return user.NewUserServiceBatchGetUserInfoArgs()
}

func newUserServiceBatchGetUserInfoResult() interface{} {
	return user.NewUserServiceBatchGetUserInfoResult()
}

func adminListUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceAdminListUsersArgs)
	realResult := result.(*user.UserServiceAdminListUsersResult)
	success, err := handler.(user.UserService).AdminListUsers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceAdminListUsersArgs() interface{} {
	return user.NewUserServiceAdminListUsersArgs()
}

func newUserServiceAdminListUsersResult() interface{} {
	return user.NewUserServiceAdminListUsersResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *user.RegisterReq) (r *user.RegisterResp, err error) {
	var _args user.UserServiceRegisterArgs
	_args.Req = req
	var _result user.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *user.LoginReq) (r *user.LoginResp, err error) {
	var _args user.UserServiceLoginArgs
	_args.Req = req
	var _result user.UserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfo(ctx context.Context, req *user.GetUserInfoReq) (r *user.GetUserInfoResp, err error) {
	var _args user.UserServiceGetUserInfoArgs
	_args.Req = req
	var _result user.UserServiceGetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserInfo(ctx context.Context, req *user.UpdateUserInfoReq) (r *user.UpdateUserInfoResp, err error) {
	var _args user.UserServiceUpdateUserInfoArgs
	_args.Req = req
	var _result user.UserServiceUpdateUserInfoResult
	if err = p.c.Call(ctx, "UpdateUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateAvatar(ctx context.Context, req *user.UpdateAvatarReq) (r *user.UpdateAvatarResp, err error) {
	var _args user.UserServiceUpdateAvatarArgs
	_args.Req = req
	var _result user.UserServiceUpdateAvatarResult
	if err = p.c.Call(ctx, "UpdateAvatar", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateStatus(ctx context.Context, req *user.UpdateStatusReq) (r *user.UpdateStatusResp, err error) {
	var _args user.UserServiceUpdateStatusArgs
	_args.Req = req
	var _result user.UserServiceUpdateStatusResult
	if err = p.c.Call(ctx, "UpdateStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddFriend(ctx context.Context, req *user.AddFriendReq) (r *user.AddFriendResp, err error) {
	var _args user.UserServiceAddFriendArgs
	_args.Req = req
	var _result user.UserServiceAddFriendResult
	if err = p.c.Call(ctx, "AddFriend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteFriend(ctx context.Context, req *user.DeleteFriendReq) (r *user.DeleteFriendResp, err error) {
	var _args user.UserServiceDeleteFriendArgs
	_args.Req = req
	var _result user.UserServiceDeleteFriendResult
	if err = p.c.Call(ctx, "DeleteFriend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFriendList(ctx context.Context, req *user.GetFriendListReq) (r *user.GetFriendListResp, err error) {
	var _args user.UserServiceGetFriendListArgs
	_args.Req = req
	var _result user.UserServiceGetFriendListResult
	if err = p.c.Call(ctx, "GetFriendList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateFriendRemark(ctx context.Context, req *user.UpdateFriendRemarkReq) (r *user.UpdateFriendRemarkResp, err error) {
	var _args user.UserServiceUpdateFriendRemarkArgs
	_args.Req = req
	var _result user.UserServiceUpdateFriendRemarkResult
	if err = p.c.Call(ctx, "UpdateFriendRemark", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateFriendGroup(ctx context.Context, req *user.CreateFriendGroupReq) (r *user.CreateFriendGroupResp, err error) {
	var _args user.UserServiceCreateFriendGroupArgs
	_args.Req = req
	var _result user.UserServiceCreateFriendGroupResult
	if err = p.c.Call(ctx, "CreateFriendGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MoveFriendGroup(ctx context.Context, req *user.MoveFriendGroupReq) (r *user.MoveFriendGroupResp, err error) {
	var _args user.UserServiceMoveFriendGroupArgs
	_args.Req = req
	var _result user.UserServiceMoveFriendGroupResult
	if err = p.c.Call(ctx, "MoveFriendGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFriendGroups(ctx context.Context, req *user.GetFriendGroupsReq) (r *user.GetFriendGroupsResp, err error) {
	var _args user.UserServiceGetFriendGroupsArgs
	_args.Req = req
	var _result user.UserServiceGetFriendGroupsResult
	if err = p.c.Call(ctx, "GetFriendGroups", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGetUserInfo(ctx context.Context, req *user.BatchGetUserInfoReq) (r *user.BatchGetUserInfoResp, err error) {
	var _args user.UserServiceBatchGetUserInfoArgs
	_args.Req = req
	var _result user.UserServiceBatchGetUserInfoResult
	if err = p.c.Call(ctx, "BatchGetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AdminListUsers(ctx context.Context, req *user.AdminListUsersReq) (r *user.AdminListUsersResp, err error) {
	var _args user.UserServiceAdminListUsersArgs
	_args.Req = req
	var _result user.UserServiceAdminListUsersResult
	if err = p.c.Call(ctx, "AdminListUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
