// Code generated by Kitex v0.16.2. DO NOT EDIT.

package groupservice

import (
	group "ClaranAIM/kitex_gen/group"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateGroup": kitex.NewMethodInfo(
		createGroupHandler,
		newGroupServiceCreateGroupArgs,
		newGroupServiceCreateGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteGroup": kitex.NewMethodInfo(
		deleteGroupHandler,
		newGroupServiceDeleteGroupArgs,
		newGroupServiceDeleteGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateGroup": kitex.NewMethodInfo(
		updateGroupHandler,
		newGroupServiceUpdateGroupArgs,
		newGroupServiceUpdateGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetGroup": kitex.NewMethodInfo(
		getGroupHandler,
		newGroupServiceGetGroupArgs,
		newGroupServiceGetGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserGroups": kitex.NewMethodInfo(
		getUserGroupsHandler,
		newGroupServiceGetUserGroupsArgs,
		newGroupServiceGetUserGroupsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"InviteMember": kitex.NewMethodInfo(
		inviteMemberHandler,
		newGroupServiceInviteMemberArgs,
		newGroupServiceInviteMemberResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"KickMember": kitex.NewMethodInfo(
		kickMemberHandler,
		newGroupServiceKickMemberArgs,
		newGroupServiceKickMemberResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MuteMember": kitex.NewMethodInfo(
		muteMemberHandler,
		newGroupServiceMuteMemberArgs,
		newGroupServiceMuteMemberResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetRole": kitex.NewMethodInfo(
		setRoleHandler,
		newGroupServiceSetRoleArgs,
		newGroupServiceSetRoleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetGroupMembers": kitex.NewMethodInfo(
		getGroupMembersHandler,
		newGroupServiceGetGroupMembersArgs,
		newGroupServiceGetGroupMembersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CheckMember": kitex.NewMethodInfo(
		checkMemberHandler,
		newGroupServiceCheckMemberArgs,
		newGroupServiceCheckMemberResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"TransferOwner": kitex.NewMethodInfo(
		transferOwnerHandler,
		newGroupServiceTransferOwnerArgs,
		newGroupServiceTransferOwnerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	groupServiceServiceInfo                = NewServiceInfo()
	groupServiceServiceInfoForClient       = NewServiceInfoForClient()
	groupServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return groupServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return groupServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return groupServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "GroupService"
	handlerType := (*group.GroupService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "group",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func createGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceCreateGroupArgs)
	realResult := result.(*group.GroupServiceCreateGroupResult)
	success, err := handler.(group.GroupService).CreateGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceCreateGroupArgs() interface{} {
	return group.NewGroupServiceCreateGroupArgs()
}

func newGroupServiceCreateGroupResult() interface{} {
	return group.NewGroupServiceCreateGroupResult()
}

func deleteGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceDeleteGroupArgs)
	realResult := result.(*group.GroupServiceDeleteGroupResult)
	success, err := handler.(group.GroupService).DeleteGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceDeleteGroupArgs() interface{} {
	return group.NewGroupServiceDeleteGroupArgs()
}

func newGroupServiceDeleteGroupResult() interface{} {
	return group.NewGroupServiceDeleteGroupResult()
}

func updateGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceUpdateGroupArgs)
	realResult := result.(*group.GroupServiceUpdateGroupResult)
	success, err := handler.(group.GroupService).UpdateGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceUpdateGroupArgs() interface{} {
	return group.NewGroupServiceUpdateGroupArgs()
}

func newGroupServiceUpdateGroupResult() interface{} {
	return group.NewGroupServiceUpdateGroupResult()
}

func getGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceGetGroupArgs)
	realResult := result.(*group.GroupServiceGetGroupResult)
	success, err := handler.(group.GroupService).GetGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceGetGroupArgs() interface{} {
	return group.NewGroupServiceGetGroupArgs()
}

func newGroupServiceGetGroupResult() interface{} {
	return group.NewGroupServiceGetGroupResult()
}

func getUserGroupsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceGetUserGroupsArgs)
	realResult := result.(*group.GroupServiceGetUserGroupsResult)
	success, err := handler.(group.GroupService).GetUserGroups(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceGetUserGroupsArgs() interface{} {
	return group.NewGroupServiceGetUserGroupsArgs()
}

func newGroupServiceGetUserGroupsResult() interface{} {
	return group.NewGroupServiceGetUserGroupsResult()
}

func inviteMemberHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceInviteMemberArgs)
	realResult := result.(*group.GroupServiceInviteMemberResult)
	success, err := handler.(group.GroupService).InviteMember(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceInviteMemberArgs() interface{} {
	return group.NewGroupServiceInviteMemberArgs()
}

func newGroupServiceInviteMemberResult() interface{} {
	return group.NewGroupServiceInviteMemberResult()
}

func kickMemberHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceKickMemberArgs)
	realResult := result.(*group.GroupServiceKickMemberResult)
	success, err := handler.(group.GroupService).KickMember(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceKickMemberArgs() interface{} {
	return group.NewGroupServiceKickMemberArgs()
}

func newGroupServiceKickMemberResult() interface{} {
	return group.NewGroupServiceKickMemberResult()
}

func muteMemberHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceMuteMemberArgs)
	realResult := result.(*group.GroupServiceMuteMemberResult)
	success, err := handler.(group.GroupService).MuteMember(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceMuteMemberArgs() interface{} {
	return group.NewGroupServiceMuteMemberArgs()
}

func newGroupServiceMuteMemberResult() interface{} {
	return group.NewGroupServiceMuteMemberResult()
}

func setRoleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceSetRoleArgs)
	realResult := result.(*group.GroupServiceSetRoleResult)
	success, err := handler.(group.GroupService).SetRole(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceSetRoleArgs() interface{} {
	return group.NewGroupServiceSetRoleArgs()
}

func newGroupServiceSetRoleResult() interface{} {
	return group.NewGroupServiceSetRoleResult()
}

func getGroupMembersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceGetGroupMembersArgs)
	realResult := result.(*group.GroupServiceGetGroupMembersResult)
	success, err := handler.(group.GroupService).GetGroupMembers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceGetGroupMembersArgs() interface{} {
	return group.NewGroupServiceGetGroupMembersArgs()
}

func newGroupServiceGetGroupMembersResult() interface{} {
	return group.NewGroupServiceGetGroupMembersResult()
}

func checkMemberHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceCheckMemberArgs)
	realResult := result.(*group.GroupServiceCheckMemberResult)
	success, err := handler.(group.GroupService).CheckMember(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceCheckMemberArgs() interface{} {
	return group.NewGroupServiceCheckMemberArgs()
}

func newGroupServiceCheckMemberResult() interface{} {
	return group.NewGroupServiceCheckMemberResult()
}

func transferOwnerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceTransferOwnerArgs)
	realResult := result.(*group.GroupServiceTransferOwnerResult)
	success, err := handler.(group.GroupService).TransferOwner(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceTransferOwnerArgs() interface{} {
	return group.NewGroupServiceTransferOwnerArgs()
}

func newGroupServiceTransferOwnerResult() interface{} {
	return group.NewGroupServiceTransferOwnerResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateGroup(ctx context.Context, req *group.CreateGroupReq) (r *group.CreateGroupResp, err error) {
	var _args group.GroupServiceCreateGroupArgs
	_args.Req = req
	var _result group.GroupServiceCreateGroupResult
	if err = p.c.Call(ctx, "CreateGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteGroup(ctx context.Context, req *group.DeleteGroupReq) (r *group.DeleteGroupResp, err error) {
	var _args group.GroupServiceDeleteGroupArgs
	_args.Req = req
	var _result group.GroupServiceDeleteGroupResult
	if err = p.c.Call(ctx, "DeleteGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateGroup(ctx context.Context, req *group.UpdateGroupReq) (r *group.UpdateGroupResp, err error) {
	var _args group.GroupServiceUpdateGroupArgs
	_args.Req = req
	var _result group.GroupServiceUpdateGroupResult
	if err = p.c.Call(ctx, "UpdateGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetGroup(ctx context.Context, req *group.GetGroupReq) (r *group.GetGroupResp, err error) {
	var _args group.GroupServiceGetGroupArgs
	_args.Req = req
	var _result group.GroupServiceGetGroupResult
	if err = p.c.Call(ctx, "GetGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserGroups(ctx context.Context, req *group.GetUserGroupsReq) (r *group.GetUserGroupsResp, err error) {
	var _args group.GroupServiceGetUserGroupsArgs
	_args.Req = req
	var _result group.GroupServiceGetUserGroupsResult
	if err = p.c.Call(ctx, "GetUserGroups", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InviteMember(ctx context.Context, req *group.InviteMemberReq) (r *group.InviteMemberResp, err error) {
	var _args group.GroupServiceInviteMemberArgs
	_args.Req = req
	var _result group.GroupServiceInviteMemberResult
	if err = p.c.Call(ctx, "InviteMember", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) KickMember(ctx context.Context, req *group.KickMemberReq) (r *group.KickMemberResp, err error) {
	var _args group.GroupServiceKickMemberArgs
	_args.Req = req
	var _result group.GroupServiceKickMemberResult
	if err = p.c.Call(ctx, "KickMember", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MuteMember(ctx context.Context, req *group.MuteMemberReq) (r *group.MuteMemberResp, err error) {
	var _args group.GroupServiceMuteMemberArgs
	_args.Req = req
	var _result group.GroupServiceMuteMemberResult
	if err = p.c.Call(ctx, "MuteMember", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetRole(ctx context.Context, req *group.SetRoleReq) (r *group.SetRoleResp, err error) {
	var _args group.GroupServiceSetRoleArgs
	_args.Req = req
	var _result group.GroupServiceSetRoleResult
	if err = p.c.Call(ctx, "SetRole", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetGroupMembers(ctx context.Context, req *group.GetGroupMembersReq) (r *group.GetGroupMembersResp, err error) {
	var _args group.GroupServiceGetGroupMembersArgs
	_args.Req = req
	var _result group.GroupServiceGetGroupMembersResult
	if err = p.c.Call(ctx, "GetGroupMembers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckMember(ctx context.Context, req *group.CheckMemberReq) (r *group.CheckMemberResp, err error) {
	var _args group.GroupServiceCheckMemberArgs
	_args.Req = req
	var _result group.GroupServiceCheckMemberResult
	if err = p.c.Call(ctx, "CheckMember", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TransferOwner(ctx context.Context, req *group.TransferOwnerReq) (r *group.TransferOwnerResp, err error) {
	var _args group.GroupServiceTransferOwnerArgs
	_args.Req = req
	var _result group.GroupServiceTransferOwnerResult
	if err = p.c.Call(ctx, "TransferOwner", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
