// Code generated by Kitex v0.16.2. DO NOT EDIT.

package fileservice

import (
	file "ClaranAIM/kitex_gen/file"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UploadFile(ctx context.Context, req *file.UploadFileReq, callOptions ...callopt.Option) (r *file.UploadFileResp, err error)
	GetFile(ctx context.Context, req *file.GetFileReq, callOptions ...callopt.Option) (r *file.GetFileResp, err error)
	DeleteFile(ctx context.Context, req *file.DeleteFileReq, callOptions ...callopt.Option) (r *file.DeleteFileResp, err error)
	ListFiles(ctx context.Context, req *file.ListFilesReq, callOptions ...callopt.Option) (r *file.ListFilesResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kFileServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFileServiceClient struct {
	*kClient
}

func (p *kFileServiceClient) UploadFile(ctx context.Context, req *file.UploadFileReq, callOptions ...callopt.Option) (r *file.UploadFileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadFile(ctx, req)
}

func (p *kFileServiceClient) GetFile(ctx context.Context, req *file.GetFileReq, callOptions ...callopt.Option) (r *file.GetFileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFile(ctx, req)
}

func (p *kFileServiceClient) DeleteFile(ctx context.Context, req *file.DeleteFileReq, callOptions ...callopt.Option) (r *file.DeleteFileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteFile(ctx, req)
}

func (p *kFileServiceClient) ListFiles(ctx context.Context, req *file.ListFilesReq, callOptions ...callopt.Option) (r *file.ListFilesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFiles(ctx, req)
}
