// Code generated by Kitex v0.16.2. DO NOT EDIT.

package fileservice

import (
	file "ClaranAIM/kitex_gen/file"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"UploadFile": kitex.NewMethodInfo(
		uploadFileHandler,
		newFileServiceUploadFileArgs,
		newFileServiceUploadFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFile": kitex.NewMethodInfo(
		getFileHandler,
		newFileServiceGetFileArgs,
		newFileServiceGetFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteFile": kitex.NewMethodInfo(
		deleteFileHandler,
		newFileServiceDeleteFileArgs,
		newFileServiceDeleteFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListFiles": kitex.NewMethodInfo(
		listFilesHandler,
		newFileServiceListFilesArgs,
		newFileServiceListFilesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	fileServiceServiceInfo                = NewServiceInfo()
	fileServiceServiceInfoForClient       = NewServiceInfoForClient()
	fileServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return fileServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return fileServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return fileServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "FileService"
	handlerType := (*file.FileService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "file",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func uploadFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*file.FileServiceUploadFileArgs)
	realResult := result.(*file.FileServiceUploadFileResult)
	success, err := handler.(file.FileService).UploadFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFileServiceUploadFileArgs() interface{} {
	return file.NewFileServiceUploadFileArgs()
}

func newFileServiceUploadFileResult() interface{} {
	return file.NewFileServiceUploadFileResult()
}

func getFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*file.FileServiceGetFileArgs)
	realResult := result.(*file.FileServiceGetFileResult)
	success, err := handler.(file.FileService).GetFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFileServiceGetFileArgs() interface{} {
	return file.NewFileServiceGetFileArgs()
}

func newFileServiceGetFileResult() interface{} {
	return file.NewFileServiceGetFileResult()
}

func deleteFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*file.FileServiceDeleteFileArgs)
	realResult := result.(*file.FileServiceDeleteFileResult)
	success, err := handler.(file.FileService).DeleteFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFileServiceDeleteFileArgs() interface{} {
	return file.NewFileServiceDeleteFileArgs()
}

func newFileServiceDeleteFileResult() interface{} {
	return file.NewFileServiceDeleteFileResult()
}

func listFilesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*file.FileServiceListFilesArgs)
	realResult := result.(*file.FileServiceListFilesResult)
	success, err := handler.(file.FileService).ListFiles(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFileServiceListFilesArgs() interface{} {
	return file.NewFileServiceListFilesArgs()
}

func newFileServiceListFilesResult() interface{} {
	return file.NewFileServiceListFilesResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UploadFile(ctx context.Context, req *file.UploadFileReq) (r *file.UploadFileResp, err error) {
	var _args file.FileServiceUploadFileArgs
	_args.Req = req
	var _result file.FileServiceUploadFileResult
	if err = p.c.Call(ctx, "UploadFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFile(ctx context.Context, req *file.GetFileReq) (r *file.GetFileResp, err error) {
	var _args file.FileServiceGetFileArgs
	_args.Req = req
	var _result file.FileServiceGetFileResult
	if err = p.c.Call(ctx, "GetFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteFile(ctx context.Context, req *file.DeleteFileReq) (r *file.DeleteFileResp, err error) {
	var _args file.FileServiceDeleteFileArgs
	_args.Req = req
	var _result file.FileServiceDeleteFileResult
	if err = p.c.Call(ctx, "DeleteFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListFiles(ctx context.Context, req *file.ListFilesReq) (r *file.ListFilesResp, err error) {
	var _args file.FileServiceListFilesArgs
	_args.Req = req
	var _result file.FileServiceListFilesResult
	if err = p.c.Call(ctx, "ListFiles", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
