// Code generated by Kitex v0.16.2. DO NOT EDIT.

package knowledgeservice

import (
	knowledge "ClaranAIM/kitex_gen/knowledge"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetGraphView(ctx context.Context, req *knowledge.KnowledgeGraphReq, callOptions ...callopt.Option) (r *knowledge.KnowledgeGraphResp, err error)
	GetNodeDetail(ctx context.Context, req *knowledge.KnowledgeNodeDetailReq, callOptions ...callopt.Option) (r *knowledge.KnowledgeNodeDetailResp, err error)
	GetEdgeDetail(ctx context.Context, req *knowledge.KnowledgeEdgeDetailReq, callOptions ...callopt.Option) (r *knowledge.KnowledgeEdgeDetailResp, err error)
	GetNeighborhood(ctx context.Context, req *knowledge.KnowledgeNeighborhoodReq, callOptions ...callopt.Option) (r *knowledge.KnowledgeGraphResp, err error)
	GetPath(ctx context.Context, req *knowledge.KnowledgePathReq, callOptions ...callopt.Option) (r *knowledge.KnowledgePathResp, err error)
	CreateGraphReviewCandidate(ctx context.Context, req *knowledge.CreateGraphReviewCandidateReq, callOptions ...callopt.Option) (r *knowledge.GraphReviewCandidateResp, err error)
	ListGraphReviewCandidates(ctx context.Context, req *knowledge.ListGraphReviewCandidatesReq, callOptions ...callopt.Option) (r *knowledge.ListGraphReviewCandidatesResp, err error)
	ReviewGraphCandidate(ctx context.Context, req *knowledge.ReviewGraphCandidateReq, callOptions ...callopt.Option) (r *knowledge.GraphReviewCandidateResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kKnowledgeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kKnowledgeServiceClient struct {
	*kClient
}

func (p *kKnowledgeServiceClient) GetGraphView(ctx context.Context, req *knowledge.KnowledgeGraphReq, callOptions ...callopt.Option) (r *knowledge.KnowledgeGraphResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetGraphView(ctx, req)
}

func (p *kKnowledgeServiceClient) GetNodeDetail(ctx context.Context, req *knowledge.KnowledgeNodeDetailReq, callOptions ...callopt.Option) (r *knowledge.KnowledgeNodeDetailResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetNodeDetail(ctx, req)
}

func (p *kKnowledgeServiceClient) GetEdgeDetail(ctx context.Context, req *knowledge.KnowledgeEdgeDetailReq, callOptions ...callopt.Option) (r *knowledge.KnowledgeEdgeDetailResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetEdgeDetail(ctx, req)
}

func (p *kKnowledgeServiceClient) GetNeighborhood(ctx context.Context, req *knowledge.KnowledgeNeighborhoodReq, callOptions ...callopt.Option) (r *knowledge.KnowledgeGraphResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetNeighborhood(ctx, req)
}

func (p *kKnowledgeServiceClient) GetPath(ctx context.Context, req *knowledge.KnowledgePathReq, callOptions ...callopt.Option) (r *knowledge.KnowledgePathResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPath(ctx, req)
}

func (p *kKnowledgeServiceClient) CreateGraphReviewCandidate(ctx context.Context, req *knowledge.CreateGraphReviewCandidateReq, callOptions ...callopt.Option) (r *knowledge.GraphReviewCandidateResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateGraphReviewCandidate(ctx, req)
}

func (p *kKnowledgeServiceClient) ListGraphReviewCandidates(ctx context.Context, req *knowledge.ListGraphReviewCandidatesReq, callOptions ...callopt.Option) (r *knowledge.ListGraphReviewCandidatesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListGraphReviewCandidates(ctx, req)
}

func (p *kKnowledgeServiceClient) ReviewGraphCandidate(ctx context.Context, req *knowledge.ReviewGraphCandidateReq, callOptions ...callopt.Option) (r *knowledge.GraphReviewCandidateResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReviewGraphCandidate(ctx, req)
}
