// Code generated by Kitex v0.16.2. DO NOT EDIT.

package knowledgeservice

import (
	knowledge "ClaranAIM/kitex_gen/knowledge"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetGraphView": kitex.NewMethodInfo(
		getGraphViewHandler,
		newKnowledgeServiceGetGraphViewArgs,
		newKnowledgeServiceGetGraphViewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetNodeDetail": kitex.NewMethodInfo(
		getNodeDetailHandler,
		newKnowledgeServiceGetNodeDetailArgs,
		newKnowledgeServiceGetNodeDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetEdgeDetail": kitex.NewMethodInfo(
		getEdgeDetailHandler,
		newKnowledgeServiceGetEdgeDetailArgs,
		newKnowledgeServiceGetEdgeDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetNeighborhood": kitex.NewMethodInfo(
		getNeighborhoodHandler,
		newKnowledgeServiceGetNeighborhoodArgs,
		newKnowledgeServiceGetNeighborhoodResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPath": kitex.NewMethodInfo(
		getPathHandler,
		newKnowledgeServiceGetPathArgs,
		newKnowledgeServiceGetPathResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateGraphReviewCandidate": kitex.NewMethodInfo(
		createGraphReviewCandidateHandler,
		newKnowledgeServiceCreateGraphReviewCandidateArgs,
		newKnowledgeServiceCreateGraphReviewCandidateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListGraphReviewCandidates": kitex.NewMethodInfo(
		listGraphReviewCandidatesHandler,
		newKnowledgeServiceListGraphReviewCandidatesArgs,
		newKnowledgeServiceListGraphReviewCandidatesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReviewGraphCandidate": kitex.NewMethodInfo(
		reviewGraphCandidateHandler,
		newKnowledgeServiceReviewGraphCandidateArgs,
		newKnowledgeServiceReviewGraphCandidateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	knowledgeServiceServiceInfo                = NewServiceInfo()
	knowledgeServiceServiceInfoForClient       = NewServiceInfoForClient()
	knowledgeServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return knowledgeServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return knowledgeServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return knowledgeServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "KnowledgeService"
	handlerType := (*knowledge.KnowledgeService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "knowledge",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func getGraphViewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledge.KnowledgeServiceGetGraphViewArgs)
	realResult := result.(*knowledge.KnowledgeServiceGetGraphViewResult)
	success, err := handler.(knowledge.KnowledgeService).GetGraphView(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceGetGraphViewArgs() interface{} {
	return knowledge.NewKnowledgeServiceGetGraphViewArgs()
}

func newKnowledgeServiceGetGraphViewResult() interface{} {
	return knowledge.NewKnowledgeServiceGetGraphViewResult()
}

func getNodeDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledge.KnowledgeServiceGetNodeDetailArgs)
	realResult := result.(*knowledge.KnowledgeServiceGetNodeDetailResult)
	success, err := handler.(knowledge.KnowledgeService).GetNodeDetail(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceGetNodeDetailArgs() interface{} {
	return knowledge.NewKnowledgeServiceGetNodeDetailArgs()
}

func newKnowledgeServiceGetNodeDetailResult() interface{} {
	return knowledge.NewKnowledgeServiceGetNodeDetailResult()
}

func getEdgeDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledge.KnowledgeServiceGetEdgeDetailArgs)
	realResult := result.(*knowledge.KnowledgeServiceGetEdgeDetailResult)
	success, err := handler.(knowledge.KnowledgeService).GetEdgeDetail(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceGetEdgeDetailArgs() interface{} {
	return knowledge.NewKnowledgeServiceGetEdgeDetailArgs()
}

func newKnowledgeServiceGetEdgeDetailResult() interface{} {
	return knowledge.NewKnowledgeServiceGetEdgeDetailResult()
}

func getNeighborhoodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledge.KnowledgeServiceGetNeighborhoodArgs)
	realResult := result.(*knowledge.KnowledgeServiceGetNeighborhoodResult)
	success, err := handler.(knowledge.KnowledgeService).GetNeighborhood(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceGetNeighborhoodArgs() interface{} {
	return knowledge.NewKnowledgeServiceGetNeighborhoodArgs()
}

func newKnowledgeServiceGetNeighborhoodResult() interface{} {
	return knowledge.NewKnowledgeServiceGetNeighborhoodResult()
}

func getPathHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledge.KnowledgeServiceGetPathArgs)
	realResult := result.(*knowledge.KnowledgeServiceGetPathResult)
	success, err := handler.(knowledge.KnowledgeService).GetPath(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceGetPathArgs() interface{} {
	return knowledge.NewKnowledgeServiceGetPathArgs()
}

func newKnowledgeServiceGetPathResult() interface{} {
	return knowledge.NewKnowledgeServiceGetPathResult()
}

func createGraphReviewCandidateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledge.KnowledgeServiceCreateGraphReviewCandidateArgs)
	realResult := result.(*knowledge.KnowledgeServiceCreateGraphReviewCandidateResult)
	success, err := handler.(knowledge.KnowledgeService).CreateGraphReviewCandidate(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceCreateGraphReviewCandidateArgs() interface{} {
	return knowledge.NewKnowledgeServiceCreateGraphReviewCandidateArgs()
}

func newKnowledgeServiceCreateGraphReviewCandidateResult() interface{} {
	return knowledge.NewKnowledgeServiceCreateGraphReviewCandidateResult()
}

func listGraphReviewCandidatesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledge.KnowledgeServiceListGraphReviewCandidatesArgs)
	realResult := result.(*knowledge.KnowledgeServiceListGraphReviewCandidatesResult)
	success, err := handler.(knowledge.KnowledgeService).ListGraphReviewCandidates(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceListGraphReviewCandidatesArgs() interface{} {
	return knowledge.NewKnowledgeServiceListGraphReviewCandidatesArgs()
}

func newKnowledgeServiceListGraphReviewCandidatesResult() interface{} {
	return knowledge.NewKnowledgeServiceListGraphReviewCandidatesResult()
}

func reviewGraphCandidateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledge.KnowledgeServiceReviewGraphCandidateArgs)
	realResult := result.(*knowledge.KnowledgeServiceReviewGraphCandidateResult)
	success, err := handler.(knowledge.KnowledgeService).ReviewGraphCandidate(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceReviewGraphCandidateArgs() interface{} {
	return knowledge.NewKnowledgeServiceReviewGraphCandidateArgs()
}

func newKnowledgeServiceReviewGraphCandidateResult() interface{} {
	return knowledge.NewKnowledgeServiceReviewGraphCandidateResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetGraphView(ctx context.Context, req *knowledge.KnowledgeGraphReq) (r *knowledge.KnowledgeGraphResp, err error) {
	var _args knowledge.KnowledgeServiceGetGraphViewArgs
	_args.Req = req
	var _result knowledge.KnowledgeServiceGetGraphViewResult
	if err = p.c.Call(ctx, "GetGraphView", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetNodeDetail(ctx context.Context, req *knowledge.KnowledgeNodeDetailReq) (r *knowledge.KnowledgeNodeDetailResp, err error) {
	var _args knowledge.KnowledgeServiceGetNodeDetailArgs
	_args.Req = req
	var _result knowledge.KnowledgeServiceGetNodeDetailResult
	if err = p.c.Call(ctx, "GetNodeDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetEdgeDetail(ctx context.Context, req *knowledge.KnowledgeEdgeDetailReq) (r *knowledge.KnowledgeEdgeDetailResp, err error) {
	var _args knowledge.KnowledgeServiceGetEdgeDetailArgs
	_args.Req = req
	var _result knowledge.KnowledgeServiceGetEdgeDetailResult
	if err = p.c.Call(ctx, "GetEdgeDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetNeighborhood(ctx context.Context, req *knowledge.KnowledgeNeighborhoodReq) (r *knowledge.KnowledgeGraphResp, err error) {
	var _args knowledge.KnowledgeServiceGetNeighborhoodArgs
	_args.Req = req
	var _result knowledge.KnowledgeServiceGetNeighborhoodResult
	if err = p.c.Call(ctx, "GetNeighborhood", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPath(ctx context.Context, req *knowledge.KnowledgePathReq) (r *knowledge.KnowledgePathResp, err error) {
	var _args knowledge.KnowledgeServiceGetPathArgs
	_args.Req = req
	var _result knowledge.KnowledgeServiceGetPathResult
	if err = p.c.Call(ctx, "GetPath", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateGraphReviewCandidate(ctx context.Context, req *knowledge.CreateGraphReviewCandidateReq) (r *knowledge.GraphReviewCandidateResp, err error) {
	var _args knowledge.KnowledgeServiceCreateGraphReviewCandidateArgs
	_args.Req = req
	var _result knowledge.KnowledgeServiceCreateGraphReviewCandidateResult
	if err = p.c.Call(ctx, "CreateGraphReviewCandidate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListGraphReviewCandidates(ctx context.Context, req *knowledge.ListGraphReviewCandidatesReq) (r *knowledge.ListGraphReviewCandidatesResp, err error) {
	var _args knowledge.KnowledgeServiceListGraphReviewCandidatesArgs
	_args.Req = req
	var _result knowledge.KnowledgeServiceListGraphReviewCandidatesResult
	if err = p.c.Call(ctx, "ListGraphReviewCandidates", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReviewGraphCandidate(ctx context.Context, req *knowledge.ReviewGraphCandidateReq) (r *knowledge.GraphReviewCandidateResp, err error) {
	var _args knowledge.KnowledgeServiceReviewGraphCandidateArgs
	_args.Req = req
	var _result knowledge.KnowledgeServiceReviewGraphCandidateResult
	if err = p.c.Call(ctx, "ReviewGraphCandidate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
