// Code generated by Kitex v0.12.3. DO NOT EDIT.

package settingsservice

import (
	settings "ClaranAIM/kitex_gen/settings"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SaveLLMProfile": kitex.NewMethodInfo(
		saveLLMProfileHandler,
		newSettingsServiceSaveLLMProfileArgs,
		newSettingsServiceSaveLLMProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListLLMProfiles": kitex.NewMethodInfo(
		listLLMProfilesHandler,
		newSettingsServiceListLLMProfilesArgs,
		newSettingsServiceListLLMProfilesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteLLMProfile": kitex.NewMethodInfo(
		deleteLLMProfileHandler,
		newSettingsServiceDeleteLLMProfileArgs,
		newSettingsServiceDeleteLLMProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SavePrompt": kitex.NewMethodInfo(
		savePromptHandler,
		newSettingsServiceSavePromptArgs,
		newSettingsServiceSavePromptResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListPrompts": kitex.NewMethodInfo(
		listPromptsHandler,
		newSettingsServiceListPromptsArgs,
		newSettingsServiceListPromptsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ResolveTranslationConfig": kitex.NewMethodInfo(
		resolveTranslationConfigHandler,
		newSettingsServiceResolveTranslationConfigArgs,
		newSettingsServiceResolveTranslationConfigResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ResolveLLMProfile": kitex.NewMethodInfo(
		resolveLLMProfileHandler,
		newSettingsServiceResolveLLMProfileArgs,
		newSettingsServiceResolveLLMProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SaveSkill": kitex.NewMethodInfo(
		saveSkillHandler,
		newSettingsServiceSaveSkillArgs,
		newSettingsServiceSaveSkillResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListSkills": kitex.NewMethodInfo(
		listSkillsHandler,
		newSettingsServiceListSkillsArgs,
		newSettingsServiceListSkillsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetSkill": kitex.NewMethodInfo(
		getSkillHandler,
		newSettingsServiceGetSkillArgs,
		newSettingsServiceGetSkillResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateSkillContent": kitex.NewMethodInfo(
		updateSkillContentHandler,
		newSettingsServiceUpdateSkillContentArgs,
		newSettingsServiceUpdateSkillContentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteSkill": kitex.NewMethodInfo(
		deleteSkillHandler,
		newSettingsServiceDeleteSkillArgs,
		newSettingsServiceDeleteSkillResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	settingsServiceServiceInfo                = NewServiceInfo()
	settingsServiceServiceInfoForClient       = NewServiceInfoForClient()
	settingsServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return settingsServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return settingsServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return settingsServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "SettingsService"
	handlerType := (*settings.SettingsService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "settings",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func saveLLMProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*settings.SettingsServiceSaveLLMProfileArgs)
	realResult := result.(*settings.SettingsServiceSaveLLMProfileResult)
	success, err := handler.(settings.SettingsService).SaveLLMProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSettingsServiceSaveLLMProfileArgs() interface{} {
	return settings.NewSettingsServiceSaveLLMProfileArgs()
}

func newSettingsServiceSaveLLMProfileResult() interface{} {
	return settings.NewSettingsServiceSaveLLMProfileResult()
}

func listLLMProfilesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*settings.SettingsServiceListLLMProfilesArgs)
	realResult := result.(*settings.SettingsServiceListLLMProfilesResult)
	success, err := handler.(settings.SettingsService).ListLLMProfiles(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSettingsServiceListLLMProfilesArgs() interface{} {
	return settings.NewSettingsServiceListLLMProfilesArgs()
}

func newSettingsServiceListLLMProfilesResult() interface{} {
	return settings.NewSettingsServiceListLLMProfilesResult()
}

func deleteLLMProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*settings.SettingsServiceDeleteLLMProfileArgs)
	realResult := result.(*settings.SettingsServiceDeleteLLMProfileResult)
	success, err := handler.(settings.SettingsService).DeleteLLMProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSettingsServiceDeleteLLMProfileArgs() interface{} {
	return settings.NewSettingsServiceDeleteLLMProfileArgs()
}

func newSettingsServiceDeleteLLMProfileResult() interface{} {
	return settings.NewSettingsServiceDeleteLLMProfileResult()
}

func savePromptHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*settings.SettingsServiceSavePromptArgs)
	realResult := result.(*settings.SettingsServiceSavePromptResult)
	success, err := handler.(settings.SettingsService).SavePrompt(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSettingsServiceSavePromptArgs() interface{} {
	return settings.NewSettingsServiceSavePromptArgs()
}

func newSettingsServiceSavePromptResult() interface{} {
	return settings.NewSettingsServiceSavePromptResult()
}

func listPromptsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*settings.SettingsServiceListPromptsArgs)
	realResult := result.(*settings.SettingsServiceListPromptsResult)
	success, err := handler.(settings.SettingsService).ListPrompts(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSettingsServiceListPromptsArgs() interface{} {
	return settings.NewSettingsServiceListPromptsArgs()
}

func newSettingsServiceListPromptsResult() interface{} {
	return settings.NewSettingsServiceListPromptsResult()
}

func resolveTranslationConfigHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*settings.SettingsServiceResolveTranslationConfigArgs)
	realResult := result.(*settings.SettingsServiceResolveTranslationConfigResult)
	success, err := handler.(settings.SettingsService).ResolveTranslationConfig(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSettingsServiceResolveTranslationConfigArgs() interface{} {
	return settings.NewSettingsServiceResolveTranslationConfigArgs()
}

func newSettingsServiceResolveTranslationConfigResult() interface{} {
	return settings.NewSettingsServiceResolveTranslationConfigResult()
}

func resolveLLMProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*settings.SettingsServiceResolveLLMProfileArgs)
	realResult := result.(*settings.SettingsServiceResolveLLMProfileResult)
	success, err := handler.(settings.SettingsService).ResolveLLMProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSettingsServiceResolveLLMProfileArgs() interface{} {
	return settings.NewSettingsServiceResolveLLMProfileArgs()
}

func newSettingsServiceResolveLLMProfileResult() interface{} {
	return settings.NewSettingsServiceResolveLLMProfileResult()
}

func saveSkillHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*settings.SettingsServiceSaveSkillArgs)
	realResult := result.(*settings.SettingsServiceSaveSkillResult)
	success, err := handler.(settings.SettingsService).SaveSkill(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSettingsServiceSaveSkillArgs() interface{} {
	return settings.NewSettingsServiceSaveSkillArgs()
}

func newSettingsServiceSaveSkillResult() interface{} {
	return settings.NewSettingsServiceSaveSkillResult()
}

func listSkillsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*settings.SettingsServiceListSkillsArgs)
	realResult := result.(*settings.SettingsServiceListSkillsResult)
	success, err := handler.(settings.SettingsService).ListSkills(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSettingsServiceListSkillsArgs() interface{} {
	return settings.NewSettingsServiceListSkillsArgs()
}

func newSettingsServiceListSkillsResult() interface{} {
	return settings.NewSettingsServiceListSkillsResult()
}

func getSkillHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*settings.SettingsServiceGetSkillArgs)
	realResult := result.(*settings.SettingsServiceGetSkillResult)
	success, err := handler.(settings.SettingsService).GetSkill(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSettingsServiceGetSkillArgs() interface{} {
	return settings.NewSettingsServiceGetSkillArgs()
}

func newSettingsServiceGetSkillResult() interface{} {
	return settings.NewSettingsServiceGetSkillResult()
}

func updateSkillContentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*settings.SettingsServiceUpdateSkillContentArgs)
	realResult := result.(*settings.SettingsServiceUpdateSkillContentResult)
	success, err := handler.(settings.SettingsService).UpdateSkillContent(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSettingsServiceUpdateSkillContentArgs() interface{} {
	return settings.NewSettingsServiceUpdateSkillContentArgs()
}

func newSettingsServiceUpdateSkillContentResult() interface{} {
	return settings.NewSettingsServiceUpdateSkillContentResult()
}

func deleteSkillHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*settings.SettingsServiceDeleteSkillArgs)
	realResult := result.(*settings.SettingsServiceDeleteSkillResult)
	success, err := handler.(settings.SettingsService).DeleteSkill(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSettingsServiceDeleteSkillArgs() interface{} {
	return settings.NewSettingsServiceDeleteSkillArgs()
}

func newSettingsServiceDeleteSkillResult() interface{} {
	return settings.NewSettingsServiceDeleteSkillResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SaveLLMProfile(ctx context.Context, req *settings.SaveLLMProfileReq) (r *settings.SaveLLMProfileResp, err error) {
	var _args settings.SettingsServiceSaveLLMProfileArgs
	_args.Req = req
	var _result settings.SettingsServiceSaveLLMProfileResult
	if err = p.c.Call(ctx, "SaveLLMProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListLLMProfiles(ctx context.Context, req *settings.ListLLMProfilesReq) (r *settings.ListLLMProfilesResp, err error) {
	var _args settings.SettingsServiceListLLMProfilesArgs
	_args.Req = req
	var _result settings.SettingsServiceListLLMProfilesResult
	if err = p.c.Call(ctx, "ListLLMProfiles", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteLLMProfile(ctx context.Context, req *settings.DeleteLLMProfileReq) (r *settings.DeleteLLMProfileResp, err error) {
	var _args settings.SettingsServiceDeleteLLMProfileArgs
	_args.Req = req
	var _result settings.SettingsServiceDeleteLLMProfileResult
	if err = p.c.Call(ctx, "DeleteLLMProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SavePrompt(ctx context.Context, req *settings.SavePromptReq) (r *settings.SavePromptResp, err error) {
	var _args settings.SettingsServiceSavePromptArgs
	_args.Req = req
	var _result settings.SettingsServiceSavePromptResult
	if err = p.c.Call(ctx, "SavePrompt", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListPrompts(ctx context.Context, req *settings.ListPromptsReq) (r *settings.ListPromptsResp, err error) {
	var _args settings.SettingsServiceListPromptsArgs
	_args.Req = req
	var _result settings.SettingsServiceListPromptsResult
	if err = p.c.Call(ctx, "ListPrompts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ResolveTranslationConfig(ctx context.Context, req *settings.ResolveTranslationConfigReq) (r *settings.ResolveTranslationConfigResp, err error) {
	var _args settings.SettingsServiceResolveTranslationConfigArgs
	_args.Req = req
	var _result settings.SettingsServiceResolveTranslationConfigResult
	if err = p.c.Call(ctx, "ResolveTranslationConfig", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ResolveLLMProfile(ctx context.Context, req *settings.ResolveLLMProfileReq) (r *settings.ResolveLLMProfileResp, err error) {
	var _args settings.SettingsServiceResolveLLMProfileArgs
	_args.Req = req
	var _result settings.SettingsServiceResolveLLMProfileResult
	if err = p.c.Call(ctx, "ResolveLLMProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SaveSkill(ctx context.Context, req *settings.SaveSkillReq) (r *settings.SaveSkillResp, err error) {
	var _args settings.SettingsServiceSaveSkillArgs
	_args.Req = req
	var _result settings.SettingsServiceSaveSkillResult
	if err = p.c.Call(ctx, "SaveSkill", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListSkills(ctx context.Context, req *settings.ListSkillsReq) (r *settings.ListSkillsResp, err error) {
	var _args settings.SettingsServiceListSkillsArgs
	_args.Req = req
	var _result settings.SettingsServiceListSkillsResult
	if err = p.c.Call(ctx, "ListSkills", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSkill(ctx context.Context, req *settings.GetSkillReq) (r *settings.GetSkillResp, err error) {
	var _args settings.SettingsServiceGetSkillArgs
	_args.Req = req
	var _result settings.SettingsServiceGetSkillResult
	if err = p.c.Call(ctx, "GetSkill", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateSkillContent(ctx context.Context, req *settings.UpdateSkillContentReq) (r *settings.UpdateSkillContentResp, err error) {
	var _args settings.SettingsServiceUpdateSkillContentArgs
	_args.Req = req
	var _result settings.SettingsServiceUpdateSkillContentResult
	if err = p.c.Call(ctx, "UpdateSkillContent", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteSkill(ctx context.Context, req *settings.DeleteSkillReq) (r *settings.DeleteSkillResp, err error) {
	var _args settings.SettingsServiceDeleteSkillArgs
	_args.Req = req
	var _result settings.SettingsServiceDeleteSkillResult
	if err = p.c.Call(ctx, "DeleteSkill", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
