// Code generated by thriftgo (0.3.18). DO NOT EDIT.

package mcp_gateway

import (
	"context"
	"fmt"
	"strings"
)

type MCPTool struct {
	Name             string `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Description      string `thrift:"description,2" frugal:"2,default,string" json:"description"`
	Source           string `thrift:"source,3" frugal:"3,default,string" json:"source"`
	ServerName       string `thrift:"server_name,4" frugal:"4,default,string" json:"server_name"`
	InputSchemaJson  string `thrift:"input_schema_json,5" frugal:"5,default,string" json:"input_schema_json"`
	RequiresApproval bool   `thrift:"requires_approval,6" frugal:"6,default,bool" json:"requires_approval"`
}

func NewMCPTool() *MCPTool {
	return &MCPTool{}
}

func (p *MCPTool) InitDefault() {
}

func (p *MCPTool) GetName() (v string) {
	return p.Name
}

func (p *MCPTool) GetDescription() (v string) {
	return p.Description
}

func (p *MCPTool) GetSource() (v string) {
	return p.Source
}

func (p *MCPTool) GetServerName() (v string) {
	return p.ServerName
}

func (p *MCPTool) GetInputSchemaJson() (v string) {
	return p.InputSchemaJson
}

func (p *MCPTool) GetRequiresApproval() (v bool) {
	return p.RequiresApproval
}
func (p *MCPTool) SetName(val string) {
	p.Name = val
}
func (p *MCPTool) SetDescription(val string) {
	p.Description = val
}
func (p *MCPTool) SetSource(val string) {
	p.Source = val
}
func (p *MCPTool) SetServerName(val string) {
	p.ServerName = val
}
func (p *MCPTool) SetInputSchemaJson(val string) {
	p.InputSchemaJson = val
}
func (p *MCPTool) SetRequiresApproval(val bool) {
	p.RequiresApproval = val
}

func (p *MCPTool) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MCPTool(%+v)", *p)
}

func (p *MCPTool) DeepEqual(ano *MCPTool) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Name) {
		return false
	}
	if !p.Field2DeepEqual(ano.Description) {
		return false
	}
	if !p.Field3DeepEqual(ano.Source) {
		return false
	}
	if !p.Field4DeepEqual(ano.ServerName) {
		return false
	}
	if !p.Field5DeepEqual(ano.InputSchemaJson) {
		return false
	}
	if !p.Field6DeepEqual(ano.RequiresApproval) {
		return false
	}
	return true
}

func (p *MCPTool) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Name, src) != 0 {
		return false
	}
	return true
}
func (p *MCPTool) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Description, src) != 0 {
		return false
	}
	return true
}
func (p *MCPTool) Field3DeepEqual(src string) bool {

	if strings.Compare(p.Source, src) != 0 {
		return false
	}
	return true
}
func (p *MCPTool) Field4DeepEqual(src string) bool {

	if strings.Compare(p.ServerName, src) != 0 {
		return false
	}
	return true
}
func (p *MCPTool) Field5DeepEqual(src string) bool {

	if strings.Compare(p.InputSchemaJson, src) != 0 {
		return false
	}
	return true
}
func (p *MCPTool) Field6DeepEqual(src bool) bool {

	if p.RequiresApproval != src {
		return false
	}
	return true
}

var fieldIDToName_MCPTool = map[int16]string{
	1: "name",
	2: "description",
	3: "source",
	4: "server_name",
	5: "input_schema_json",
	6: "requires_approval",
}

type ListToolsReq struct {
	UserId         int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	AgentId        int64 `thrift:"agent_id,2" frugal:"2,default,i64" json:"agent_id"`
	ConversationId int64 `thrift:"conversation_id,3" frugal:"3,default,i64" json:"conversation_id"`
}

func NewListToolsReq() *ListToolsReq {
	return &ListToolsReq{}
}

func (p *ListToolsReq) InitDefault() {
}

func (p *ListToolsReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *ListToolsReq) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *ListToolsReq) GetConversationId() (v int64) {
	return p.ConversationId
}
func (p *ListToolsReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *ListToolsReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *ListToolsReq) SetConversationId(val int64) {
	p.ConversationId = val
}

func (p *ListToolsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListToolsReq(%+v)", *p)
}

func (p *ListToolsReq) DeepEqual(ano *ListToolsReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.UserId) {
		return false
	}
	if !p.Field2DeepEqual(ano.AgentId) {
		return false
	}
	if !p.Field3DeepEqual(ano.ConversationId) {
		return false
	}
	return true
}

func (p *ListToolsReq) Field1DeepEqual(src int64) bool {

	if p.UserId != src {
		return false
	}
	return true
}
func (p *ListToolsReq) Field2DeepEqual(src int64) bool {

	if p.AgentId != src {
		return false
	}
	return true
}
func (p *ListToolsReq) Field3DeepEqual(src int64) bool {

	if p.ConversationId != src {
		return false
	}
	return true
}

var fieldIDToName_ListToolsReq = map[int16]string{
	1: "user_id",
	2: "agent_id",
	3: "conversation_id",
}

type ListToolsResp struct {
	Success bool       `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Tools   []*MCPTool `thrift:"tools,2" frugal:"2,default,list<MCPTool>" json:"tools"`
	Msg     string     `thrift:"msg,3" frugal:"3,default,string" json:"msg"`
}

func NewListToolsResp() *ListToolsResp {
	return &ListToolsResp{}
}

func (p *ListToolsResp) InitDefault() {
}

func (p *ListToolsResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *ListToolsResp) GetTools() (v []*MCPTool) {
	return p.Tools
}

func (p *ListToolsResp) GetMsg() (v string) {
	return p.Msg
}
func (p *ListToolsResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *ListToolsResp) SetTools(val []*MCPTool) {
	p.Tools = val
}
func (p *ListToolsResp) SetMsg(val string) {
	p.Msg = val
}

func (p *ListToolsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListToolsResp(%+v)", *p)
}

func (p *ListToolsResp) DeepEqual(ano *ListToolsResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Success) {
		return false
	}
	if !p.Field2DeepEqual(ano.Tools) {
		return false
	}
	if !p.Field3DeepEqual(ano.Msg) {
		return false
	}
	return true
}

func (p *ListToolsResp) Field1DeepEqual(src bool) bool {

	if p.Success != src {
		return false
	}
	return true
}
func (p *ListToolsResp) Field2DeepEqual(src []*MCPTool) bool {

	if len(p.Tools) != len(src) {
		return false
	}
	for i, v := range p.Tools {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *ListToolsResp) Field3DeepEqual(src string) bool {

	if strings.Compare(p.Msg, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_ListToolsResp = map[int16]string{
	1: "success",
	2: "tools",
	3: "msg",
}

type CallToolReq struct {
	UserId         int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	AgentId        int64  `thrift:"agent_id,2" frugal:"2,default,i64" json:"agent_id"`
	ConversationId int64  `thrift:"conversation_id,3" frugal:"3,default,i64" json:"conversation_id"`
	ToolName       string `thrift:"tool_name,4" frugal:"4,default,string" json:"tool_name"`
	ArgumentsJson  string `thrift:"arguments_json,5" frugal:"5,default,string" json:"arguments_json"`
	TraceId        string `thrift:"trace_id,6" frugal:"6,default,string" json:"trace_id"`
}

func NewCallToolReq() *CallToolReq {
	return &CallToolReq{}
}

func (p *CallToolReq) InitDefault() {
}

func (p *CallToolReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *CallToolReq) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *CallToolReq) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *CallToolReq) GetToolName() (v string) {
	return p.ToolName
}

func (p *CallToolReq) GetArgumentsJson() (v string) {
	return p.ArgumentsJson
}

func (p *CallToolReq) GetTraceId() (v string) {
	return p.TraceId
}
func (p *CallToolReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *CallToolReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *CallToolReq) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *CallToolReq) SetToolName(val string) {
	p.ToolName = val
}
func (p *CallToolReq) SetArgumentsJson(val string) {
	p.ArgumentsJson = val
}
func (p *CallToolReq) SetTraceId(val string) {
	p.TraceId = val
}

func (p *CallToolReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CallToolReq(%+v)", *p)
}

func (p *CallToolReq) DeepEqual(ano *CallToolReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.UserId) {
		return false
	}
	if !p.Field2DeepEqual(ano.AgentId) {
		return false
	}
	if !p.Field3DeepEqual(ano.ConversationId) {
		return false
	}
	if !p.Field4DeepEqual(ano.ToolName) {
		return false
	}
	if !p.Field5DeepEqual(ano.ArgumentsJson) {
		return false
	}
	if !p.Field6DeepEqual(ano.TraceId) {
		return false
	}
	return true
}

func (p *CallToolReq) Field1DeepEqual(src int64) bool {

	if p.UserId != src {
		return false
	}
	return true
}
func (p *CallToolReq) Field2DeepEqual(src int64) bool {

	if p.AgentId != src {
		return false
	}
	return true
}
func (p *CallToolReq) Field3DeepEqual(src int64) bool {

	if p.ConversationId != src {
		return false
	}
	return true
}
func (p *CallToolReq) Field4DeepEqual(src string) bool {

	if strings.Compare(p.ToolName, src) != 0 {
		return false
	}
	return true
}
func (p *CallToolReq) Field5DeepEqual(src string) bool {

	if strings.Compare(p.ArgumentsJson, src) != 0 {
		return false
	}
	return true
}
func (p *CallToolReq) Field6DeepEqual(src string) bool {

	if strings.Compare(p.TraceId, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_CallToolReq = map[int16]string{
	1: "user_id",
	2: "agent_id",
	3: "conversation_id",
	4: "tool_name",
	5: "arguments_json",
	6: "trace_id",
}

type CallToolResp struct {
	Success    bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	ToolName   string `thrift:"tool_name,2" frugal:"2,default,string" json:"tool_name"`
	ResultText string `thrift:"result_text,3" frugal:"3,default,string" json:"result_text"`
	ResultJson string `thrift:"result_json,4" frugal:"4,default,string" json:"result_json"`
	TraceId    string `thrift:"trace_id,5" frugal:"5,default,string" json:"trace_id"`
	Msg        string `thrift:"msg,6" frugal:"6,default,string" json:"msg"`
}

func NewCallToolResp() *CallToolResp {
	return &CallToolResp{}
}

func (p *CallToolResp) InitDefault() {
}

func (p *CallToolResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *CallToolResp) GetToolName() (v string) {
	return p.ToolName
}

func (p *CallToolResp) GetResultText() (v string) {
	return p.ResultText
}

func (p *CallToolResp) GetResultJson() (v string) {
	return p.ResultJson
}

func (p *CallToolResp) GetTraceId() (v string) {
	return p.TraceId
}

func (p *CallToolResp) GetMsg() (v string) {
	return p.Msg
}
func (p *CallToolResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *CallToolResp) SetToolName(val string) {
	p.ToolName = val
}
func (p *CallToolResp) SetResultText(val string) {
	p.ResultText = val
}
func (p *CallToolResp) SetResultJson(val string) {
	p.ResultJson = val
}
func (p *CallToolResp) SetTraceId(val string) {
	p.TraceId = val
}
func (p *CallToolResp) SetMsg(val string) {
	p.Msg = val
}

func (p *CallToolResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CallToolResp(%+v)", *p)
}

func (p *CallToolResp) DeepEqual(ano *CallToolResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Success) {
		return false
	}
	if !p.Field2DeepEqual(ano.ToolName) {
		return false
	}
	if !p.Field3DeepEqual(ano.ResultText) {
		return false
	}
	if !p.Field4DeepEqual(ano.ResultJson) {
		return false
	}
	if !p.Field5DeepEqual(ano.TraceId) {
		return false
	}
	if !p.Field6DeepEqual(ano.Msg) {
		return false
	}
	return true
}

func (p *CallToolResp) Field1DeepEqual(src bool) bool {

	if p.Success != src {
		return false
	}
	return true
}
func (p *CallToolResp) Field2DeepEqual(src string) bool {

	if strings.Compare(p.ToolName, src) != 0 {
		return false
	}
	return true
}
func (p *CallToolResp) Field3DeepEqual(src string) bool {

	if strings.Compare(p.ResultText, src) != 0 {
		return false
	}
	return true
}
func (p *CallToolResp) Field4DeepEqual(src string) bool {

	if strings.Compare(p.ResultJson, src) != 0 {
		return false
	}
	return true
}
func (p *CallToolResp) Field5DeepEqual(src string) bool {

	if strings.Compare(p.TraceId, src) != 0 {
		return false
	}
	return true
}
func (p *CallToolResp) Field6DeepEqual(src string) bool {

	if strings.Compare(p.Msg, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_CallToolResp = map[int16]string{
	1: "success",
	2: "tool_name",
	3: "result_text",
	4: "result_json",
	5: "trace_id",
	6: "msg",
}

type GetToolSchemaReq struct {
	UserId         int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	AgentId        int64  `thrift:"agent_id,2" frugal:"2,default,i64" json:"agent_id"`
	ConversationId int64  `thrift:"conversation_id,3" frugal:"3,default,i64" json:"conversation_id"`
	ToolName       string `thrift:"tool_name,4" frugal:"4,default,string" json:"tool_name"`
}

func NewGetToolSchemaReq() *GetToolSchemaReq {
	return &GetToolSchemaReq{}
}

func (p *GetToolSchemaReq) InitDefault() {
}

func (p *GetToolSchemaReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetToolSchemaReq) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *GetToolSchemaReq) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *GetToolSchemaReq) GetToolName() (v string) {
	return p.ToolName
}
func (p *GetToolSchemaReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetToolSchemaReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *GetToolSchemaReq) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *GetToolSchemaReq) SetToolName(val string) {
	p.ToolName = val
}

func (p *GetToolSchemaReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetToolSchemaReq(%+v)", *p)
}

func (p *GetToolSchemaReq) DeepEqual(ano *GetToolSchemaReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.UserId) {
		return false
	}
	if !p.Field2DeepEqual(ano.AgentId) {
		return false
	}
	if !p.Field3DeepEqual(ano.ConversationId) {
		return false
	}
	if !p.Field4DeepEqual(ano.ToolName) {
		return false
	}
	return true
}

func (p *GetToolSchemaReq) Field1DeepEqual(src int64) bool {

	if p.UserId != src {
		return false
	}
	return true
}
func (p *GetToolSchemaReq) Field2DeepEqual(src int64) bool {

	if p.AgentId != src {
		return false
	}
	return true
}
func (p *GetToolSchemaReq) Field3DeepEqual(src int64) bool {

	if p.ConversationId != src {
		return false
	}
	return true
}
func (p *GetToolSchemaReq) Field4DeepEqual(src string) bool {

	if strings.Compare(p.ToolName, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_GetToolSchemaReq = map[int16]string{
	1: "user_id",
	2: "agent_id",
	3: "conversation_id",
	4: "tool_name",
}

type GetToolSchemaResp struct {
	Success bool     `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Tool    *MCPTool `thrift:"tool,2" frugal:"2,default,MCPTool" json:"tool"`
	Msg     string   `thrift:"msg,3" frugal:"3,default,string" json:"msg"`
}

func NewGetToolSchemaResp() *GetToolSchemaResp {
	return &GetToolSchemaResp{}
}

func (p *GetToolSchemaResp) InitDefault() {
}

func (p *GetToolSchemaResp) GetSuccess() (v bool) {
	return p.Success
}

var GetToolSchemaResp_Tool_DEFAULT *MCPTool

func (p *GetToolSchemaResp) GetTool() (v *MCPTool) {
	if !p.IsSetTool() {
		return GetToolSchemaResp_Tool_DEFAULT
	}
	return p.Tool
}

func (p *GetToolSchemaResp) GetMsg() (v string) {
	return p.Msg
}
func (p *GetToolSchemaResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *GetToolSchemaResp) SetTool(val *MCPTool) {
	p.Tool = val
}
func (p *GetToolSchemaResp) SetMsg(val string) {
	p.Msg = val
}

func (p *GetToolSchemaResp) IsSetTool() bool {
	return p.Tool != nil
}

func (p *GetToolSchemaResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetToolSchemaResp(%+v)", *p)
}

func (p *GetToolSchemaResp) DeepEqual(ano *GetToolSchemaResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Success) {
		return false
	}
	if !p.Field2DeepEqual(ano.Tool) {
		return false
	}
	if !p.Field3DeepEqual(ano.Msg) {
		return false
	}
	return true
}

func (p *GetToolSchemaResp) Field1DeepEqual(src bool) bool {

	if p.Success != src {
		return false
	}
	return true
}
func (p *GetToolSchemaResp) Field2DeepEqual(src *MCPTool) bool {

	if !p.Tool.DeepEqual(src) {
		return false
	}
	return true
}
func (p *GetToolSchemaResp) Field3DeepEqual(src string) bool {

	if strings.Compare(p.Msg, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_GetToolSchemaResp = map[int16]string{
	1: "success",
	2: "tool",
	3: "msg",
}

type MCPToolCallTrace struct {
	Id             int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	UserId         int64  `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	AgentId        int64  `thrift:"agent_id,3" frugal:"3,default,i64" json:"agent_id"`
	ConversationId int64  `thrift:"conversation_id,4" frugal:"4,default,i64" json:"conversation_id"`
	ToolName       string `thrift:"tool_name,5" frugal:"5,default,string" json:"tool_name"`
	Source         string `thrift:"source,6" frugal:"6,default,string" json:"source"`
	ServerName     string `thrift:"server_name,7" frugal:"7,default,string" json:"server_name"`
	TraceId        string `thrift:"trace_id,8" frugal:"8,default,string" json:"trace_id"`
	Status         string `thrift:"status,9" frugal:"9,default,string" json:"status"`
	LatencyMs      int64  `thrift:"latency_ms,10" frugal:"10,default,i64" json:"latency_ms"`
	ErrorMessage   string `thrift:"error_message,11" frugal:"11,default,string" json:"error_message"`
	CreatedAt      string `thrift:"created_at,12" frugal:"12,default,string" json:"created_at"`
}

func NewMCPToolCallTrace() *MCPToolCallTrace {
	return &MCPToolCallTrace{}
}

func (p *MCPToolCallTrace) InitDefault() {
}

func (p *MCPToolCallTrace) GetId() (v int64) {
	return p.Id
}

func (p *MCPToolCallTrace) GetUserId() (v int64) {
	return p.UserId
}

func (p *MCPToolCallTrace) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *MCPToolCallTrace) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *MCPToolCallTrace) GetToolName() (v string) {
	return p.ToolName
}

func (p *MCPToolCallTrace) GetSource() (v string) {
	return p.Source
}

func (p *MCPToolCallTrace) GetServerName() (v string) {
	return p.ServerName
}

func (p *MCPToolCallTrace) GetTraceId() (v string) {
	return p.TraceId
}

func (p *MCPToolCallTrace) GetStatus() (v string) {
	return p.Status
}

func (p *MCPToolCallTrace) GetLatencyMs() (v int64) {
	return p.LatencyMs
}

func (p *MCPToolCallTrace) GetErrorMessage() (v string) {
	return p.ErrorMessage
}

func (p *MCPToolCallTrace) GetCreatedAt() (v string) {
	return p.CreatedAt
}
func (p *MCPToolCallTrace) SetId(val int64) {
	p.Id = val
}
func (p *MCPToolCallTrace) SetUserId(val int64) {
	p.UserId = val
}
func (p *MCPToolCallTrace) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *MCPToolCallTrace) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *MCPToolCallTrace) SetToolName(val string) {
	p.ToolName = val
}
func (p *MCPToolCallTrace) SetSource(val string) {
	p.Source = val
}
func (p *MCPToolCallTrace) SetServerName(val string) {
	p.ServerName = val
}
func (p *MCPToolCallTrace) SetTraceId(val string) {
	p.TraceId = val
}
func (p *MCPToolCallTrace) SetStatus(val string) {
	p.Status = val
}
func (p *MCPToolCallTrace) SetLatencyMs(val int64) {
	p.LatencyMs = val
}
func (p *MCPToolCallTrace) SetErrorMessage(val string) {
	p.ErrorMessage = val
}
func (p *MCPToolCallTrace) SetCreatedAt(val string) {
	p.CreatedAt = val
}

func (p *MCPToolCallTrace) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MCPToolCallTrace(%+v)", *p)
}

func (p *MCPToolCallTrace) DeepEqual(ano *MCPToolCallTrace) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Id) {
		return false
	}
	if !p.Field2DeepEqual(ano.UserId) {
		return false
	}
	if !p.Field3DeepEqual(ano.AgentId) {
		return false
	}
	if !p.Field4DeepEqual(ano.ConversationId) {
		return false
	}
	if !p.Field5DeepEqual(ano.ToolName) {
		return false
	}
	if !p.Field6DeepEqual(ano.Source) {
		return false
	}
	if !p.Field7DeepEqual(ano.ServerName) {
		return false
	}
	if !p.Field8DeepEqual(ano.TraceId) {
		return false
	}
	if !p.Field9DeepEqual(ano.Status) {
		return false
	}
	if !p.Field10DeepEqual(ano.LatencyMs) {
		return false
	}
	if !p.Field11DeepEqual(ano.ErrorMessage) {
		return false
	}
	if !p.Field12DeepEqual(ano.CreatedAt) {
		return false
	}
	return true
}

func (p *MCPToolCallTrace) Field1DeepEqual(src int64) bool {

	if p.Id != src {
		return false
	}
	return true
}
func (p *MCPToolCallTrace) Field2DeepEqual(src int64) bool {

	if p.UserId != src {
		return false
	}
	return true
}
func (p *MCPToolCallTrace) Field3DeepEqual(src int64) bool {

	if p.AgentId != src {
		return false
	}
	return true
}
func (p *MCPToolCallTrace) Field4DeepEqual(src int64) bool {

	if p.ConversationId != src {
		return false
	}
	return true
}
func (p *MCPToolCallTrace) Field5DeepEqual(src string) bool {

	if strings.Compare(p.ToolName, src) != 0 {
		return false
	}
	return true
}
func (p *MCPToolCallTrace) Field6DeepEqual(src string) bool {

	if strings.Compare(p.Source, src) != 0 {
		return false
	}
	return true
}
func (p *MCPToolCallTrace) Field7DeepEqual(src string) bool {

	if strings.Compare(p.ServerName, src) != 0 {
		return false
	}
	return true
}
func (p *MCPToolCallTrace) Field8DeepEqual(src string) bool {

	if strings.Compare(p.TraceId, src) != 0 {
		return false
	}
	return true
}
func (p *MCPToolCallTrace) Field9DeepEqual(src string) bool {

	if strings.Compare(p.Status, src) != 0 {
		return false
	}
	return true
}
func (p *MCPToolCallTrace) Field10DeepEqual(src int64) bool {

	if p.LatencyMs != src {
		return false
	}
	return true
}
func (p *MCPToolCallTrace) Field11DeepEqual(src string) bool {

	if strings.Compare(p.ErrorMessage, src) != 0 {
		return false
	}
	return true
}
func (p *MCPToolCallTrace) Field12DeepEqual(src string) bool {

	if strings.Compare(p.CreatedAt, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_MCPToolCallTrace = map[int16]string{
	1:  "id",
	2:  "user_id",
	3:  "agent_id",
	4:  "conversation_id",
	5:  "tool_name",
	6:  "source",
	7:  "server_name",
	8:  "trace_id",
	9:  "status",
	10: "latency_ms",
	11: "error_message",
	12: "created_at",
}

type ListToolCallsReq struct {
	UserId         int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	AgentId        int64 `thrift:"agent_id,2" frugal:"2,default,i64" json:"agent_id"`
	ConversationId int64 `thrift:"conversation_id,3" frugal:"3,default,i64" json:"conversation_id"`
	Limit          int64 `thrift:"limit,4" frugal:"4,default,i64" json:"limit"`
	Offset         int64 `thrift:"offset,5" frugal:"5,default,i64" json:"offset"`
}

func NewListToolCallsReq() *ListToolCallsReq {
	return &ListToolCallsReq{}
}

func (p *ListToolCallsReq) InitDefault() {
}

func (p *ListToolCallsReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *ListToolCallsReq) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *ListToolCallsReq) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *ListToolCallsReq) GetLimit() (v int64) {
	return p.Limit
}

func (p *ListToolCallsReq) GetOffset() (v int64) {
	return p.Offset
}
func (p *ListToolCallsReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *ListToolCallsReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *ListToolCallsReq) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *ListToolCallsReq) SetLimit(val int64) {
	p.Limit = val
}
func (p *ListToolCallsReq) SetOffset(val int64) {
	p.Offset = val
}

func (p *ListToolCallsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListToolCallsReq(%+v)", *p)
}

func (p *ListToolCallsReq) DeepEqual(ano *ListToolCallsReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.UserId) {
		return false
	}
	if !p.Field2DeepEqual(ano.AgentId) {
		return false
	}
	if !p.Field3DeepEqual(ano.ConversationId) {
		return false
	}
	if !p.Field4DeepEqual(ano.Limit) {
		return false
	}
	if !p.Field5DeepEqual(ano.Offset) {
		return false
	}
	return true
}

func (p *ListToolCallsReq) Field1DeepEqual(src int64) bool {

	if p.UserId != src {
		return false
	}
	return true
}
func (p *ListToolCallsReq) Field2DeepEqual(src int64) bool {

	if p.AgentId != src {
		return false
	}
	return true
}
func (p *ListToolCallsReq) Field3DeepEqual(src int64) bool {

	if p.ConversationId != src {
		return false
	}
	return true
}
func (p *ListToolCallsReq) Field4DeepEqual(src int64) bool {

	if p.Limit != src {
		return false
	}
	return true
}
func (p *ListToolCallsReq) Field5DeepEqual(src int64) bool {

	if p.Offset != src {
		return false
	}
	return true
}

var fieldIDToName_ListToolCallsReq = map[int16]string{
	1: "user_id",
	2: "agent_id",
	3: "conversation_id",
	4: "limit",
	5: "offset",
}

type ListToolCallsResp struct {
	Success bool                `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Traces  []*MCPToolCallTrace `thrift:"traces,2" frugal:"2,default,list<MCPToolCallTrace>" json:"traces"`
	Total   int64               `thrift:"total,3" frugal:"3,default,i64" json:"total"`
	Msg     string              `thrift:"msg,4" frugal:"4,default,string" json:"msg"`
}

func NewListToolCallsResp() *ListToolCallsResp {
	return &ListToolCallsResp{}
}

func (p *ListToolCallsResp) InitDefault() {
}

func (p *ListToolCallsResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *ListToolCallsResp) GetTraces() (v []*MCPToolCallTrace) {
	return p.Traces
}

func (p *ListToolCallsResp) GetTotal() (v int64) {
	return p.Total
}

func (p *ListToolCallsResp) GetMsg() (v string) {
	return p.Msg
}
func (p *ListToolCallsResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *ListToolCallsResp) SetTraces(val []*MCPToolCallTrace) {
	p.Traces = val
}
func (p *ListToolCallsResp) SetTotal(val int64) {
	p.Total = val
}
func (p *ListToolCallsResp) SetMsg(val string) {
	p.Msg = val
}

func (p *ListToolCallsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListToolCallsResp(%+v)", *p)
}

func (p *ListToolCallsResp) DeepEqual(ano *ListToolCallsResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Success) {
		return false
	}
	if !p.Field2DeepEqual(ano.Traces) {
		return false
	}
	if !p.Field3DeepEqual(ano.Total) {
		return false
	}
	if !p.Field4DeepEqual(ano.Msg) {
		return false
	}
	return true
}

func (p *ListToolCallsResp) Field1DeepEqual(src bool) bool {

	if p.Success != src {
		return false
	}
	return true
}
func (p *ListToolCallsResp) Field2DeepEqual(src []*MCPToolCallTrace) bool {

	if len(p.Traces) != len(src) {
		return false
	}
	for i, v := range p.Traces {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *ListToolCallsResp) Field3DeepEqual(src int64) bool {

	if p.Total != src {
		return false
	}
	return true
}
func (p *ListToolCallsResp) Field4DeepEqual(src string) bool {

	if strings.Compare(p.Msg, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_ListToolCallsResp = map[int16]string{
	1: "success",
	2: "traces",
	3: "total",
	4: "msg",
}

type GetToolCallTraceReq struct {
	UserId  int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	TraceId string `thrift:"trace_id,2" frugal:"2,default,string" json:"trace_id"`
}

func NewGetToolCallTraceReq() *GetToolCallTraceReq {
	return &GetToolCallTraceReq{}
}

func (p *GetToolCallTraceReq) InitDefault() {
}

func (p *GetToolCallTraceReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetToolCallTraceReq) GetTraceId() (v string) {
	return p.TraceId
}
func (p *GetToolCallTraceReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetToolCallTraceReq) SetTraceId(val string) {
	p.TraceId = val
}

func (p *GetToolCallTraceReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetToolCallTraceReq(%+v)", *p)
}

func (p *GetToolCallTraceReq) DeepEqual(ano *GetToolCallTraceReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.UserId) {
		return false
	}
	if !p.Field2DeepEqual(ano.TraceId) {
		return false
	}
	return true
}

func (p *GetToolCallTraceReq) Field1DeepEqual(src int64) bool {

	if p.UserId != src {
		return false
	}
	return true
}
func (p *GetToolCallTraceReq) Field2DeepEqual(src string) bool {

	if strings.Compare(p.TraceId, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_GetToolCallTraceReq = map[int16]string{
	1: "user_id",
	2: "trace_id",
}

type GetToolCallTraceResp struct {
	Success bool              `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Trace   *MCPToolCallTrace `thrift:"trace,2" frugal:"2,default,MCPToolCallTrace" json:"trace"`
	Msg     string            `thrift:"msg,3" frugal:"3,default,string" json:"msg"`
}

func NewGetToolCallTraceResp() *GetToolCallTraceResp {
	return &GetToolCallTraceResp{}
}

func (p *GetToolCallTraceResp) InitDefault() {
}

func (p *GetToolCallTraceResp) GetSuccess() (v bool) {
	return p.Success
}

var GetToolCallTraceResp_Trace_DEFAULT *MCPToolCallTrace

func (p *GetToolCallTraceResp) GetTrace() (v *MCPToolCallTrace) {
	if !p.IsSetTrace() {
		return GetToolCallTraceResp_Trace_DEFAULT
	}
	return p.Trace
}

func (p *GetToolCallTraceResp) GetMsg() (v string) {
	return p.Msg
}
func (p *GetToolCallTraceResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *GetToolCallTraceResp) SetTrace(val *MCPToolCallTrace) {
	p.Trace = val
}
func (p *GetToolCallTraceResp) SetMsg(val string) {
	p.Msg = val
}

func (p *GetToolCallTraceResp) IsSetTrace() bool {
	return p.Trace != nil
}

func (p *GetToolCallTraceResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetToolCallTraceResp(%+v)", *p)
}

func (p *GetToolCallTraceResp) DeepEqual(ano *GetToolCallTraceResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Success) {
		return false
	}
	if !p.Field2DeepEqual(ano.Trace) {
		return false
	}
	if !p.Field3DeepEqual(ano.Msg) {
		return false
	}
	return true
}

func (p *GetToolCallTraceResp) Field1DeepEqual(src bool) bool {

	if p.Success != src {
		return false
	}
	return true
}
func (p *GetToolCallTraceResp) Field2DeepEqual(src *MCPToolCallTrace) bool {

	if !p.Trace.DeepEqual(src) {
		return false
	}
	return true
}
func (p *GetToolCallTraceResp) Field3DeepEqual(src string) bool {

	if strings.Compare(p.Msg, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_GetToolCallTraceResp = map[int16]string{
	1: "success",
	2: "trace",
	3: "msg",
}

type MCPGatewayService interface {
	ListTools(ctx context.Context, req *ListToolsReq) (r *ListToolsResp, err error)

	CallTool(ctx context.Context, req *CallToolReq) (r *CallToolResp, err error)

	GetToolSchema(ctx context.Context, req *GetToolSchemaReq) (r *GetToolSchemaResp, err error)

	ListToolCalls(ctx context.Context, req *ListToolCallsReq) (r *ListToolCallsResp, err error)

	GetToolCallTrace(ctx context.Context, req *GetToolCallTraceReq) (r *GetToolCallTraceResp, err error)
}

type MCPGatewayServiceListToolsArgs struct {
	Req *ListToolsReq `thrift:"req,1" frugal:"1,default,ListToolsReq" json:"req"`
}

func NewMCPGatewayServiceListToolsArgs() *MCPGatewayServiceListToolsArgs {
	return &MCPGatewayServiceListToolsArgs{}
}

func (p *MCPGatewayServiceListToolsArgs) InitDefault() {
}

var MCPGatewayServiceListToolsArgs_Req_DEFAULT *ListToolsReq

func (p *MCPGatewayServiceListToolsArgs) GetReq() (v *ListToolsReq) {
	if !p.IsSetReq() {
		return MCPGatewayServiceListToolsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MCPGatewayServiceListToolsArgs) SetReq(val *ListToolsReq) {
	p.Req = val
}

func (p *MCPGatewayServiceListToolsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MCPGatewayServiceListToolsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MCPGatewayServiceListToolsArgs(%+v)", *p)
}

func (p *MCPGatewayServiceListToolsArgs) DeepEqual(ano *MCPGatewayServiceListToolsArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *MCPGatewayServiceListToolsArgs) Field1DeepEqual(src *ListToolsReq) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_MCPGatewayServiceListToolsArgs = map[int16]string{
	1: "req",
}

type MCPGatewayServiceListToolsResult struct {
	Success *ListToolsResp `thrift:"success,0,optional" frugal:"0,optional,ListToolsResp" json:"success,omitempty"`
}

func NewMCPGatewayServiceListToolsResult() *MCPGatewayServiceListToolsResult {
	return &MCPGatewayServiceListToolsResult{}
}

func (p *MCPGatewayServiceListToolsResult) InitDefault() {
}

var MCPGatewayServiceListToolsResult_Success_DEFAULT *ListToolsResp

func (p *MCPGatewayServiceListToolsResult) GetSuccess() (v *ListToolsResp) {
	if !p.IsSetSuccess() {
		return MCPGatewayServiceListToolsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MCPGatewayServiceListToolsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListToolsResp)
}

func (p *MCPGatewayServiceListToolsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MCPGatewayServiceListToolsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MCPGatewayServiceListToolsResult(%+v)", *p)
}

func (p *MCPGatewayServiceListToolsResult) DeepEqual(ano *MCPGatewayServiceListToolsResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *MCPGatewayServiceListToolsResult) Field0DeepEqual(src *ListToolsResp) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_MCPGatewayServiceListToolsResult = map[int16]string{
	0: "success",
}

type MCPGatewayServiceCallToolArgs struct {
	Req *CallToolReq `thrift:"req,1" frugal:"1,default,CallToolReq" json:"req"`
}

func NewMCPGatewayServiceCallToolArgs() *MCPGatewayServiceCallToolArgs {
	return &MCPGatewayServiceCallToolArgs{}
}

func (p *MCPGatewayServiceCallToolArgs) InitDefault() {
}

var MCPGatewayServiceCallToolArgs_Req_DEFAULT *CallToolReq

func (p *MCPGatewayServiceCallToolArgs) GetReq() (v *CallToolReq) {
	if !p.IsSetReq() {
		return MCPGatewayServiceCallToolArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MCPGatewayServiceCallToolArgs) SetReq(val *CallToolReq) {
	p.Req = val
}

func (p *MCPGatewayServiceCallToolArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MCPGatewayServiceCallToolArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MCPGatewayServiceCallToolArgs(%+v)", *p)
}

func (p *MCPGatewayServiceCallToolArgs) DeepEqual(ano *MCPGatewayServiceCallToolArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *MCPGatewayServiceCallToolArgs) Field1DeepEqual(src *CallToolReq) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_MCPGatewayServiceCallToolArgs = map[int16]string{
	1: "req",
}

type MCPGatewayServiceCallToolResult struct {
	Success *CallToolResp `thrift:"success,0,optional" frugal:"0,optional,CallToolResp" json:"success,omitempty"`
}

func NewMCPGatewayServiceCallToolResult() *MCPGatewayServiceCallToolResult {
	return &MCPGatewayServiceCallToolResult{}
}

func (p *MCPGatewayServiceCallToolResult) InitDefault() {
}

var MCPGatewayServiceCallToolResult_Success_DEFAULT *CallToolResp

func (p *MCPGatewayServiceCallToolResult) GetSuccess() (v *CallToolResp) {
	if !p.IsSetSuccess() {
		return MCPGatewayServiceCallToolResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MCPGatewayServiceCallToolResult) SetSuccess(x interface{}) {
	p.Success = x.(*CallToolResp)
}

func (p *MCPGatewayServiceCallToolResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MCPGatewayServiceCallToolResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MCPGatewayServiceCallToolResult(%+v)", *p)
}

func (p *MCPGatewayServiceCallToolResult) DeepEqual(ano *MCPGatewayServiceCallToolResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *MCPGatewayServiceCallToolResult) Field0DeepEqual(src *CallToolResp) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_MCPGatewayServiceCallToolResult = map[int16]string{
	0: "success",
}

type MCPGatewayServiceGetToolSchemaArgs struct {
	Req *GetToolSchemaReq `thrift:"req,1" frugal:"1,default,GetToolSchemaReq" json:"req"`
}

func NewMCPGatewayServiceGetToolSchemaArgs() *MCPGatewayServiceGetToolSchemaArgs {
	return &MCPGatewayServiceGetToolSchemaArgs{}
}

func (p *MCPGatewayServiceGetToolSchemaArgs) InitDefault() {
}

var MCPGatewayServiceGetToolSchemaArgs_Req_DEFAULT *GetToolSchemaReq

func (p *MCPGatewayServiceGetToolSchemaArgs) GetReq() (v *GetToolSchemaReq) {
	if !p.IsSetReq() {
		return MCPGatewayServiceGetToolSchemaArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MCPGatewayServiceGetToolSchemaArgs) SetReq(val *GetToolSchemaReq) {
	p.Req = val
}

func (p *MCPGatewayServiceGetToolSchemaArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MCPGatewayServiceGetToolSchemaArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MCPGatewayServiceGetToolSchemaArgs(%+v)", *p)
}

func (p *MCPGatewayServiceGetToolSchemaArgs) DeepEqual(ano *MCPGatewayServiceGetToolSchemaArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *MCPGatewayServiceGetToolSchemaArgs) Field1DeepEqual(src *GetToolSchemaReq) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_MCPGatewayServiceGetToolSchemaArgs = map[int16]string{
	1: "req",
}

type MCPGatewayServiceGetToolSchemaResult struct {
	Success *GetToolSchemaResp `thrift:"success,0,optional" frugal:"0,optional,GetToolSchemaResp" json:"success,omitempty"`
}

func NewMCPGatewayServiceGetToolSchemaResult() *MCPGatewayServiceGetToolSchemaResult {
	return &MCPGatewayServiceGetToolSchemaResult{}
}

func (p *MCPGatewayServiceGetToolSchemaResult) InitDefault() {
}

var MCPGatewayServiceGetToolSchemaResult_Success_DEFAULT *GetToolSchemaResp

func (p *MCPGatewayServiceGetToolSchemaResult) GetSuccess() (v *GetToolSchemaResp) {
	if !p.IsSetSuccess() {
		return MCPGatewayServiceGetToolSchemaResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MCPGatewayServiceGetToolSchemaResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetToolSchemaResp)
}

func (p *MCPGatewayServiceGetToolSchemaResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MCPGatewayServiceGetToolSchemaResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MCPGatewayServiceGetToolSchemaResult(%+v)", *p)
}

func (p *MCPGatewayServiceGetToolSchemaResult) DeepEqual(ano *MCPGatewayServiceGetToolSchemaResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *MCPGatewayServiceGetToolSchemaResult) Field0DeepEqual(src *GetToolSchemaResp) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_MCPGatewayServiceGetToolSchemaResult = map[int16]string{
	0: "success",
}

type MCPGatewayServiceListToolCallsArgs struct {
	Req *ListToolCallsReq `thrift:"req,1" frugal:"1,default,ListToolCallsReq" json:"req"`
}

func NewMCPGatewayServiceListToolCallsArgs() *MCPGatewayServiceListToolCallsArgs {
	return &MCPGatewayServiceListToolCallsArgs{}
}

func (p *MCPGatewayServiceListToolCallsArgs) InitDefault() {
}

var MCPGatewayServiceListToolCallsArgs_Req_DEFAULT *ListToolCallsReq

func (p *MCPGatewayServiceListToolCallsArgs) GetReq() (v *ListToolCallsReq) {
	if !p.IsSetReq() {
		return MCPGatewayServiceListToolCallsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MCPGatewayServiceListToolCallsArgs) SetReq(val *ListToolCallsReq) {
	p.Req = val
}

func (p *MCPGatewayServiceListToolCallsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MCPGatewayServiceListToolCallsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MCPGatewayServiceListToolCallsArgs(%+v)", *p)
}

func (p *MCPGatewayServiceListToolCallsArgs) DeepEqual(ano *MCPGatewayServiceListToolCallsArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *MCPGatewayServiceListToolCallsArgs) Field1DeepEqual(src *ListToolCallsReq) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_MCPGatewayServiceListToolCallsArgs = map[int16]string{
	1: "req",
}

type MCPGatewayServiceListToolCallsResult struct {
	Success *ListToolCallsResp `thrift:"success,0,optional" frugal:"0,optional,ListToolCallsResp" json:"success,omitempty"`
}

func NewMCPGatewayServiceListToolCallsResult() *MCPGatewayServiceListToolCallsResult {
	return &MCPGatewayServiceListToolCallsResult{}
}

func (p *MCPGatewayServiceListToolCallsResult) InitDefault() {
}

var MCPGatewayServiceListToolCallsResult_Success_DEFAULT *ListToolCallsResp

func (p *MCPGatewayServiceListToolCallsResult) GetSuccess() (v *ListToolCallsResp) {
	if !p.IsSetSuccess() {
		return MCPGatewayServiceListToolCallsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MCPGatewayServiceListToolCallsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListToolCallsResp)
}

func (p *MCPGatewayServiceListToolCallsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MCPGatewayServiceListToolCallsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MCPGatewayServiceListToolCallsResult(%+v)", *p)
}

func (p *MCPGatewayServiceListToolCallsResult) DeepEqual(ano *MCPGatewayServiceListToolCallsResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *MCPGatewayServiceListToolCallsResult) Field0DeepEqual(src *ListToolCallsResp) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_MCPGatewayServiceListToolCallsResult = map[int16]string{
	0: "success",
}

type MCPGatewayServiceGetToolCallTraceArgs struct {
	Req *GetToolCallTraceReq `thrift:"req,1" frugal:"1,default,GetToolCallTraceReq" json:"req"`
}

func NewMCPGatewayServiceGetToolCallTraceArgs() *MCPGatewayServiceGetToolCallTraceArgs {
	return &MCPGatewayServiceGetToolCallTraceArgs{}
}

func (p *MCPGatewayServiceGetToolCallTraceArgs) InitDefault() {
}

var MCPGatewayServiceGetToolCallTraceArgs_Req_DEFAULT *GetToolCallTraceReq

func (p *MCPGatewayServiceGetToolCallTraceArgs) GetReq() (v *GetToolCallTraceReq) {
	if !p.IsSetReq() {
		return MCPGatewayServiceGetToolCallTraceArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MCPGatewayServiceGetToolCallTraceArgs) SetReq(val *GetToolCallTraceReq) {
	p.Req = val
}

func (p *MCPGatewayServiceGetToolCallTraceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MCPGatewayServiceGetToolCallTraceArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MCPGatewayServiceGetToolCallTraceArgs(%+v)", *p)
}

func (p *MCPGatewayServiceGetToolCallTraceArgs) DeepEqual(ano *MCPGatewayServiceGetToolCallTraceArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *MCPGatewayServiceGetToolCallTraceArgs) Field1DeepEqual(src *GetToolCallTraceReq) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_MCPGatewayServiceGetToolCallTraceArgs = map[int16]string{
	1: "req",
}

type MCPGatewayServiceGetToolCallTraceResult struct {
	Success *GetToolCallTraceResp `thrift:"success,0,optional" frugal:"0,optional,GetToolCallTraceResp" json:"success,omitempty"`
}

func NewMCPGatewayServiceGetToolCallTraceResult() *MCPGatewayServiceGetToolCallTraceResult {
	return &MCPGatewayServiceGetToolCallTraceResult{}
}

func (p *MCPGatewayServiceGetToolCallTraceResult) InitDefault() {
}

var MCPGatewayServiceGetToolCallTraceResult_Success_DEFAULT *GetToolCallTraceResp

func (p *MCPGatewayServiceGetToolCallTraceResult) GetSuccess() (v *GetToolCallTraceResp) {
	if !p.IsSetSuccess() {
		return MCPGatewayServiceGetToolCallTraceResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MCPGatewayServiceGetToolCallTraceResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetToolCallTraceResp)
}

func (p *MCPGatewayServiceGetToolCallTraceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MCPGatewayServiceGetToolCallTraceResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MCPGatewayServiceGetToolCallTraceResult(%+v)", *p)
}

func (p *MCPGatewayServiceGetToolCallTraceResult) DeepEqual(ano *MCPGatewayServiceGetToolCallTraceResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *MCPGatewayServiceGetToolCallTraceResult) Field0DeepEqual(src *GetToolCallTraceResp) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_MCPGatewayServiceGetToolCallTraceResult = map[int16]string{
	0: "success",
}
