// Code generated by Kitex v0.16.2. DO NOT EDIT.

package conversationintelligenceservice

import (
	conversation_intelligence "ClaranAIM/kitex_gen/conversation_intelligence"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateDigestJob": kitex.NewMethodInfo(
		createDigestJobHandler,
		newConversationIntelligenceServiceCreateDigestJobArgs,
		newConversationIntelligenceServiceCreateDigestJobResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ProcessDigestJob": kitex.NewMethodInfo(
		processDigestJobHandler,
		newConversationIntelligenceServiceProcessDigestJobArgs,
		newConversationIntelligenceServiceProcessDigestJobResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListArtifacts": kitex.NewMethodInfo(
		listArtifactsHandler,
		newConversationIntelligenceServiceListArtifactsArgs,
		newConversationIntelligenceServiceListArtifactsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListDigestJobs": kitex.NewMethodInfo(
		listDigestJobsHandler,
		newConversationIntelligenceServiceListDigestJobsArgs,
		newConversationIntelligenceServiceListDigestJobsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RetryDigestJob": kitex.NewMethodInfo(
		retryDigestJobHandler,
		newConversationIntelligenceServiceRetryDigestJobArgs,
		newConversationIntelligenceServiceRetryDigestJobResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	conversationIntelligenceServiceServiceInfo                = NewServiceInfo()
	conversationIntelligenceServiceServiceInfoForClient       = NewServiceInfoForClient()
	conversationIntelligenceServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return conversationIntelligenceServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return conversationIntelligenceServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return conversationIntelligenceServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ConversationIntelligenceService"
	handlerType := (*conversation_intelligence.ConversationIntelligenceService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "conversation_intelligence",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func createDigestJobHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*conversation_intelligence.ConversationIntelligenceServiceCreateDigestJobArgs)
	realResult := result.(*conversation_intelligence.ConversationIntelligenceServiceCreateDigestJobResult)
	success, err := handler.(conversation_intelligence.ConversationIntelligenceService).CreateDigestJob(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newConversationIntelligenceServiceCreateDigestJobArgs() interface{} {
	return conversation_intelligence.NewConversationIntelligenceServiceCreateDigestJobArgs()
}

func newConversationIntelligenceServiceCreateDigestJobResult() interface{} {
	return conversation_intelligence.NewConversationIntelligenceServiceCreateDigestJobResult()
}

func processDigestJobHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*conversation_intelligence.ConversationIntelligenceServiceProcessDigestJobArgs)
	realResult := result.(*conversation_intelligence.ConversationIntelligenceServiceProcessDigestJobResult)
	success, err := handler.(conversation_intelligence.ConversationIntelligenceService).ProcessDigestJob(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newConversationIntelligenceServiceProcessDigestJobArgs() interface{} {
	return conversation_intelligence.NewConversationIntelligenceServiceProcessDigestJobArgs()
}

func newConversationIntelligenceServiceProcessDigestJobResult() interface{} {
	return conversation_intelligence.NewConversationIntelligenceServiceProcessDigestJobResult()
}

func listArtifactsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*conversation_intelligence.ConversationIntelligenceServiceListArtifactsArgs)
	realResult := result.(*conversation_intelligence.ConversationIntelligenceServiceListArtifactsResult)
	success, err := handler.(conversation_intelligence.ConversationIntelligenceService).ListArtifacts(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newConversationIntelligenceServiceListArtifactsArgs() interface{} {
	return conversation_intelligence.NewConversationIntelligenceServiceListArtifactsArgs()
}

func newConversationIntelligenceServiceListArtifactsResult() interface{} {
	return conversation_intelligence.NewConversationIntelligenceServiceListArtifactsResult()
}

func listDigestJobsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*conversation_intelligence.ConversationIntelligenceServiceListDigestJobsArgs)
	realResult := result.(*conversation_intelligence.ConversationIntelligenceServiceListDigestJobsResult)
	success, err := handler.(conversation_intelligence.ConversationIntelligenceService).ListDigestJobs(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newConversationIntelligenceServiceListDigestJobsArgs() interface{} {
	return conversation_intelligence.NewConversationIntelligenceServiceListDigestJobsArgs()
}

func newConversationIntelligenceServiceListDigestJobsResult() interface{} {
	return conversation_intelligence.NewConversationIntelligenceServiceListDigestJobsResult()
}

func retryDigestJobHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*conversation_intelligence.ConversationIntelligenceServiceRetryDigestJobArgs)
	realResult := result.(*conversation_intelligence.ConversationIntelligenceServiceRetryDigestJobResult)
	success, err := handler.(conversation_intelligence.ConversationIntelligenceService).RetryDigestJob(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newConversationIntelligenceServiceRetryDigestJobArgs() interface{} {
	return conversation_intelligence.NewConversationIntelligenceServiceRetryDigestJobArgs()
}

func newConversationIntelligenceServiceRetryDigestJobResult() interface{} {
	return conversation_intelligence.NewConversationIntelligenceServiceRetryDigestJobResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateDigestJob(ctx context.Context, req *conversation_intelligence.CreateDigestJobReq) (r *conversation_intelligence.CreateDigestJobResp, err error) {
	var _args conversation_intelligence.ConversationIntelligenceServiceCreateDigestJobArgs
	_args.Req = req
	var _result conversation_intelligence.ConversationIntelligenceServiceCreateDigestJobResult
	if err = p.c.Call(ctx, "CreateDigestJob", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ProcessDigestJob(ctx context.Context, req *conversation_intelligence.ProcessDigestJobReq) (r *conversation_intelligence.ProcessDigestJobResp, err error) {
	var _args conversation_intelligence.ConversationIntelligenceServiceProcessDigestJobArgs
	_args.Req = req
	var _result conversation_intelligence.ConversationIntelligenceServiceProcessDigestJobResult
	if err = p.c.Call(ctx, "ProcessDigestJob", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListArtifacts(ctx context.Context, req *conversation_intelligence.ListArtifactsReq) (r *conversation_intelligence.ListArtifactsResp, err error) {
	var _args conversation_intelligence.ConversationIntelligenceServiceListArtifactsArgs
	_args.Req = req
	var _result conversation_intelligence.ConversationIntelligenceServiceListArtifactsResult
	if err = p.c.Call(ctx, "ListArtifacts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListDigestJobs(ctx context.Context, req *conversation_intelligence.ListDigestJobsReq) (r *conversation_intelligence.ListDigestJobsResp, err error) {
	var _args conversation_intelligence.ConversationIntelligenceServiceListDigestJobsArgs
	_args.Req = req
	var _result conversation_intelligence.ConversationIntelligenceServiceListDigestJobsResult
	if err = p.c.Call(ctx, "ListDigestJobs", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RetryDigestJob(ctx context.Context, req *conversation_intelligence.RetryDigestJobReq) (r *conversation_intelligence.RetryDigestJobResp, err error) {
	var _args conversation_intelligence.ConversationIntelligenceServiceRetryDigestJobArgs
	_args.Req = req
	var _result conversation_intelligence.ConversationIntelligenceServiceRetryDigestJobResult
	if err = p.c.Call(ctx, "RetryDigestJob", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
