// Code generated by Kitex v0.12.3. DO NOT EDIT.

package mcpgatewayservice

import (
	mcp_gateway "ClaranAIM/kitex_gen/mcp_gateway"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListTools": kitex.NewMethodInfo(
		listToolsHandler,
		newMCPGatewayServiceListToolsArgs,
		newMCPGatewayServiceListToolsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CallTool": kitex.NewMethodInfo(
		callToolHandler,
		newMCPGatewayServiceCallToolArgs,
		newMCPGatewayServiceCallToolResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetToolSchema": kitex.NewMethodInfo(
		getToolSchemaHandler,
		newMCPGatewayServiceGetToolSchemaArgs,
		newMCPGatewayServiceGetToolSchemaResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListToolCalls": kitex.NewMethodInfo(
		listToolCallsHandler,
		newMCPGatewayServiceListToolCallsArgs,
		newMCPGatewayServiceListToolCallsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetToolCallTrace": kitex.NewMethodInfo(
		getToolCallTraceHandler,
		newMCPGatewayServiceGetToolCallTraceArgs,
		newMCPGatewayServiceGetToolCallTraceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	mCPGatewayServiceServiceInfo                = NewServiceInfo()
	mCPGatewayServiceServiceInfoForClient       = NewServiceInfoForClient()
	mCPGatewayServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return mCPGatewayServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return mCPGatewayServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return mCPGatewayServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "MCPGatewayService"
	handlerType := (*mcp_gateway.MCPGatewayService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "mcp_gateway",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func listToolsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*mcp_gateway.MCPGatewayServiceListToolsArgs)
	realResult := result.(*mcp_gateway.MCPGatewayServiceListToolsResult)
	success, err := handler.(mcp_gateway.MCPGatewayService).ListTools(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMCPGatewayServiceListToolsArgs() interface{} {
	return mcp_gateway.NewMCPGatewayServiceListToolsArgs()
}

func newMCPGatewayServiceListToolsResult() interface{} {
	return mcp_gateway.NewMCPGatewayServiceListToolsResult()
}

func callToolHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*mcp_gateway.MCPGatewayServiceCallToolArgs)
	realResult := result.(*mcp_gateway.MCPGatewayServiceCallToolResult)
	success, err := handler.(mcp_gateway.MCPGatewayService).CallTool(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMCPGatewayServiceCallToolArgs() interface{} {
	return mcp_gateway.NewMCPGatewayServiceCallToolArgs()
}

func newMCPGatewayServiceCallToolResult() interface{} {
	return mcp_gateway.NewMCPGatewayServiceCallToolResult()
}

func getToolSchemaHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*mcp_gateway.MCPGatewayServiceGetToolSchemaArgs)
	realResult := result.(*mcp_gateway.MCPGatewayServiceGetToolSchemaResult)
	success, err := handler.(mcp_gateway.MCPGatewayService).GetToolSchema(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMCPGatewayServiceGetToolSchemaArgs() interface{} {
	return mcp_gateway.NewMCPGatewayServiceGetToolSchemaArgs()
}

func newMCPGatewayServiceGetToolSchemaResult() interface{} {
	return mcp_gateway.NewMCPGatewayServiceGetToolSchemaResult()
}

func listToolCallsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*mcp_gateway.MCPGatewayServiceListToolCallsArgs)
	realResult := result.(*mcp_gateway.MCPGatewayServiceListToolCallsResult)
	success, err := handler.(mcp_gateway.MCPGatewayService).ListToolCalls(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMCPGatewayServiceListToolCallsArgs() interface{} {
	return mcp_gateway.NewMCPGatewayServiceListToolCallsArgs()
}

func newMCPGatewayServiceListToolCallsResult() interface{} {
	return mcp_gateway.NewMCPGatewayServiceListToolCallsResult()
}

func getToolCallTraceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*mcp_gateway.MCPGatewayServiceGetToolCallTraceArgs)
	realResult := result.(*mcp_gateway.MCPGatewayServiceGetToolCallTraceResult)
	success, err := handler.(mcp_gateway.MCPGatewayService).GetToolCallTrace(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMCPGatewayServiceGetToolCallTraceArgs() interface{} {
	return mcp_gateway.NewMCPGatewayServiceGetToolCallTraceArgs()
}

func newMCPGatewayServiceGetToolCallTraceResult() interface{} {
	return mcp_gateway.NewMCPGatewayServiceGetToolCallTraceResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListTools(ctx context.Context, req *mcp_gateway.ListToolsReq) (r *mcp_gateway.ListToolsResp, err error) {
	var _args mcp_gateway.MCPGatewayServiceListToolsArgs
	_args.Req = req
	var _result mcp_gateway.MCPGatewayServiceListToolsResult
	if err = p.c.Call(ctx, "ListTools", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CallTool(ctx context.Context, req *mcp_gateway.CallToolReq) (r *mcp_gateway.CallToolResp, err error) {
	var _args mcp_gateway.MCPGatewayServiceCallToolArgs
	_args.Req = req
	var _result mcp_gateway.MCPGatewayServiceCallToolResult
	if err = p.c.Call(ctx, "CallTool", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetToolSchema(ctx context.Context, req *mcp_gateway.GetToolSchemaReq) (r *mcp_gateway.GetToolSchemaResp, err error) {
	var _args mcp_gateway.MCPGatewayServiceGetToolSchemaArgs
	_args.Req = req
	var _result mcp_gateway.MCPGatewayServiceGetToolSchemaResult
	if err = p.c.Call(ctx, "GetToolSchema", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListToolCalls(ctx context.Context, req *mcp_gateway.ListToolCallsReq) (r *mcp_gateway.ListToolCallsResp, err error) {
	var _args mcp_gateway.MCPGatewayServiceListToolCallsArgs
	_args.Req = req
	var _result mcp_gateway.MCPGatewayServiceListToolCallsResult
	if err = p.c.Call(ctx, "ListToolCalls", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetToolCallTrace(ctx context.Context, req *mcp_gateway.GetToolCallTraceReq) (r *mcp_gateway.GetToolCallTraceResp, err error) {
	var _args mcp_gateway.MCPGatewayServiceGetToolCallTraceArgs
	_args.Req = req
	var _result mcp_gateway.MCPGatewayServiceGetToolCallTraceResult
	if err = p.c.Call(ctx, "GetToolCallTrace", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
