apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Jaeger
    uid: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
  - name: Elasticsearch
    uid: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://host.docker.internal:9200
    jsonData:
      index: claran-services-*
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: level
      esVersion: "8.0.0"
