service:
  name: "file-service"
  address: "127.0.0.1:9005"

mysql:
  dsn: ""

redis:
  addr: ""
  password: ""
  db: 0

jwt:
  secret_key: ""
  expiration: 0

etcd:
  endpoints: []

minio:
  endpoint: ""
  access_key: ""
  secret_key: ""
  bucket: "claranaim"
  use_minio: false

storage:
  dir: "./storage"

governance:
  rpc:
    timeout_ms: 5000
    circuit_breaker: true
    max_connections: 1000
    max_qps: 1000
