// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package knowledge

import (
	"context"
	"fmt"
)

type KnowledgeGraphNode struct {
	Id          int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name        string  `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Type        string  `thrift:"type,3" frugal:"3,default,string" json:"type"`
	Summary     string  `thrift:"summary,4" frugal:"4,default,string" json:"summary"`
	CommunityId int64   `thrift:"community_id,5" frugal:"5,default,i64" json:"community_id"`
	Score       float64 `thrift:"score,6" frugal:"6,default,double" json:"score"`
	Degree      int64   `thrift:"degree,7" frugal:"7,default,i64" json:"degree"`
	Size        float64 `thrift:"size,8" frugal:"8,default,double" json:"size"`
	Color       string  `thrift:"color,9" frugal:"9,default,string" json:"color"`
}

func NewKnowledgeGraphNode() *KnowledgeGraphNode {
	return &KnowledgeGraphNode{}
}

func (p *KnowledgeGraphNode) InitDefault() {
}

func (p *KnowledgeGraphNode) GetId() (v int64) {
	return p.Id
}

func (p *KnowledgeGraphNode) GetName() (v string) {
	return p.Name
}

func (p *KnowledgeGraphNode) GetType() (v string) {
	return p.Type
}

func (p *KnowledgeGraphNode) GetSummary() (v string) {
	return p.Summary
}

func (p *KnowledgeGraphNode) GetCommunityId() (v int64) {
	return p.CommunityId
}

func (p *KnowledgeGraphNode) GetScore() (v float64) {
	return p.Score
}

func (p *KnowledgeGraphNode) GetDegree() (v int64) {
	return p.Degree
}

func (p *KnowledgeGraphNode) GetSize() (v float64) {
	return p.Size
}

func (p *KnowledgeGraphNode) GetColor() (v string) {
	return p.Color
}
func (p *KnowledgeGraphNode) SetId(val int64) {
	p.Id = val
}
func (p *KnowledgeGraphNode) SetName(val string) {
	p.Name = val
}
func (p *KnowledgeGraphNode) SetType(val string) {
	p.Type = val
}
func (p *KnowledgeGraphNode) SetSummary(val string) {
	p.Summary = val
}
func (p *KnowledgeGraphNode) SetCommunityId(val int64) {
	p.CommunityId = val
}
func (p *KnowledgeGraphNode) SetScore(val float64) {
	p.Score = val
}
func (p *KnowledgeGraphNode) SetDegree(val int64) {
	p.Degree = val
}
func (p *KnowledgeGraphNode) SetSize(val float64) {
	p.Size = val
}
func (p *KnowledgeGraphNode) SetColor(val string) {
	p.Color = val
}

func (p *KnowledgeGraphNode) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeGraphNode(%+v)", *p)
}

var fieldIDToName_KnowledgeGraphNode = map[int16]string{
	1: "id",
	2: "name",
	3: "type",
	4: "summary",
	5: "community_id",
	6: "score",
	7: "degree",
	8: "size",
	9: "color",
}

type KnowledgeGraphEdge struct {
	Id          int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	SourceId    int64   `thrift:"source_id,2" frugal:"2,default,i64" json:"source_id"`
	TargetId    int64   `thrift:"target_id,3" frugal:"3,default,i64" json:"target_id"`
	Relation    string  `thrift:"relation,4" frugal:"4,default,string" json:"relation"`
	Description string  `thrift:"description,5" frugal:"5,default,string" json:"description"`
	Weight      float64 `thrift:"weight,6" frugal:"6,default,double" json:"weight"`
	Evidence    string  `thrift:"evidence,7" frugal:"7,default,string" json:"evidence"`
	Color       string  `thrift:"color,8" frugal:"8,default,string" json:"color"`
}

func NewKnowledgeGraphEdge() *KnowledgeGraphEdge {
	return &KnowledgeGraphEdge{}
}

func (p *KnowledgeGraphEdge) InitDefault() {
}

func (p *KnowledgeGraphEdge) GetId() (v int64) {
	return p.Id
}

func (p *KnowledgeGraphEdge) GetSourceId() (v int64) {
	return p.SourceId
}

func (p *KnowledgeGraphEdge) GetTargetId() (v int64) {
	return p.TargetId
}

func (p *KnowledgeGraphEdge) GetRelation() (v string) {
	return p.Relation
}

func (p *KnowledgeGraphEdge) GetDescription() (v string) {
	return p.Description
}

func (p *KnowledgeGraphEdge) GetWeight() (v float64) {
	return p.Weight
}

func (p *KnowledgeGraphEdge) GetEvidence() (v string) {
	return p.Evidence
}

func (p *KnowledgeGraphEdge) GetColor() (v string) {
	return p.Color
}
func (p *KnowledgeGraphEdge) SetId(val int64) {
	p.Id = val
}
func (p *KnowledgeGraphEdge) SetSourceId(val int64) {
	p.SourceId = val
}
func (p *KnowledgeGraphEdge) SetTargetId(val int64) {
	p.TargetId = val
}
func (p *KnowledgeGraphEdge) SetRelation(val string) {
	p.Relation = val
}
func (p *KnowledgeGraphEdge) SetDescription(val string) {
	p.Description = val
}
func (p *KnowledgeGraphEdge) SetWeight(val float64) {
	p.Weight = val
}
func (p *KnowledgeGraphEdge) SetEvidence(val string) {
	p.Evidence = val
}
func (p *KnowledgeGraphEdge) SetColor(val string) {
	p.Color = val
}

func (p *KnowledgeGraphEdge) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeGraphEdge(%+v)", *p)
}

var fieldIDToName_KnowledgeGraphEdge = map[int16]string{
	1: "id",
	2: "source_id",
	3: "target_id",
	4: "relation",
	5: "description",
	6: "weight",
	7: "evidence",
	8: "color",
}

type KnowledgeGraphCommunity struct {
	Id      int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name    string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Summary string `thrift:"summary,3" frugal:"3,default,string" json:"summary"`
	Level   int64  `thrift:"level,4" frugal:"4,default,i64" json:"level"`
	Color   string `thrift:"color,5" frugal:"5,default,string" json:"color"`
}

func NewKnowledgeGraphCommunity() *KnowledgeGraphCommunity {
	return &KnowledgeGraphCommunity{}
}

func (p *KnowledgeGraphCommunity) InitDefault() {
}

func (p *KnowledgeGraphCommunity) GetId() (v int64) {
	return p.Id
}

func (p *KnowledgeGraphCommunity) GetName() (v string) {
	return p.Name
}

func (p *KnowledgeGraphCommunity) GetSummary() (v string) {
	return p.Summary
}

func (p *KnowledgeGraphCommunity) GetLevel() (v int64) {
	return p.Level
}

func (p *KnowledgeGraphCommunity) GetColor() (v string) {
	return p.Color
}
func (p *KnowledgeGraphCommunity) SetId(val int64) {
	p.Id = val
}
func (p *KnowledgeGraphCommunity) SetName(val string) {
	p.Name = val
}
func (p *KnowledgeGraphCommunity) SetSummary(val string) {
	p.Summary = val
}
func (p *KnowledgeGraphCommunity) SetLevel(val int64) {
	p.Level = val
}
func (p *KnowledgeGraphCommunity) SetColor(val string) {
	p.Color = val
}

func (p *KnowledgeGraphCommunity) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeGraphCommunity(%+v)", *p)
}

var fieldIDToName_KnowledgeGraphCommunity = map[int16]string{
	1: "id",
	2: "name",
	3: "summary",
	4: "level",
	5: "color",
}

type KnowledgeGraphStats struct {
	NodeCount      int64    `thrift:"node_count,1" frugal:"1,default,i64" json:"node_count"`
	EdgeCount      int64    `thrift:"edge_count,2" frugal:"2,default,i64" json:"edge_count"`
	CommunityCount int64    `thrift:"community_count,3" frugal:"3,default,i64" json:"community_count"`
	Types          []string `thrift:"types,4" frugal:"4,default,list<string>" json:"types"`
	Relations      []string `thrift:"relations,5" frugal:"5,default,list<string>" json:"relations"`
}

func NewKnowledgeGraphStats() *KnowledgeGraphStats {
	return &KnowledgeGraphStats{}
}

func (p *KnowledgeGraphStats) InitDefault() {
}

func (p *KnowledgeGraphStats) GetNodeCount() (v int64) {
	return p.NodeCount
}

func (p *KnowledgeGraphStats) GetEdgeCount() (v int64) {
	return p.EdgeCount
}

func (p *KnowledgeGraphStats) GetCommunityCount() (v int64) {
	return p.CommunityCount
}

func (p *KnowledgeGraphStats) GetTypes() (v []string) {
	return p.Types
}

func (p *KnowledgeGraphStats) GetRelations() (v []string) {
	return p.Relations
}
func (p *KnowledgeGraphStats) SetNodeCount(val int64) {
	p.NodeCount = val
}
func (p *KnowledgeGraphStats) SetEdgeCount(val int64) {
	p.EdgeCount = val
}
func (p *KnowledgeGraphStats) SetCommunityCount(val int64) {
	p.CommunityCount = val
}
func (p *KnowledgeGraphStats) SetTypes(val []string) {
	p.Types = val
}
func (p *KnowledgeGraphStats) SetRelations(val []string) {
	p.Relations = val
}

func (p *KnowledgeGraphStats) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeGraphStats(%+v)", *p)
}

var fieldIDToName_KnowledgeGraphStats = map[int16]string{
	1: "node_count",
	2: "edge_count",
	3: "community_count",
	4: "types",
	5: "relations",
}

type KnowledgeGraphReq struct {
	ViewerId        int64    `thrift:"viewer_id,1" frugal:"1,default,i64" json:"viewer_id"`
	Query           string   `thrift:"query,2" frugal:"2,default,string" json:"query"`
	TypeFilters     []string `thrift:"type_filters,3" frugal:"3,default,list<string>" json:"type_filters"`
	RelationFilters []string `thrift:"relation_filters,4" frugal:"4,default,list<string>" json:"relation_filters"`
	CommunityId     int64    `thrift:"community_id,5" frugal:"5,default,i64" json:"community_id"`
	Hops            int64    `thrift:"hops,6" frugal:"6,default,i64" json:"hops"`
	Limit           int64    `thrift:"limit,7" frugal:"7,default,i64" json:"limit"`
}

func NewKnowledgeGraphReq() *KnowledgeGraphReq {
	return &KnowledgeGraphReq{}
}

func (p *KnowledgeGraphReq) InitDefault() {
}

func (p *KnowledgeGraphReq) GetViewerId() (v int64) {
	return p.ViewerId
}

func (p *KnowledgeGraphReq) GetQuery() (v string) {
	return p.Query
}

func (p *KnowledgeGraphReq) GetTypeFilters() (v []string) {
	return p.TypeFilters
}

func (p *KnowledgeGraphReq) GetRelationFilters() (v []string) {
	return p.RelationFilters
}

func (p *KnowledgeGraphReq) GetCommunityId() (v int64) {
	return p.CommunityId
}

func (p *KnowledgeGraphReq) GetHops() (v int64) {
	return p.Hops
}

func (p *KnowledgeGraphReq) GetLimit() (v int64) {
	return p.Limit
}
func (p *KnowledgeGraphReq) SetViewerId(val int64) {
	p.ViewerId = val
}
func (p *KnowledgeGraphReq) SetQuery(val string) {
	p.Query = val
}
func (p *KnowledgeGraphReq) SetTypeFilters(val []string) {
	p.TypeFilters = val
}
func (p *KnowledgeGraphReq) SetRelationFilters(val []string) {
	p.RelationFilters = val
}
func (p *KnowledgeGraphReq) SetCommunityId(val int64) {
	p.CommunityId = val
}
func (p *KnowledgeGraphReq) SetHops(val int64) {
	p.Hops = val
}
func (p *KnowledgeGraphReq) SetLimit(val int64) {
	p.Limit = val
}

func (p *KnowledgeGraphReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeGraphReq(%+v)", *p)
}

var fieldIDToName_KnowledgeGraphReq = map[int16]string{
	1: "viewer_id",
	2: "query",
	3: "type_filters",
	4: "relation_filters",
	5: "community_id",
	6: "hops",
	7: "limit",
}

type KnowledgeGraphResp struct {
	Success     bool                       `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Nodes       []*KnowledgeGraphNode      `thrift:"nodes,2" frugal:"2,default,list<KnowledgeGraphNode>" json:"nodes"`
	Edges       []*KnowledgeGraphEdge      `thrift:"edges,3" frugal:"3,default,list<KnowledgeGraphEdge>" json:"edges"`
	Communities []*KnowledgeGraphCommunity `thrift:"communities,4" frugal:"4,default,list<KnowledgeGraphCommunity>" json:"communities"`
	Stats       *KnowledgeGraphStats       `thrift:"stats,5" frugal:"5,default,KnowledgeGraphStats" json:"stats"`
	Msg         string                     `thrift:"msg,6" frugal:"6,default,string" json:"msg"`
}

func NewKnowledgeGraphResp() *KnowledgeGraphResp {
	return &KnowledgeGraphResp{}
}

func (p *KnowledgeGraphResp) InitDefault() {
}

func (p *KnowledgeGraphResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *KnowledgeGraphResp) GetNodes() (v []*KnowledgeGraphNode) {
	return p.Nodes
}

func (p *KnowledgeGraphResp) GetEdges() (v []*KnowledgeGraphEdge) {
	return p.Edges
}

func (p *KnowledgeGraphResp) GetCommunities() (v []*KnowledgeGraphCommunity) {
	return p.Communities
}

var KnowledgeGraphResp_Stats_DEFAULT *KnowledgeGraphStats

func (p *KnowledgeGraphResp) GetStats() (v *KnowledgeGraphStats) {
	if !p.IsSetStats() {
		return KnowledgeGraphResp_Stats_DEFAULT
	}
	return p.Stats
}

func (p *KnowledgeGraphResp) GetMsg() (v string) {
	return p.Msg
}
func (p *KnowledgeGraphResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *KnowledgeGraphResp) SetNodes(val []*KnowledgeGraphNode) {
	p.Nodes = val
}
func (p *KnowledgeGraphResp) SetEdges(val []*KnowledgeGraphEdge) {
	p.Edges = val
}
func (p *KnowledgeGraphResp) SetCommunities(val []*KnowledgeGraphCommunity) {
	p.Communities = val
}
func (p *KnowledgeGraphResp) SetStats(val *KnowledgeGraphStats) {
	p.Stats = val
}
func (p *KnowledgeGraphResp) SetMsg(val string) {
	p.Msg = val
}

func (p *KnowledgeGraphResp) IsSetStats() bool {
	return p.Stats != nil
}

func (p *KnowledgeGraphResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeGraphResp(%+v)", *p)
}

var fieldIDToName_KnowledgeGraphResp = map[int16]string{
	1: "success",
	2: "nodes",
	3: "edges",
	4: "communities",
	5: "stats",
	6: "msg",
}

type KnowledgeNodeDetailReq struct {
	ViewerId int64  `thrift:"viewer_id,1" frugal:"1,default,i64" json:"viewer_id"`
	NodeId   int64  `thrift:"node_id,2" frugal:"2,default,i64" json:"node_id"`
	Query    string `thrift:"query,3" frugal:"3,default,string" json:"query"`
	Limit    int64  `thrift:"limit,4" frugal:"4,default,i64" json:"limit"`
}

func NewKnowledgeNodeDetailReq() *KnowledgeNodeDetailReq {
	return &KnowledgeNodeDetailReq{}
}

func (p *KnowledgeNodeDetailReq) InitDefault() {
}

func (p *KnowledgeNodeDetailReq) GetViewerId() (v int64) {
	return p.ViewerId
}

func (p *KnowledgeNodeDetailReq) GetNodeId() (v int64) {
	return p.NodeId
}

func (p *KnowledgeNodeDetailReq) GetQuery() (v string) {
	return p.Query
}

func (p *KnowledgeNodeDetailReq) GetLimit() (v int64) {
	return p.Limit
}
func (p *KnowledgeNodeDetailReq) SetViewerId(val int64) {
	p.ViewerId = val
}
func (p *KnowledgeNodeDetailReq) SetNodeId(val int64) {
	p.NodeId = val
}
func (p *KnowledgeNodeDetailReq) SetQuery(val string) {
	p.Query = val
}
func (p *KnowledgeNodeDetailReq) SetLimit(val int64) {
	p.Limit = val
}

func (p *KnowledgeNodeDetailReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeNodeDetailReq(%+v)", *p)
}

var fieldIDToName_KnowledgeNodeDetailReq = map[int16]string{
	1: "viewer_id",
	2: "node_id",
	3: "query",
	4: "limit",
}

type KnowledgeNodeDetailResp struct {
	Success   bool                  `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Node      *KnowledgeGraphNode   `thrift:"node,2" frugal:"2,default,KnowledgeGraphNode" json:"node"`
	Relations []*KnowledgeGraphEdge `thrift:"relations,3" frugal:"3,default,list<KnowledgeGraphEdge>" json:"relations"`
	Neighbors []*KnowledgeGraphNode `thrift:"neighbors,4" frugal:"4,default,list<KnowledgeGraphNode>" json:"neighbors"`
	Msg       string                `thrift:"msg,5" frugal:"5,default,string" json:"msg"`
}

func NewKnowledgeNodeDetailResp() *KnowledgeNodeDetailResp {
	return &KnowledgeNodeDetailResp{}
}

func (p *KnowledgeNodeDetailResp) InitDefault() {
}

func (p *KnowledgeNodeDetailResp) GetSuccess() (v bool) {
	return p.Success
}

var KnowledgeNodeDetailResp_Node_DEFAULT *KnowledgeGraphNode

func (p *KnowledgeNodeDetailResp) GetNode() (v *KnowledgeGraphNode) {
	if !p.IsSetNode() {
		return KnowledgeNodeDetailResp_Node_DEFAULT
	}
	return p.Node
}

func (p *KnowledgeNodeDetailResp) GetRelations() (v []*KnowledgeGraphEdge) {
	return p.Relations
}

func (p *KnowledgeNodeDetailResp) GetNeighbors() (v []*KnowledgeGraphNode) {
	return p.Neighbors
}

func (p *KnowledgeNodeDetailResp) GetMsg() (v string) {
	return p.Msg
}
func (p *KnowledgeNodeDetailResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *KnowledgeNodeDetailResp) SetNode(val *KnowledgeGraphNode) {
	p.Node = val
}
func (p *KnowledgeNodeDetailResp) SetRelations(val []*KnowledgeGraphEdge) {
	p.Relations = val
}
func (p *KnowledgeNodeDetailResp) SetNeighbors(val []*KnowledgeGraphNode) {
	p.Neighbors = val
}
func (p *KnowledgeNodeDetailResp) SetMsg(val string) {
	p.Msg = val
}

func (p *KnowledgeNodeDetailResp) IsSetNode() bool {
	return p.Node != nil
}

func (p *KnowledgeNodeDetailResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeNodeDetailResp(%+v)", *p)
}

var fieldIDToName_KnowledgeNodeDetailResp = map[int16]string{
	1: "success",
	2: "node",
	3: "relations",
	4: "neighbors",
	5: "msg",
}

type KnowledgeEdgeDetailReq struct {
	ViewerId int64  `thrift:"viewer_id,1" frugal:"1,default,i64" json:"viewer_id"`
	EdgeId   int64  `thrift:"edge_id,2" frugal:"2,default,i64" json:"edge_id"`
	Query    string `thrift:"query,3" frugal:"3,default,string" json:"query"`
	Limit    int64  `thrift:"limit,4" frugal:"4,default,i64" json:"limit"`
}

func NewKnowledgeEdgeDetailReq() *KnowledgeEdgeDetailReq {
	return &KnowledgeEdgeDetailReq{}
}

func (p *KnowledgeEdgeDetailReq) InitDefault() {
}

func (p *KnowledgeEdgeDetailReq) GetViewerId() (v int64) {
	return p.ViewerId
}

func (p *KnowledgeEdgeDetailReq) GetEdgeId() (v int64) {
	return p.EdgeId
}

func (p *KnowledgeEdgeDetailReq) GetQuery() (v string) {
	return p.Query
}

func (p *KnowledgeEdgeDetailReq) GetLimit() (v int64) {
	return p.Limit
}
func (p *KnowledgeEdgeDetailReq) SetViewerId(val int64) {
	p.ViewerId = val
}
func (p *KnowledgeEdgeDetailReq) SetEdgeId(val int64) {
	p.EdgeId = val
}
func (p *KnowledgeEdgeDetailReq) SetQuery(val string) {
	p.Query = val
}
func (p *KnowledgeEdgeDetailReq) SetLimit(val int64) {
	p.Limit = val
}

func (p *KnowledgeEdgeDetailReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeEdgeDetailReq(%+v)", *p)
}

var fieldIDToName_KnowledgeEdgeDetailReq = map[int16]string{
	1: "viewer_id",
	2: "edge_id",
	3: "query",
	4: "limit",
}

type KnowledgeEdgeDetailResp struct {
	Success bool                `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Edge    *KnowledgeGraphEdge `thrift:"edge,2" frugal:"2,default,KnowledgeGraphEdge" json:"edge"`
	Source  *KnowledgeGraphNode `thrift:"source,3" frugal:"3,default,KnowledgeGraphNode" json:"source"`
	Target  *KnowledgeGraphNode `thrift:"target,4" frugal:"4,default,KnowledgeGraphNode" json:"target"`
	Msg     string              `thrift:"msg,5" frugal:"5,default,string" json:"msg"`
}

func NewKnowledgeEdgeDetailResp() *KnowledgeEdgeDetailResp {
	return &KnowledgeEdgeDetailResp{}
}

func (p *KnowledgeEdgeDetailResp) InitDefault() {
}

func (p *KnowledgeEdgeDetailResp) GetSuccess() (v bool) {
	return p.Success
}

var KnowledgeEdgeDetailResp_Edge_DEFAULT *KnowledgeGraphEdge

func (p *KnowledgeEdgeDetailResp) GetEdge() (v *KnowledgeGraphEdge) {
	if !p.IsSetEdge() {
		return KnowledgeEdgeDetailResp_Edge_DEFAULT
	}
	return p.Edge
}

var KnowledgeEdgeDetailResp_Source_DEFAULT *KnowledgeGraphNode

func (p *KnowledgeEdgeDetailResp) GetSource() (v *KnowledgeGraphNode) {
	if !p.IsSetSource() {
		return KnowledgeEdgeDetailResp_Source_DEFAULT
	}
	return p.Source
}

var KnowledgeEdgeDetailResp_Target_DEFAULT *KnowledgeGraphNode

func (p *KnowledgeEdgeDetailResp) GetTarget() (v *KnowledgeGraphNode) {
	if !p.IsSetTarget() {
		return KnowledgeEdgeDetailResp_Target_DEFAULT
	}
	return p.Target
}

func (p *KnowledgeEdgeDetailResp) GetMsg() (v string) {
	return p.Msg
}
func (p *KnowledgeEdgeDetailResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *KnowledgeEdgeDetailResp) SetEdge(val *KnowledgeGraphEdge) {
	p.Edge = val
}
func (p *KnowledgeEdgeDetailResp) SetSource(val *KnowledgeGraphNode) {
	p.Source = val
}
func (p *KnowledgeEdgeDetailResp) SetTarget(val *KnowledgeGraphNode) {
	p.Target = val
}
func (p *KnowledgeEdgeDetailResp) SetMsg(val string) {
	p.Msg = val
}

func (p *KnowledgeEdgeDetailResp) IsSetEdge() bool {
	return p.Edge != nil
}

func (p *KnowledgeEdgeDetailResp) IsSetSource() bool {
	return p.Source != nil
}

func (p *KnowledgeEdgeDetailResp) IsSetTarget() bool {
	return p.Target != nil
}

func (p *KnowledgeEdgeDetailResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeEdgeDetailResp(%+v)", *p)
}

var fieldIDToName_KnowledgeEdgeDetailResp = map[int16]string{
	1: "success",
	2: "edge",
	3: "source",
	4: "target",
	5: "msg",
}

type KnowledgeNeighborhoodReq struct {
	ViewerId        int64    `thrift:"viewer_id,1" frugal:"1,default,i64" json:"viewer_id"`
	NodeId          int64    `thrift:"node_id,2" frugal:"2,default,i64" json:"node_id"`
	Query           string   `thrift:"query,3" frugal:"3,default,string" json:"query"`
	TypeFilters     []string `thrift:"type_filters,4" frugal:"4,default,list<string>" json:"type_filters"`
	RelationFilters []string `thrift:"relation_filters,5" frugal:"5,default,list<string>" json:"relation_filters"`
	CommunityId     int64    `thrift:"community_id,6" frugal:"6,default,i64" json:"community_id"`
	Hops            int64    `thrift:"hops,7" frugal:"7,default,i64" json:"hops"`
	Limit           int64    `thrift:"limit,8" frugal:"8,default,i64" json:"limit"`
}

func NewKnowledgeNeighborhoodReq() *KnowledgeNeighborhoodReq {
	return &KnowledgeNeighborhoodReq{}
}

func (p *KnowledgeNeighborhoodReq) InitDefault() {
}

func (p *KnowledgeNeighborhoodReq) GetViewerId() (v int64) {
	return p.ViewerId
}

func (p *KnowledgeNeighborhoodReq) GetNodeId() (v int64) {
	return p.NodeId
}

func (p *KnowledgeNeighborhoodReq) GetQuery() (v string) {
	return p.Query
}

func (p *KnowledgeNeighborhoodReq) GetTypeFilters() (v []string) {
	return p.TypeFilters
}

func (p *KnowledgeNeighborhoodReq) GetRelationFilters() (v []string) {
	return p.RelationFilters
}

func (p *KnowledgeNeighborhoodReq) GetCommunityId() (v int64) {
	return p.CommunityId
}

func (p *KnowledgeNeighborhoodReq) GetHops() (v int64) {
	return p.Hops
}

func (p *KnowledgeNeighborhoodReq) GetLimit() (v int64) {
	return p.Limit
}
func (p *KnowledgeNeighborhoodReq) SetViewerId(val int64) {
	p.ViewerId = val
}
func (p *KnowledgeNeighborhoodReq) SetNodeId(val int64) {
	p.NodeId = val
}
func (p *KnowledgeNeighborhoodReq) SetQuery(val string) {
	p.Query = val
}
func (p *KnowledgeNeighborhoodReq) SetTypeFilters(val []string) {
	p.TypeFilters = val
}
func (p *KnowledgeNeighborhoodReq) SetRelationFilters(val []string) {
	p.RelationFilters = val
}
func (p *KnowledgeNeighborhoodReq) SetCommunityId(val int64) {
	p.CommunityId = val
}
func (p *KnowledgeNeighborhoodReq) SetHops(val int64) {
	p.Hops = val
}
func (p *KnowledgeNeighborhoodReq) SetLimit(val int64) {
	p.Limit = val
}

func (p *KnowledgeNeighborhoodReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeNeighborhoodReq(%+v)", *p)
}

var fieldIDToName_KnowledgeNeighborhoodReq = map[int16]string{
	1: "viewer_id",
	2: "node_id",
	3: "query",
	4: "type_filters",
	5: "relation_filters",
	6: "community_id",
	7: "hops",
	8: "limit",
}

type KnowledgePathReq struct {
	ViewerId int64  `thrift:"viewer_id,1" frugal:"1,default,i64" json:"viewer_id"`
	SourceId int64  `thrift:"source_id,2" frugal:"2,default,i64" json:"source_id"`
	TargetId int64  `thrift:"target_id,3" frugal:"3,default,i64" json:"target_id"`
	Query    string `thrift:"query,4" frugal:"4,default,string" json:"query"`
	Limit    int64  `thrift:"limit,5" frugal:"5,default,i64" json:"limit"`
}

func NewKnowledgePathReq() *KnowledgePathReq {
	return &KnowledgePathReq{}
}

func (p *KnowledgePathReq) InitDefault() {
}

func (p *KnowledgePathReq) GetViewerId() (v int64) {
	return p.ViewerId
}

func (p *KnowledgePathReq) GetSourceId() (v int64) {
	return p.SourceId
}

func (p *KnowledgePathReq) GetTargetId() (v int64) {
	return p.TargetId
}

func (p *KnowledgePathReq) GetQuery() (v string) {
	return p.Query
}

func (p *KnowledgePathReq) GetLimit() (v int64) {
	return p.Limit
}
func (p *KnowledgePathReq) SetViewerId(val int64) {
	p.ViewerId = val
}
func (p *KnowledgePathReq) SetSourceId(val int64) {
	p.SourceId = val
}
func (p *KnowledgePathReq) SetTargetId(val int64) {
	p.TargetId = val
}
func (p *KnowledgePathReq) SetQuery(val string) {
	p.Query = val
}
func (p *KnowledgePathReq) SetLimit(val int64) {
	p.Limit = val
}

func (p *KnowledgePathReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgePathReq(%+v)", *p)
}

var fieldIDToName_KnowledgePathReq = map[int16]string{
	1: "viewer_id",
	2: "source_id",
	3: "target_id",
	4: "query",
	5: "limit",
}

type KnowledgePathResp struct {
	Success bool                  `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Nodes   []*KnowledgeGraphNode `thrift:"nodes,2" frugal:"2,default,list<KnowledgeGraphNode>" json:"nodes"`
	Edges   []*KnowledgeGraphEdge `thrift:"edges,3" frugal:"3,default,list<KnowledgeGraphEdge>" json:"edges"`
	NodeIds []int64               `thrift:"node_ids,4" frugal:"4,default,list<i64>" json:"node_ids"`
	EdgeIds []int64               `thrift:"edge_ids,5" frugal:"5,default,list<i64>" json:"edge_ids"`
	Msg     string                `thrift:"msg,6" frugal:"6,default,string" json:"msg"`
}

func NewKnowledgePathResp() *KnowledgePathResp {
	return &KnowledgePathResp{}
}

func (p *KnowledgePathResp) InitDefault() {
}

func (p *KnowledgePathResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *KnowledgePathResp) GetNodes() (v []*KnowledgeGraphNode) {
	return p.Nodes
}

func (p *KnowledgePathResp) GetEdges() (v []*KnowledgeGraphEdge) {
	return p.Edges
}

func (p *KnowledgePathResp) GetNodeIds() (v []int64) {
	return p.NodeIds
}

func (p *KnowledgePathResp) GetEdgeIds() (v []int64) {
	return p.EdgeIds
}

func (p *KnowledgePathResp) GetMsg() (v string) {
	return p.Msg
}
func (p *KnowledgePathResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *KnowledgePathResp) SetNodes(val []*KnowledgeGraphNode) {
	p.Nodes = val
}
func (p *KnowledgePathResp) SetEdges(val []*KnowledgeGraphEdge) {
	p.Edges = val
}
func (p *KnowledgePathResp) SetNodeIds(val []int64) {
	p.NodeIds = val
}
func (p *KnowledgePathResp) SetEdgeIds(val []int64) {
	p.EdgeIds = val
}
func (p *KnowledgePathResp) SetMsg(val string) {
	p.Msg = val
}

func (p *KnowledgePathResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgePathResp(%+v)", *p)
}

var fieldIDToName_KnowledgePathResp = map[int16]string{
	1: "success",
	2: "nodes",
	3: "edges",
	4: "node_ids",
	5: "edge_ids",
	6: "msg",
}

type KnowledgeService interface {
	GetGraphView(ctx context.Context, req *KnowledgeGraphReq) (r *KnowledgeGraphResp, err error)

	GetNodeDetail(ctx context.Context, req *KnowledgeNodeDetailReq) (r *KnowledgeNodeDetailResp, err error)

	GetEdgeDetail(ctx context.Context, req *KnowledgeEdgeDetailReq) (r *KnowledgeEdgeDetailResp, err error)

	GetNeighborhood(ctx context.Context, req *KnowledgeNeighborhoodReq) (r *KnowledgeGraphResp, err error)

	GetPath(ctx context.Context, req *KnowledgePathReq) (r *KnowledgePathResp, err error)
}

type KnowledgeServiceGetGraphViewArgs struct {
	Req *KnowledgeGraphReq `thrift:"req,1" frugal:"1,default,KnowledgeGraphReq" json:"req"`
}

func NewKnowledgeServiceGetGraphViewArgs() *KnowledgeServiceGetGraphViewArgs {
	return &KnowledgeServiceGetGraphViewArgs{}
}

func (p *KnowledgeServiceGetGraphViewArgs) InitDefault() {
}

var KnowledgeServiceGetGraphViewArgs_Req_DEFAULT *KnowledgeGraphReq

func (p *KnowledgeServiceGetGraphViewArgs) GetReq() (v *KnowledgeGraphReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceGetGraphViewArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceGetGraphViewArgs) SetReq(val *KnowledgeGraphReq) {
	p.Req = val
}

func (p *KnowledgeServiceGetGraphViewArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceGetGraphViewArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetGraphViewArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetGraphViewArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceGetGraphViewResult struct {
	Success *KnowledgeGraphResp `thrift:"success,0,optional" frugal:"0,optional,KnowledgeGraphResp" json:"success,omitempty"`
}

func NewKnowledgeServiceGetGraphViewResult() *KnowledgeServiceGetGraphViewResult {
	return &KnowledgeServiceGetGraphViewResult{}
}

func (p *KnowledgeServiceGetGraphViewResult) InitDefault() {
}

var KnowledgeServiceGetGraphViewResult_Success_DEFAULT *KnowledgeGraphResp

func (p *KnowledgeServiceGetGraphViewResult) GetSuccess() (v *KnowledgeGraphResp) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceGetGraphViewResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceGetGraphViewResult) SetSuccess(x interface{}) {
	p.Success = x.(*KnowledgeGraphResp)
}

func (p *KnowledgeServiceGetGraphViewResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceGetGraphViewResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetGraphViewResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetGraphViewResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceGetNodeDetailArgs struct {
	Req *KnowledgeNodeDetailReq `thrift:"req,1" frugal:"1,default,KnowledgeNodeDetailReq" json:"req"`
}

func NewKnowledgeServiceGetNodeDetailArgs() *KnowledgeServiceGetNodeDetailArgs {
	return &KnowledgeServiceGetNodeDetailArgs{}
}

func (p *KnowledgeServiceGetNodeDetailArgs) InitDefault() {
}

var KnowledgeServiceGetNodeDetailArgs_Req_DEFAULT *KnowledgeNodeDetailReq

func (p *KnowledgeServiceGetNodeDetailArgs) GetReq() (v *KnowledgeNodeDetailReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceGetNodeDetailArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceGetNodeDetailArgs) SetReq(val *KnowledgeNodeDetailReq) {
	p.Req = val
}

func (p *KnowledgeServiceGetNodeDetailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceGetNodeDetailArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetNodeDetailArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetNodeDetailArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceGetNodeDetailResult struct {
	Success *KnowledgeNodeDetailResp `thrift:"success,0,optional" frugal:"0,optional,KnowledgeNodeDetailResp" json:"success,omitempty"`
}

func NewKnowledgeServiceGetNodeDetailResult() *KnowledgeServiceGetNodeDetailResult {
	return &KnowledgeServiceGetNodeDetailResult{}
}

func (p *KnowledgeServiceGetNodeDetailResult) InitDefault() {
}

var KnowledgeServiceGetNodeDetailResult_Success_DEFAULT *KnowledgeNodeDetailResp

func (p *KnowledgeServiceGetNodeDetailResult) GetSuccess() (v *KnowledgeNodeDetailResp) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceGetNodeDetailResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceGetNodeDetailResult) SetSuccess(x interface{}) {
	p.Success = x.(*KnowledgeNodeDetailResp)
}

func (p *KnowledgeServiceGetNodeDetailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceGetNodeDetailResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetNodeDetailResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetNodeDetailResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceGetEdgeDetailArgs struct {
	Req *KnowledgeEdgeDetailReq `thrift:"req,1" frugal:"1,default,KnowledgeEdgeDetailReq" json:"req"`
}

func NewKnowledgeServiceGetEdgeDetailArgs() *KnowledgeServiceGetEdgeDetailArgs {
	return &KnowledgeServiceGetEdgeDetailArgs{}
}

func (p *KnowledgeServiceGetEdgeDetailArgs) InitDefault() {
}

var KnowledgeServiceGetEdgeDetailArgs_Req_DEFAULT *KnowledgeEdgeDetailReq

func (p *KnowledgeServiceGetEdgeDetailArgs) GetReq() (v *KnowledgeEdgeDetailReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceGetEdgeDetailArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceGetEdgeDetailArgs) SetReq(val *KnowledgeEdgeDetailReq) {
	p.Req = val
}

func (p *KnowledgeServiceGetEdgeDetailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceGetEdgeDetailArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetEdgeDetailArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetEdgeDetailArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceGetEdgeDetailResult struct {
	Success *KnowledgeEdgeDetailResp `thrift:"success,0,optional" frugal:"0,optional,KnowledgeEdgeDetailResp" json:"success,omitempty"`
}

func NewKnowledgeServiceGetEdgeDetailResult() *KnowledgeServiceGetEdgeDetailResult {
	return &KnowledgeServiceGetEdgeDetailResult{}
}

func (p *KnowledgeServiceGetEdgeDetailResult) InitDefault() {
}

var KnowledgeServiceGetEdgeDetailResult_Success_DEFAULT *KnowledgeEdgeDetailResp

func (p *KnowledgeServiceGetEdgeDetailResult) GetSuccess() (v *KnowledgeEdgeDetailResp) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceGetEdgeDetailResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceGetEdgeDetailResult) SetSuccess(x interface{}) {
	p.Success = x.(*KnowledgeEdgeDetailResp)
}

func (p *KnowledgeServiceGetEdgeDetailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceGetEdgeDetailResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetEdgeDetailResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetEdgeDetailResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceGetNeighborhoodArgs struct {
	Req *KnowledgeNeighborhoodReq `thrift:"req,1" frugal:"1,default,KnowledgeNeighborhoodReq" json:"req"`
}

func NewKnowledgeServiceGetNeighborhoodArgs() *KnowledgeServiceGetNeighborhoodArgs {
	return &KnowledgeServiceGetNeighborhoodArgs{}
}

func (p *KnowledgeServiceGetNeighborhoodArgs) InitDefault() {
}

var KnowledgeServiceGetNeighborhoodArgs_Req_DEFAULT *KnowledgeNeighborhoodReq

func (p *KnowledgeServiceGetNeighborhoodArgs) GetReq() (v *KnowledgeNeighborhoodReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceGetNeighborhoodArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceGetNeighborhoodArgs) SetReq(val *KnowledgeNeighborhoodReq) {
	p.Req = val
}

func (p *KnowledgeServiceGetNeighborhoodArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceGetNeighborhoodArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetNeighborhoodArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetNeighborhoodArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceGetNeighborhoodResult struct {
	Success *KnowledgeGraphResp `thrift:"success,0,optional" frugal:"0,optional,KnowledgeGraphResp" json:"success,omitempty"`
}

func NewKnowledgeServiceGetNeighborhoodResult() *KnowledgeServiceGetNeighborhoodResult {
	return &KnowledgeServiceGetNeighborhoodResult{}
}

func (p *KnowledgeServiceGetNeighborhoodResult) InitDefault() {
}

var KnowledgeServiceGetNeighborhoodResult_Success_DEFAULT *KnowledgeGraphResp

func (p *KnowledgeServiceGetNeighborhoodResult) GetSuccess() (v *KnowledgeGraphResp) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceGetNeighborhoodResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceGetNeighborhoodResult) SetSuccess(x interface{}) {
	p.Success = x.(*KnowledgeGraphResp)
}

func (p *KnowledgeServiceGetNeighborhoodResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceGetNeighborhoodResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetNeighborhoodResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetNeighborhoodResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceGetPathArgs struct {
	Req *KnowledgePathReq `thrift:"req,1" frugal:"1,default,KnowledgePathReq" json:"req"`
}

func NewKnowledgeServiceGetPathArgs() *KnowledgeServiceGetPathArgs {
	return &KnowledgeServiceGetPathArgs{}
}

func (p *KnowledgeServiceGetPathArgs) InitDefault() {
}

var KnowledgeServiceGetPathArgs_Req_DEFAULT *KnowledgePathReq

func (p *KnowledgeServiceGetPathArgs) GetReq() (v *KnowledgePathReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceGetPathArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceGetPathArgs) SetReq(val *KnowledgePathReq) {
	p.Req = val
}

func (p *KnowledgeServiceGetPathArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceGetPathArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetPathArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetPathArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceGetPathResult struct {
	Success *KnowledgePathResp `thrift:"success,0,optional" frugal:"0,optional,KnowledgePathResp" json:"success,omitempty"`
}

func NewKnowledgeServiceGetPathResult() *KnowledgeServiceGetPathResult {
	return &KnowledgeServiceGetPathResult{}
}

func (p *KnowledgeServiceGetPathResult) InitDefault() {
}

var KnowledgeServiceGetPathResult_Success_DEFAULT *KnowledgePathResp

func (p *KnowledgeServiceGetPathResult) GetSuccess() (v *KnowledgePathResp) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceGetPathResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceGetPathResult) SetSuccess(x interface{}) {
	p.Success = x.(*KnowledgePathResp)
}

func (p *KnowledgeServiceGetPathResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceGetPathResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetPathResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetPathResult = map[int16]string{
	0: "success",
}
