// Code generated by Kitex v0.12.3. DO NOT EDIT.

package historyservice

import (
	message "ClaranAIM/kitex_gen/message"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SaveMessage(ctx context.Context, req *message.SaveMessageReq, callOptions ...callopt.Option) (r *message.SaveMessageResp, err error)
	GetHistory(ctx context.Context, req *message.GetHistoryReq, callOptions ...callopt.Option) (r *message.GetHistoryResp, err error)
	SearchHistory(ctx context.Context, req *message.SearchMessagesReq, callOptions ...callopt.Option) (r *message.SearchMessagesResp, err error)
	GetOfflineMessages(ctx context.Context, req *message.GetOfflineMessagesReq, callOptions ...callopt.Option) (r *message.GetOfflineMessagesResp, err error)
	MarkOfflineRead(ctx context.Context, req *message.MarkOfflineReadReq, callOptions ...callopt.Option) (r *message.MarkOfflineReadResp, err error)
	GetUnreadCount(ctx context.Context, req *message.GetUnreadCountReq, callOptions ...callopt.Option) (r *message.GetUnreadCountResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kHistoryServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kHistoryServiceClient struct {
	*kClient
}

func (p *kHistoryServiceClient) SaveMessage(ctx context.Context, req *message.SaveMessageReq, callOptions ...callopt.Option) (r *message.SaveMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SaveMessage(ctx, req)
}

func (p *kHistoryServiceClient) GetHistory(ctx context.Context, req *message.GetHistoryReq, callOptions ...callopt.Option) (r *message.GetHistoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetHistory(ctx, req)
}

func (p *kHistoryServiceClient) SearchHistory(ctx context.Context, req *message.SearchMessagesReq, callOptions ...callopt.Option) (r *message.SearchMessagesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchHistory(ctx, req)
}

func (p *kHistoryServiceClient) GetOfflineMessages(ctx context.Context, req *message.GetOfflineMessagesReq, callOptions ...callopt.Option) (r *message.GetOfflineMessagesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOfflineMessages(ctx, req)
}

func (p *kHistoryServiceClient) MarkOfflineRead(ctx context.Context, req *message.MarkOfflineReadReq, callOptions ...callopt.Option) (r *message.MarkOfflineReadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MarkOfflineRead(ctx, req)
}

func (p *kHistoryServiceClient) GetUnreadCount(ctx context.Context, req *message.GetUnreadCountReq, callOptions ...callopt.Option) (r *message.GetUnreadCountResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUnreadCount(ctx, req)
}
