// Code generated by Kitex v0.12.3. DO NOT EDIT.

package historyservice

import (
	message "ClaranAIM/kitex_gen/message"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SaveMessage": kitex.NewMethodInfo(
		saveMessageHandler,
		newHistoryServiceSaveMessageArgs,
		newHistoryServiceSaveMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetHistory": kitex.NewMethodInfo(
		getHistoryHandler,
		newHistoryServiceGetHistoryArgs,
		newHistoryServiceGetHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SearchHistory": kitex.NewMethodInfo(
		searchHistoryHandler,
		newHistoryServiceSearchHistoryArgs,
		newHistoryServiceSearchHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOfflineMessages": kitex.NewMethodInfo(
		getOfflineMessagesHandler,
		newHistoryServiceGetOfflineMessagesArgs,
		newHistoryServiceGetOfflineMessagesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MarkOfflineRead": kitex.NewMethodInfo(
		markOfflineReadHandler,
		newHistoryServiceMarkOfflineReadArgs,
		newHistoryServiceMarkOfflineReadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUnreadCount": kitex.NewMethodInfo(
		getUnreadCountHandler,
		newHistoryServiceGetUnreadCountArgs,
		newHistoryServiceGetUnreadCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	historyServiceServiceInfo                = NewServiceInfo()
	historyServiceServiceInfoForClient       = NewServiceInfoForClient()
	historyServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return historyServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return historyServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return historyServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "HistoryService"
	handlerType := (*message.HistoryService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "message",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func saveMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.HistoryServiceSaveMessageArgs)
	realResult := result.(*message.HistoryServiceSaveMessageResult)
	success, err := handler.(message.HistoryService).SaveMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHistoryServiceSaveMessageArgs() interface{} {
	return message.NewHistoryServiceSaveMessageArgs()
}

func newHistoryServiceSaveMessageResult() interface{} {
	return message.NewHistoryServiceSaveMessageResult()
}

func getHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.HistoryServiceGetHistoryArgs)
	realResult := result.(*message.HistoryServiceGetHistoryResult)
	success, err := handler.(message.HistoryService).GetHistory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHistoryServiceGetHistoryArgs() interface{} {
	return message.NewHistoryServiceGetHistoryArgs()
}

func newHistoryServiceGetHistoryResult() interface{} {
	return message.NewHistoryServiceGetHistoryResult()
}

func searchHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.HistoryServiceSearchHistoryArgs)
	realResult := result.(*message.HistoryServiceSearchHistoryResult)
	success, err := handler.(message.HistoryService).SearchHistory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHistoryServiceSearchHistoryArgs() interface{} {
	return message.NewHistoryServiceSearchHistoryArgs()
}

func newHistoryServiceSearchHistoryResult() interface{} {
	return message.NewHistoryServiceSearchHistoryResult()
}

func getOfflineMessagesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.HistoryServiceGetOfflineMessagesArgs)
	realResult := result.(*message.HistoryServiceGetOfflineMessagesResult)
	success, err := handler.(message.HistoryService).GetOfflineMessages(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHistoryServiceGetOfflineMessagesArgs() interface{} {
	return message.NewHistoryServiceGetOfflineMessagesArgs()
}

func newHistoryServiceGetOfflineMessagesResult() interface{} {
	return message.NewHistoryServiceGetOfflineMessagesResult()
}

func markOfflineReadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.HistoryServiceMarkOfflineReadArgs)
	realResult := result.(*message.HistoryServiceMarkOfflineReadResult)
	success, err := handler.(message.HistoryService).MarkOfflineRead(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHistoryServiceMarkOfflineReadArgs() interface{} {
	return message.NewHistoryServiceMarkOfflineReadArgs()
}

func newHistoryServiceMarkOfflineReadResult() interface{} {
	return message.NewHistoryServiceMarkOfflineReadResult()
}

func getUnreadCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.HistoryServiceGetUnreadCountArgs)
	realResult := result.(*message.HistoryServiceGetUnreadCountResult)
	success, err := handler.(message.HistoryService).GetUnreadCount(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHistoryServiceGetUnreadCountArgs() interface{} {
	return message.NewHistoryServiceGetUnreadCountArgs()
}

func newHistoryServiceGetUnreadCountResult() interface{} {
	return message.NewHistoryServiceGetUnreadCountResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SaveMessage(ctx context.Context, req *message.SaveMessageReq) (r *message.SaveMessageResp, err error) {
	var _args message.HistoryServiceSaveMessageArgs
	_args.Req = req
	var _result message.HistoryServiceSaveMessageResult
	if err = p.c.Call(ctx, "SaveMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetHistory(ctx context.Context, req *message.GetHistoryReq) (r *message.GetHistoryResp, err error) {
	var _args message.HistoryServiceGetHistoryArgs
	_args.Req = req
	var _result message.HistoryServiceGetHistoryResult
	if err = p.c.Call(ctx, "GetHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchHistory(ctx context.Context, req *message.SearchMessagesReq) (r *message.SearchMessagesResp, err error) {
	var _args message.HistoryServiceSearchHistoryArgs
	_args.Req = req
	var _result message.HistoryServiceSearchHistoryResult
	if err = p.c.Call(ctx, "SearchHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOfflineMessages(ctx context.Context, req *message.GetOfflineMessagesReq) (r *message.GetOfflineMessagesResp, err error) {
	var _args message.HistoryServiceGetOfflineMessagesArgs
	_args.Req = req
	var _result message.HistoryServiceGetOfflineMessagesResult
	if err = p.c.Call(ctx, "GetOfflineMessages", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MarkOfflineRead(ctx context.Context, req *message.MarkOfflineReadReq) (r *message.MarkOfflineReadResp, err error) {
	var _args message.HistoryServiceMarkOfflineReadArgs
	_args.Req = req
	var _result message.HistoryServiceMarkOfflineReadResult
	if err = p.c.Call(ctx, "MarkOfflineRead", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUnreadCount(ctx context.Context, req *message.GetUnreadCountReq) (r *message.GetUnreadCountResp, err error) {
	var _args message.HistoryServiceGetUnreadCountArgs
	_args.Req = req
	var _result message.HistoryServiceGetUnreadCountResult
	if err = p.c.Call(ctx, "GetUnreadCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
