// Code generated by Kitex v0.12.3. DO NOT EDIT.

package botservice

import (
	bot "ClaranAIM/kitex_gen/bot"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateBot": kitex.NewMethodInfo(
		createBotHandler,
		newBotServiceCreateBotArgs,
		newBotServiceCreateBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateBot": kitex.NewMethodInfo(
		updateBotHandler,
		newBotServiceUpdateBotArgs,
		newBotServiceUpdateBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetBot": kitex.NewMethodInfo(
		getBotHandler,
		newBotServiceGetBotArgs,
		newBotServiceGetBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListBots": kitex.NewMethodInfo(
		listBotsHandler,
		newBotServiceListBotsArgs,
		newBotServiceListBotsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteBot": kitex.NewMethodInfo(
		deleteBotHandler,
		newBotServiceDeleteBotArgs,
		newBotServiceDeleteBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChatWithBot": kitex.NewMethodInfo(
		chatWithBotHandler,
		newBotServiceChatWithBotArgs,
		newBotServiceChatWithBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SummarizeConversation": kitex.NewMethodInfo(
		summarizeConversationHandler,
		newBotServiceSummarizeConversationArgs,
		newBotServiceSummarizeConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AskConversation": kitex.NewMethodInfo(
		askConversationHandler,
		newBotServiceAskConversationArgs,
		newBotServiceAskConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ExtractInsights": kitex.NewMethodInfo(
		extractInsightsHandler,
		newBotServiceExtractInsightsArgs,
		newBotServiceExtractInsightsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GenerateReplyCandidates": kitex.NewMethodInfo(
		generateReplyCandidatesHandler,
		newBotServiceGenerateReplyCandidatesArgs,
		newBotServiceGenerateReplyCandidatesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GrantPermission": kitex.NewMethodInfo(
		grantPermissionHandler,
		newBotServiceGrantPermissionArgs,
		newBotServiceGrantPermissionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RevokePermission": kitex.NewMethodInfo(
		revokePermissionHandler,
		newBotServiceRevokePermissionArgs,
		newBotServiceRevokePermissionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListPermissions": kitex.NewMethodInfo(
		listPermissionsHandler,
		newBotServiceListPermissionsArgs,
		newBotServiceListPermissionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateRoute": kitex.NewMethodInfo(
		createRouteHandler,
		newBotServiceCreateRouteArgs,
		newBotServiceCreateRouteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListRoutes": kitex.NewMethodInfo(
		listRoutesHandler,
		newBotServiceListRoutesArgs,
		newBotServiceListRoutesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteRoute": kitex.NewMethodInfo(
		deleteRouteHandler,
		newBotServiceDeleteRouteArgs,
		newBotServiceDeleteRouteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetBilling": kitex.NewMethodInfo(
		getBillingHandler,
		newBotServiceGetBillingArgs,
		newBotServiceGetBillingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	botServiceServiceInfo                = NewServiceInfo()
	botServiceServiceInfoForClient       = NewServiceInfoForClient()
	botServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return botServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return botServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return botServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "BotService"
	handlerType := (*bot.BotService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "bot",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func createBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceCreateBotArgs)
	realResult := result.(*bot.BotServiceCreateBotResult)
	success, err := handler.(bot.BotService).CreateBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceCreateBotArgs() interface{} {
	return bot.NewBotServiceCreateBotArgs()
}

func newBotServiceCreateBotResult() interface{} {
	return bot.NewBotServiceCreateBotResult()
}

func updateBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceUpdateBotArgs)
	realResult := result.(*bot.BotServiceUpdateBotResult)
	success, err := handler.(bot.BotService).UpdateBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceUpdateBotArgs() interface{} {
	return bot.NewBotServiceUpdateBotArgs()
}

func newBotServiceUpdateBotResult() interface{} {
	return bot.NewBotServiceUpdateBotResult()
}

func getBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceGetBotArgs)
	realResult := result.(*bot.BotServiceGetBotResult)
	success, err := handler.(bot.BotService).GetBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceGetBotArgs() interface{} {
	return bot.NewBotServiceGetBotArgs()
}

func newBotServiceGetBotResult() interface{} {
	return bot.NewBotServiceGetBotResult()
}

func listBotsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceListBotsArgs)
	realResult := result.(*bot.BotServiceListBotsResult)
	success, err := handler.(bot.BotService).ListBots(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceListBotsArgs() interface{} {
	return bot.NewBotServiceListBotsArgs()
}

func newBotServiceListBotsResult() interface{} {
	return bot.NewBotServiceListBotsResult()
}

func deleteBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceDeleteBotArgs)
	realResult := result.(*bot.BotServiceDeleteBotResult)
	success, err := handler.(bot.BotService).DeleteBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceDeleteBotArgs() interface{} {
	return bot.NewBotServiceDeleteBotArgs()
}

func newBotServiceDeleteBotResult() interface{} {
	return bot.NewBotServiceDeleteBotResult()
}

func chatWithBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceChatWithBotArgs)
	realResult := result.(*bot.BotServiceChatWithBotResult)
	success, err := handler.(bot.BotService).ChatWithBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceChatWithBotArgs() interface{} {
	return bot.NewBotServiceChatWithBotArgs()
}

func newBotServiceChatWithBotResult() interface{} {
	return bot.NewBotServiceChatWithBotResult()
}

func summarizeConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceSummarizeConversationArgs)
	realResult := result.(*bot.BotServiceSummarizeConversationResult)
	success, err := handler.(bot.BotService).SummarizeConversation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceSummarizeConversationArgs() interface{} {
	return bot.NewBotServiceSummarizeConversationArgs()
}

func newBotServiceSummarizeConversationResult() interface{} {
	return bot.NewBotServiceSummarizeConversationResult()
}

func askConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceAskConversationArgs)
	realResult := result.(*bot.BotServiceAskConversationResult)
	success, err := handler.(bot.BotService).AskConversation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceAskConversationArgs() interface{} {
	return bot.NewBotServiceAskConversationArgs()
}

func newBotServiceAskConversationResult() interface{} {
	return bot.NewBotServiceAskConversationResult()
}

func extractInsightsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceExtractInsightsArgs)
	realResult := result.(*bot.BotServiceExtractInsightsResult)
	success, err := handler.(bot.BotService).ExtractInsights(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceExtractInsightsArgs() interface{} {
	return bot.NewBotServiceExtractInsightsArgs()
}

func newBotServiceExtractInsightsResult() interface{} {
	return bot.NewBotServiceExtractInsightsResult()
}

func generateReplyCandidatesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceGenerateReplyCandidatesArgs)
	realResult := result.(*bot.BotServiceGenerateReplyCandidatesResult)
	success, err := handler.(bot.BotService).GenerateReplyCandidates(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceGenerateReplyCandidatesArgs() interface{} {
	return bot.NewBotServiceGenerateReplyCandidatesArgs()
}

func newBotServiceGenerateReplyCandidatesResult() interface{} {
	return bot.NewBotServiceGenerateReplyCandidatesResult()
}

func grantPermissionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceGrantPermissionArgs)
	realResult := result.(*bot.BotServiceGrantPermissionResult)
	success, err := handler.(bot.BotService).GrantPermission(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceGrantPermissionArgs() interface{} {
	return bot.NewBotServiceGrantPermissionArgs()
}

func newBotServiceGrantPermissionResult() interface{} {
	return bot.NewBotServiceGrantPermissionResult()
}

func revokePermissionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceRevokePermissionArgs)
	realResult := result.(*bot.BotServiceRevokePermissionResult)
	success, err := handler.(bot.BotService).RevokePermission(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceRevokePermissionArgs() interface{} {
	return bot.NewBotServiceRevokePermissionArgs()
}

func newBotServiceRevokePermissionResult() interface{} {
	return bot.NewBotServiceRevokePermissionResult()
}

func listPermissionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceListPermissionsArgs)
	realResult := result.(*bot.BotServiceListPermissionsResult)
	success, err := handler.(bot.BotService).ListPermissions(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceListPermissionsArgs() interface{} {
	return bot.NewBotServiceListPermissionsArgs()
}

func newBotServiceListPermissionsResult() interface{} {
	return bot.NewBotServiceListPermissionsResult()
}

func createRouteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceCreateRouteArgs)
	realResult := result.(*bot.BotServiceCreateRouteResult)
	success, err := handler.(bot.BotService).CreateRoute(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceCreateRouteArgs() interface{} {
	return bot.NewBotServiceCreateRouteArgs()
}

func newBotServiceCreateRouteResult() interface{} {
	return bot.NewBotServiceCreateRouteResult()
}

func listRoutesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceListRoutesArgs)
	realResult := result.(*bot.BotServiceListRoutesResult)
	success, err := handler.(bot.BotService).ListRoutes(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceListRoutesArgs() interface{} {
	return bot.NewBotServiceListRoutesArgs()
}

func newBotServiceListRoutesResult() interface{} {
	return bot.NewBotServiceListRoutesResult()
}

func deleteRouteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceDeleteRouteArgs)
	realResult := result.(*bot.BotServiceDeleteRouteResult)
	success, err := handler.(bot.BotService).DeleteRoute(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceDeleteRouteArgs() interface{} {
	return bot.NewBotServiceDeleteRouteArgs()
}

func newBotServiceDeleteRouteResult() interface{} {
	return bot.NewBotServiceDeleteRouteResult()
}

func getBillingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceGetBillingArgs)
	realResult := result.(*bot.BotServiceGetBillingResult)
	success, err := handler.(bot.BotService).GetBilling(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceGetBillingArgs() interface{} {
	return bot.NewBotServiceGetBillingArgs()
}

func newBotServiceGetBillingResult() interface{} {
	return bot.NewBotServiceGetBillingResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateBot(ctx context.Context, req *bot.CreateBotReq) (r *bot.CreateBotResp, err error) {
	var _args bot.BotServiceCreateBotArgs
	_args.Req = req
	var _result bot.BotServiceCreateBotResult
	if err = p.c.Call(ctx, "CreateBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateBot(ctx context.Context, req *bot.UpdateBotReq) (r *bot.UpdateBotResp, err error) {
	var _args bot.BotServiceUpdateBotArgs
	_args.Req = req
	var _result bot.BotServiceUpdateBotResult
	if err = p.c.Call(ctx, "UpdateBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetBot(ctx context.Context, req *bot.GetBotReq) (r *bot.GetBotResp, err error) {
	var _args bot.BotServiceGetBotArgs
	_args.Req = req
	var _result bot.BotServiceGetBotResult
	if err = p.c.Call(ctx, "GetBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListBots(ctx context.Context, req *bot.ListBotsReq) (r *bot.ListBotsResp, err error) {
	var _args bot.BotServiceListBotsArgs
	_args.Req = req
	var _result bot.BotServiceListBotsResult
	if err = p.c.Call(ctx, "ListBots", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteBot(ctx context.Context, req *bot.DeleteBotReq) (r *bot.DeleteBotResp, err error) {
	var _args bot.BotServiceDeleteBotArgs
	_args.Req = req
	var _result bot.BotServiceDeleteBotResult
	if err = p.c.Call(ctx, "DeleteBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChatWithBot(ctx context.Context, req *bot.ChatWithBotReq) (r *bot.ChatWithBotResp, err error) {
	var _args bot.BotServiceChatWithBotArgs
	_args.Req = req
	var _result bot.BotServiceChatWithBotResult
	if err = p.c.Call(ctx, "ChatWithBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SummarizeConversation(ctx context.Context, req *bot.AgentTaskReq) (r *bot.AgentTaskResp, err error) {
	var _args bot.BotServiceSummarizeConversationArgs
	_args.Req = req
	var _result bot.BotServiceSummarizeConversationResult
	if err = p.c.Call(ctx, "SummarizeConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AskConversation(ctx context.Context, req *bot.AgentTaskReq) (r *bot.AgentTaskResp, err error) {
	var _args bot.BotServiceAskConversationArgs
	_args.Req = req
	var _result bot.BotServiceAskConversationResult
	if err = p.c.Call(ctx, "AskConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ExtractInsights(ctx context.Context, req *bot.AgentTaskReq) (r *bot.AgentTaskResp, err error) {
	var _args bot.BotServiceExtractInsightsArgs
	_args.Req = req
	var _result bot.BotServiceExtractInsightsResult
	if err = p.c.Call(ctx, "ExtractInsights", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GenerateReplyCandidates(ctx context.Context, req *bot.AgentTaskReq) (r *bot.AgentTaskResp, err error) {
	var _args bot.BotServiceGenerateReplyCandidatesArgs
	_args.Req = req
	var _result bot.BotServiceGenerateReplyCandidatesResult
	if err = p.c.Call(ctx, "GenerateReplyCandidates", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GrantPermission(ctx context.Context, req *bot.GrantPermissionReq) (r *bot.GrantPermissionResp, err error) {
	var _args bot.BotServiceGrantPermissionArgs
	_args.Req = req
	var _result bot.BotServiceGrantPermissionResult
	if err = p.c.Call(ctx, "GrantPermission", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RevokePermission(ctx context.Context, req *bot.RevokePermissionReq) (r *bot.RevokePermissionResp, err error) {
	var _args bot.BotServiceRevokePermissionArgs
	_args.Req = req
	var _result bot.BotServiceRevokePermissionResult
	if err = p.c.Call(ctx, "RevokePermission", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListPermissions(ctx context.Context, req *bot.ListPermissionsReq) (r *bot.ListPermissionsResp, err error) {
	var _args bot.BotServiceListPermissionsArgs
	_args.Req = req
	var _result bot.BotServiceListPermissionsResult
	if err = p.c.Call(ctx, "ListPermissions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateRoute(ctx context.Context, req *bot.CreateRouteReq) (r *bot.CreateRouteResp, err error) {
	var _args bot.BotServiceCreateRouteArgs
	_args.Req = req
	var _result bot.BotServiceCreateRouteResult
	if err = p.c.Call(ctx, "CreateRoute", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListRoutes(ctx context.Context, req *bot.ListRoutesReq) (r *bot.ListRoutesResp, err error) {
	var _args bot.BotServiceListRoutesArgs
	_args.Req = req
	var _result bot.BotServiceListRoutesResult
	if err = p.c.Call(ctx, "ListRoutes", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteRoute(ctx context.Context, req *bot.DeleteRouteReq) (r *bot.DeleteRouteResp, err error) {
	var _args bot.BotServiceDeleteRouteArgs
	_args.Req = req
	var _result bot.BotServiceDeleteRouteResult
	if err = p.c.Call(ctx, "DeleteRoute", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetBilling(ctx context.Context, req *bot.GetBillingReq) (r *bot.GetBillingResp, err error) {
	var _args bot.BotServiceGetBillingArgs
	_args.Req = req
	var _result bot.BotServiceGetBillingResult
	if err = p.c.Call(ctx, "GetBilling", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
