// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
)

type User struct {
	Id        int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Username  string `thrift:"username,2" frugal:"2,default,string" json:"username"`
	Nickname  string `thrift:"nickname,3" frugal:"3,default,string" json:"nickname"`
	Avatar    string `thrift:"avatar,4" frugal:"4,default,string" json:"avatar"`
	Email     string `thrift:"email,5" frugal:"5,default,string" json:"email"`
	Phone     string `thrift:"phone,6" frugal:"6,default,string" json:"phone"`
	Status    string `thrift:"status,7" frugal:"7,default,string" json:"status"`
	CreatedAt string `thrift:"created_at,8" frugal:"8,default,string" json:"created_at"`
	UpdatedAt string `thrift:"updated_at,9" frugal:"9,default,string" json:"updated_at"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetId() (v int64) {
	return p.Id
}

func (p *User) GetUsername() (v string) {
	return p.Username
}

func (p *User) GetNickname() (v string) {
	return p.Nickname
}

func (p *User) GetAvatar() (v string) {
	return p.Avatar
}

func (p *User) GetEmail() (v string) {
	return p.Email
}

func (p *User) GetPhone() (v string) {
	return p.Phone
}

func (p *User) GetStatus() (v string) {
	return p.Status
}

func (p *User) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *User) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}
func (p *User) SetId(val int64) {
	p.Id = val
}
func (p *User) SetUsername(val string) {
	p.Username = val
}
func (p *User) SetNickname(val string) {
	p.Nickname = val
}
func (p *User) SetAvatar(val string) {
	p.Avatar = val
}
func (p *User) SetEmail(val string) {
	p.Email = val
}
func (p *User) SetPhone(val string) {
	p.Phone = val
}
func (p *User) SetStatus(val string) {
	p.Status = val
}
func (p *User) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *User) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1: "id",
	2: "username",
	3: "nickname",
	4: "avatar",
	5: "email",
	6: "phone",
	7: "status",
	8: "created_at",
	9: "updated_at",
}

type RegisterReq struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
	Nickname string `thrift:"nickname,3" frugal:"3,default,string" json:"nickname"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

func (p *RegisterReq) GetUsername() (v string) {
	return p.Username
}

func (p *RegisterReq) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterReq) GetNickname() (v string) {
	return p.Nickname
}
func (p *RegisterReq) SetUsername(val string) {
	p.Username = val
}
func (p *RegisterReq) SetPassword(val string) {
	p.Password = val
}
func (p *RegisterReq) SetNickname(val string) {
	p.Nickname = val
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

var fieldIDToName_RegisterReq = map[int16]string{
	1: "username",
	2: "password",
	3: "nickname",
}

type RegisterResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	UserId  int64  `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	Msg     string `thrift:"msg,3" frugal:"3,default,string" json:"msg"`
}

func NewRegisterResp() *RegisterResp {
	return &RegisterResp{}
}

func (p *RegisterResp) InitDefault() {
}

func (p *RegisterResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *RegisterResp) GetUserId() (v int64) {
	return p.UserId
}

func (p *RegisterResp) GetMsg() (v string) {
	return p.Msg
}
func (p *RegisterResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *RegisterResp) SetUserId(val int64) {
	p.UserId = val
}
func (p *RegisterResp) SetMsg(val string) {
	p.Msg = val
}

func (p *RegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResp(%+v)", *p)
}

var fieldIDToName_RegisterResp = map[int16]string{
	1: "success",
	2: "user_id",
	3: "msg",
}

type LoginReq struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

func (p *LoginReq) GetUsername() (v string) {
	return p.Username
}

func (p *LoginReq) GetPassword() (v string) {
	return p.Password
}
func (p *LoginReq) SetUsername(val string) {
	p.Username = val
}
func (p *LoginReq) SetPassword(val string) {
	p.Password = val
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

var fieldIDToName_LoginReq = map[int16]string{
	1: "username",
	2: "password",
}

type LoginResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Token   string `thrift:"token,2" frugal:"2,default,string" json:"token"`
	UserId  int64  `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
	Msg     string `thrift:"msg,4" frugal:"4,default,string" json:"msg"`
}

func NewLoginResp() *LoginResp {
	return &LoginResp{}
}

func (p *LoginResp) InitDefault() {
}

func (p *LoginResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *LoginResp) GetToken() (v string) {
	return p.Token
}

func (p *LoginResp) GetUserId() (v int64) {
	return p.UserId
}

func (p *LoginResp) GetMsg() (v string) {
	return p.Msg
}
func (p *LoginResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *LoginResp) SetToken(val string) {
	p.Token = val
}
func (p *LoginResp) SetUserId(val int64) {
	p.UserId = val
}
func (p *LoginResp) SetMsg(val string) {
	p.Msg = val
}

func (p *LoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResp(%+v)", *p)
}

var fieldIDToName_LoginResp = map[int16]string{
	1: "success",
	2: "token",
	3: "user_id",
	4: "msg",
}

type GetUserInfoReq struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetUserInfoReq() *GetUserInfoReq {
	return &GetUserInfoReq{}
}

func (p *GetUserInfoReq) InitDefault() {
}

func (p *GetUserInfoReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetUserInfoReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoReq(%+v)", *p)
}

var fieldIDToName_GetUserInfoReq = map[int16]string{
	1: "user_id",
}

type GetUserInfoResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	User    *User  `thrift:"user,2" frugal:"2,default,User" json:"user"`
	Msg     string `thrift:"msg,3" frugal:"3,default,string" json:"msg"`
}

func NewGetUserInfoResp() *GetUserInfoResp {
	return &GetUserInfoResp{}
}

func (p *GetUserInfoResp) InitDefault() {
}

func (p *GetUserInfoResp) GetSuccess() (v bool) {
	return p.Success
}

var GetUserInfoResp_User_DEFAULT *User

func (p *GetUserInfoResp) GetUser() (v *User) {
	if !p.IsSetUser() {
		return GetUserInfoResp_User_DEFAULT
	}
	return p.User
}

func (p *GetUserInfoResp) GetMsg() (v string) {
	return p.Msg
}
func (p *GetUserInfoResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *GetUserInfoResp) SetUser(val *User) {
	p.User = val
}
func (p *GetUserInfoResp) SetMsg(val string) {
	p.Msg = val
}

func (p *GetUserInfoResp) IsSetUser() bool {
	return p.User != nil
}

func (p *GetUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoResp(%+v)", *p)
}

var fieldIDToName_GetUserInfoResp = map[int16]string{
	1: "success",
	2: "user",
	3: "msg",
}

type UpdateUserInfoReq struct {
	UserId   int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Nickname string `thrift:"nickname,2" frugal:"2,default,string" json:"nickname"`
	Email    string `thrift:"email,3" frugal:"3,default,string" json:"email"`
	Phone    string `thrift:"phone,4" frugal:"4,default,string" json:"phone"`
}

func NewUpdateUserInfoReq() *UpdateUserInfoReq {
	return &UpdateUserInfoReq{}
}

func (p *UpdateUserInfoReq) InitDefault() {
}

func (p *UpdateUserInfoReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *UpdateUserInfoReq) GetNickname() (v string) {
	return p.Nickname
}

func (p *UpdateUserInfoReq) GetEmail() (v string) {
	return p.Email
}

func (p *UpdateUserInfoReq) GetPhone() (v string) {
	return p.Phone
}
func (p *UpdateUserInfoReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateUserInfoReq) SetNickname(val string) {
	p.Nickname = val
}
func (p *UpdateUserInfoReq) SetEmail(val string) {
	p.Email = val
}
func (p *UpdateUserInfoReq) SetPhone(val string) {
	p.Phone = val
}

func (p *UpdateUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserInfoReq(%+v)", *p)
}

var fieldIDToName_UpdateUserInfoReq = map[int16]string{
	1: "user_id",
	2: "nickname",
	3: "email",
	4: "phone",
}

type UpdateUserInfoResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Msg     string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewUpdateUserInfoResp() *UpdateUserInfoResp {
	return &UpdateUserInfoResp{}
}

func (p *UpdateUserInfoResp) InitDefault() {
}

func (p *UpdateUserInfoResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *UpdateUserInfoResp) GetMsg() (v string) {
	return p.Msg
}
func (p *UpdateUserInfoResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *UpdateUserInfoResp) SetMsg(val string) {
	p.Msg = val
}

func (p *UpdateUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserInfoResp(%+v)", *p)
}

var fieldIDToName_UpdateUserInfoResp = map[int16]string{
	1: "success",
	2: "msg",
}

type UpdateAvatarReq struct {
	UserId int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Avatar string `thrift:"avatar,2" frugal:"2,default,string" json:"avatar"`
}

func NewUpdateAvatarReq() *UpdateAvatarReq {
	return &UpdateAvatarReq{}
}

func (p *UpdateAvatarReq) InitDefault() {
}

func (p *UpdateAvatarReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *UpdateAvatarReq) GetAvatar() (v string) {
	return p.Avatar
}
func (p *UpdateAvatarReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateAvatarReq) SetAvatar(val string) {
	p.Avatar = val
}

func (p *UpdateAvatarReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateAvatarReq(%+v)", *p)
}

var fieldIDToName_UpdateAvatarReq = map[int16]string{
	1: "user_id",
	2: "avatar",
}

type UpdateAvatarResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Msg     string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewUpdateAvatarResp() *UpdateAvatarResp {
	return &UpdateAvatarResp{}
}

func (p *UpdateAvatarResp) InitDefault() {
}

func (p *UpdateAvatarResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *UpdateAvatarResp) GetMsg() (v string) {
	return p.Msg
}
func (p *UpdateAvatarResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *UpdateAvatarResp) SetMsg(val string) {
	p.Msg = val
}

func (p *UpdateAvatarResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateAvatarResp(%+v)", *p)
}

var fieldIDToName_UpdateAvatarResp = map[int16]string{
	1: "success",
	2: "msg",
}

type UpdateStatusReq struct {
	UserId int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Status string `thrift:"status,2" frugal:"2,default,string" json:"status"`
}

func NewUpdateStatusReq() *UpdateStatusReq {
	return &UpdateStatusReq{}
}

func (p *UpdateStatusReq) InitDefault() {
}

func (p *UpdateStatusReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *UpdateStatusReq) GetStatus() (v string) {
	return p.Status
}
func (p *UpdateStatusReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateStatusReq) SetStatus(val string) {
	p.Status = val
}

func (p *UpdateStatusReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateStatusReq(%+v)", *p)
}

var fieldIDToName_UpdateStatusReq = map[int16]string{
	1: "user_id",
	2: "status",
}

type UpdateStatusResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Msg     string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewUpdateStatusResp() *UpdateStatusResp {
	return &UpdateStatusResp{}
}

func (p *UpdateStatusResp) InitDefault() {
}

func (p *UpdateStatusResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *UpdateStatusResp) GetMsg() (v string) {
	return p.Msg
}
func (p *UpdateStatusResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *UpdateStatusResp) SetMsg(val string) {
	p.Msg = val
}

func (p *UpdateStatusResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateStatusResp(%+v)", *p)
}

var fieldIDToName_UpdateStatusResp = map[int16]string{
	1: "success",
	2: "msg",
}

type AddFriendReq struct {
	UserId   int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FriendId int64  `thrift:"friend_id,2" frugal:"2,default,i64" json:"friend_id"`
	GroupId  int64  `thrift:"group_id,3" frugal:"3,default,i64" json:"group_id"`
	Remark   string `thrift:"remark,4" frugal:"4,default,string" json:"remark"`
}

func NewAddFriendReq() *AddFriendReq {
	return &AddFriendReq{}
}

func (p *AddFriendReq) InitDefault() {
}

func (p *AddFriendReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *AddFriendReq) GetFriendId() (v int64) {
	return p.FriendId
}

func (p *AddFriendReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *AddFriendReq) GetRemark() (v string) {
	return p.Remark
}
func (p *AddFriendReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *AddFriendReq) SetFriendId(val int64) {
	p.FriendId = val
}
func (p *AddFriendReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *AddFriendReq) SetRemark(val string) {
	p.Remark = val
}

func (p *AddFriendReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddFriendReq(%+v)", *p)
}

var fieldIDToName_AddFriendReq = map[int16]string{
	1: "user_id",
	2: "friend_id",
	3: "group_id",
	4: "remark",
}

type AddFriendResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Msg     string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewAddFriendResp() *AddFriendResp {
	return &AddFriendResp{}
}

func (p *AddFriendResp) InitDefault() {
}

func (p *AddFriendResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *AddFriendResp) GetMsg() (v string) {
	return p.Msg
}
func (p *AddFriendResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *AddFriendResp) SetMsg(val string) {
	p.Msg = val
}

func (p *AddFriendResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddFriendResp(%+v)", *p)
}

var fieldIDToName_AddFriendResp = map[int16]string{
	1: "success",
	2: "msg",
}

type DeleteFriendReq struct {
	UserId   int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FriendId int64 `thrift:"friend_id,2" frugal:"2,default,i64" json:"friend_id"`
}

func NewDeleteFriendReq() *DeleteFriendReq {
	return &DeleteFriendReq{}
}

func (p *DeleteFriendReq) InitDefault() {
}

func (p *DeleteFriendReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *DeleteFriendReq) GetFriendId() (v int64) {
	return p.FriendId
}
func (p *DeleteFriendReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *DeleteFriendReq) SetFriendId(val int64) {
	p.FriendId = val
}

func (p *DeleteFriendReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteFriendReq(%+v)", *p)
}

var fieldIDToName_DeleteFriendReq = map[int16]string{
	1: "user_id",
	2: "friend_id",
}

type DeleteFriendResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Msg     string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewDeleteFriendResp() *DeleteFriendResp {
	return &DeleteFriendResp{}
}

func (p *DeleteFriendResp) InitDefault() {
}

func (p *DeleteFriendResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *DeleteFriendResp) GetMsg() (v string) {
	return p.Msg
}
func (p *DeleteFriendResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *DeleteFriendResp) SetMsg(val string) {
	p.Msg = val
}

func (p *DeleteFriendResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteFriendResp(%+v)", *p)
}

var fieldIDToName_DeleteFriendResp = map[int16]string{
	1: "success",
	2: "msg",
}

type Friend struct {
	Id           int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	UserId       int64  `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	FriendId     int64  `thrift:"friend_id,3" frugal:"3,default,i64" json:"friend_id"`
	GroupId      int64  `thrift:"group_id,4" frugal:"4,default,i64" json:"group_id"`
	Remark       string `thrift:"remark,5" frugal:"5,default,string" json:"remark"`
	FriendName   string `thrift:"friend_name,6" frugal:"6,default,string" json:"friend_name"`
	FriendAvatar string `thrift:"friend_avatar,7" frugal:"7,default,string" json:"friend_avatar"`
	FriendStatus string `thrift:"friend_status,8" frugal:"8,default,string" json:"friend_status"`
	GroupName    string `thrift:"group_name,9" frugal:"9,default,string" json:"group_name"`
}

func NewFriend() *Friend {
	return &Friend{}
}

func (p *Friend) InitDefault() {
}

func (p *Friend) GetId() (v int64) {
	return p.Id
}

func (p *Friend) GetUserId() (v int64) {
	return p.UserId
}

func (p *Friend) GetFriendId() (v int64) {
	return p.FriendId
}

func (p *Friend) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *Friend) GetRemark() (v string) {
	return p.Remark
}

func (p *Friend) GetFriendName() (v string) {
	return p.FriendName
}

func (p *Friend) GetFriendAvatar() (v string) {
	return p.FriendAvatar
}

func (p *Friend) GetFriendStatus() (v string) {
	return p.FriendStatus
}

func (p *Friend) GetGroupName() (v string) {
	return p.GroupName
}
func (p *Friend) SetId(val int64) {
	p.Id = val
}
func (p *Friend) SetUserId(val int64) {
	p.UserId = val
}
func (p *Friend) SetFriendId(val int64) {
	p.FriendId = val
}
func (p *Friend) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *Friend) SetRemark(val string) {
	p.Remark = val
}
func (p *Friend) SetFriendName(val string) {
	p.FriendName = val
}
func (p *Friend) SetFriendAvatar(val string) {
	p.FriendAvatar = val
}
func (p *Friend) SetFriendStatus(val string) {
	p.FriendStatus = val
}
func (p *Friend) SetGroupName(val string) {
	p.GroupName = val
}

func (p *Friend) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Friend(%+v)", *p)
}

var fieldIDToName_Friend = map[int16]string{
	1: "id",
	2: "user_id",
	3: "friend_id",
	4: "group_id",
	5: "remark",
	6: "friend_name",
	7: "friend_avatar",
	8: "friend_status",
	9: "group_name",
}

type GetFriendListReq struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetFriendListReq() *GetFriendListReq {
	return &GetFriendListReq{}
}

func (p *GetFriendListReq) InitDefault() {
}

func (p *GetFriendListReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetFriendListReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetFriendListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFriendListReq(%+v)", *p)
}

var fieldIDToName_GetFriendListReq = map[int16]string{
	1: "user_id",
}

type GetFriendListResp struct {
	Success bool      `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Friends []*Friend `thrift:"friends,2" frugal:"2,default,list<Friend>" json:"friends"`
	Msg     string    `thrift:"msg,3" frugal:"3,default,string" json:"msg"`
}

func NewGetFriendListResp() *GetFriendListResp {
	return &GetFriendListResp{}
}

func (p *GetFriendListResp) InitDefault() {
}

func (p *GetFriendListResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *GetFriendListResp) GetFriends() (v []*Friend) {
	return p.Friends
}

func (p *GetFriendListResp) GetMsg() (v string) {
	return p.Msg
}
func (p *GetFriendListResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *GetFriendListResp) SetFriends(val []*Friend) {
	p.Friends = val
}
func (p *GetFriendListResp) SetMsg(val string) {
	p.Msg = val
}

func (p *GetFriendListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFriendListResp(%+v)", *p)
}

var fieldIDToName_GetFriendListResp = map[int16]string{
	1: "success",
	2: "friends",
	3: "msg",
}

type UpdateFriendRemarkReq struct {
	UserId   int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FriendId int64  `thrift:"friend_id,2" frugal:"2,default,i64" json:"friend_id"`
	Remark   string `thrift:"remark,3" frugal:"3,default,string" json:"remark"`
}

func NewUpdateFriendRemarkReq() *UpdateFriendRemarkReq {
	return &UpdateFriendRemarkReq{}
}

func (p *UpdateFriendRemarkReq) InitDefault() {
}

func (p *UpdateFriendRemarkReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *UpdateFriendRemarkReq) GetFriendId() (v int64) {
	return p.FriendId
}

func (p *UpdateFriendRemarkReq) GetRemark() (v string) {
	return p.Remark
}
func (p *UpdateFriendRemarkReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateFriendRemarkReq) SetFriendId(val int64) {
	p.FriendId = val
}
func (p *UpdateFriendRemarkReq) SetRemark(val string) {
	p.Remark = val
}

func (p *UpdateFriendRemarkReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateFriendRemarkReq(%+v)", *p)
}

var fieldIDToName_UpdateFriendRemarkReq = map[int16]string{
	1: "user_id",
	2: "friend_id",
	3: "remark",
}

type UpdateFriendRemarkResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Msg     string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewUpdateFriendRemarkResp() *UpdateFriendRemarkResp {
	return &UpdateFriendRemarkResp{}
}

func (p *UpdateFriendRemarkResp) InitDefault() {
}

func (p *UpdateFriendRemarkResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *UpdateFriendRemarkResp) GetMsg() (v string) {
	return p.Msg
}
func (p *UpdateFriendRemarkResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *UpdateFriendRemarkResp) SetMsg(val string) {
	p.Msg = val
}

func (p *UpdateFriendRemarkResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateFriendRemarkResp(%+v)", *p)
}

var fieldIDToName_UpdateFriendRemarkResp = map[int16]string{
	1: "success",
	2: "msg",
}

type FriendGroup struct {
	Id     int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	UserId int64  `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	Name   string `thrift:"name,3" frugal:"3,default,string" json:"name"`
}

func NewFriendGroup() *FriendGroup {
	return &FriendGroup{}
}

func (p *FriendGroup) InitDefault() {
}

func (p *FriendGroup) GetId() (v int64) {
	return p.Id
}

func (p *FriendGroup) GetUserId() (v int64) {
	return p.UserId
}

func (p *FriendGroup) GetName() (v string) {
	return p.Name
}
func (p *FriendGroup) SetId(val int64) {
	p.Id = val
}
func (p *FriendGroup) SetUserId(val int64) {
	p.UserId = val
}
func (p *FriendGroup) SetName(val string) {
	p.Name = val
}

func (p *FriendGroup) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendGroup(%+v)", *p)
}

var fieldIDToName_FriendGroup = map[int16]string{
	1: "id",
	2: "user_id",
	3: "name",
}

type CreateFriendGroupReq struct {
	UserId int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Name   string `thrift:"name,2" frugal:"2,default,string" json:"name"`
}

func NewCreateFriendGroupReq() *CreateFriendGroupReq {
	return &CreateFriendGroupReq{}
}

func (p *CreateFriendGroupReq) InitDefault() {
}

func (p *CreateFriendGroupReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *CreateFriendGroupReq) GetName() (v string) {
	return p.Name
}
func (p *CreateFriendGroupReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *CreateFriendGroupReq) SetName(val string) {
	p.Name = val
}

func (p *CreateFriendGroupReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateFriendGroupReq(%+v)", *p)
}

var fieldIDToName_CreateFriendGroupReq = map[int16]string{
	1: "user_id",
	2: "name",
}

type CreateFriendGroupResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	GroupId int64  `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	Msg     string `thrift:"msg,3" frugal:"3,default,string" json:"msg"`
}

func NewCreateFriendGroupResp() *CreateFriendGroupResp {
	return &CreateFriendGroupResp{}
}

func (p *CreateFriendGroupResp) InitDefault() {
}

func (p *CreateFriendGroupResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *CreateFriendGroupResp) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *CreateFriendGroupResp) GetMsg() (v string) {
	return p.Msg
}
func (p *CreateFriendGroupResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *CreateFriendGroupResp) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *CreateFriendGroupResp) SetMsg(val string) {
	p.Msg = val
}

func (p *CreateFriendGroupResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateFriendGroupResp(%+v)", *p)
}

var fieldIDToName_CreateFriendGroupResp = map[int16]string{
	1: "success",
	2: "group_id",
	3: "msg",
}

type MoveFriendGroupReq struct {
	UserId   int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FriendId int64 `thrift:"friend_id,2" frugal:"2,default,i64" json:"friend_id"`
	GroupId  int64 `thrift:"group_id,3" frugal:"3,default,i64" json:"group_id"`
}

func NewMoveFriendGroupReq() *MoveFriendGroupReq {
	return &MoveFriendGroupReq{}
}

func (p *MoveFriendGroupReq) InitDefault() {
}

func (p *MoveFriendGroupReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *MoveFriendGroupReq) GetFriendId() (v int64) {
	return p.FriendId
}

func (p *MoveFriendGroupReq) GetGroupId() (v int64) {
	return p.GroupId
}
func (p *MoveFriendGroupReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *MoveFriendGroupReq) SetFriendId(val int64) {
	p.FriendId = val
}
func (p *MoveFriendGroupReq) SetGroupId(val int64) {
	p.GroupId = val
}

func (p *MoveFriendGroupReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MoveFriendGroupReq(%+v)", *p)
}

var fieldIDToName_MoveFriendGroupReq = map[int16]string{
	1: "user_id",
	2: "friend_id",
	3: "group_id",
}

type MoveFriendGroupResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Msg     string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewMoveFriendGroupResp() *MoveFriendGroupResp {
	return &MoveFriendGroupResp{}
}

func (p *MoveFriendGroupResp) InitDefault() {
}

func (p *MoveFriendGroupResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *MoveFriendGroupResp) GetMsg() (v string) {
	return p.Msg
}
func (p *MoveFriendGroupResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *MoveFriendGroupResp) SetMsg(val string) {
	p.Msg = val
}

func (p *MoveFriendGroupResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MoveFriendGroupResp(%+v)", *p)
}

var fieldIDToName_MoveFriendGroupResp = map[int16]string{
	1: "success",
	2: "msg",
}

type GetFriendGroupsReq struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetFriendGroupsReq() *GetFriendGroupsReq {
	return &GetFriendGroupsReq{}
}

func (p *GetFriendGroupsReq) InitDefault() {
}

func (p *GetFriendGroupsReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetFriendGroupsReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetFriendGroupsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFriendGroupsReq(%+v)", *p)
}

var fieldIDToName_GetFriendGroupsReq = map[int16]string{
	1: "user_id",
}

type GetFriendGroupsResp struct {
	Success bool           `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Groups  []*FriendGroup `thrift:"groups,2" frugal:"2,default,list<FriendGroup>" json:"groups"`
	Msg     string         `thrift:"msg,3" frugal:"3,default,string" json:"msg"`
}

func NewGetFriendGroupsResp() *GetFriendGroupsResp {
	return &GetFriendGroupsResp{}
}

func (p *GetFriendGroupsResp) InitDefault() {
}

func (p *GetFriendGroupsResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *GetFriendGroupsResp) GetGroups() (v []*FriendGroup) {
	return p.Groups
}

func (p *GetFriendGroupsResp) GetMsg() (v string) {
	return p.Msg
}
func (p *GetFriendGroupsResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *GetFriendGroupsResp) SetGroups(val []*FriendGroup) {
	p.Groups = val
}
func (p *GetFriendGroupsResp) SetMsg(val string) {
	p.Msg = val
}

func (p *GetFriendGroupsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFriendGroupsResp(%+v)", *p)
}

var fieldIDToName_GetFriendGroupsResp = map[int16]string{
	1: "success",
	2: "groups",
	3: "msg",
}

type BatchGetUserInfoReq struct {
	UserIds []int64 `thrift:"user_ids,1" frugal:"1,default,list<i64>" json:"user_ids"`
}

func NewBatchGetUserInfoReq() *BatchGetUserInfoReq {
	return &BatchGetUserInfoReq{}
}

func (p *BatchGetUserInfoReq) InitDefault() {
}

func (p *BatchGetUserInfoReq) GetUserIds() (v []int64) {
	return p.UserIds
}
func (p *BatchGetUserInfoReq) SetUserIds(val []int64) {
	p.UserIds = val
}

func (p *BatchGetUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchGetUserInfoReq(%+v)", *p)
}

var fieldIDToName_BatchGetUserInfoReq = map[int16]string{
	1: "user_ids",
}

type BatchGetUserInfoResp struct {
	Success bool    `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Users   []*User `thrift:"users,2" frugal:"2,default,list<User>" json:"users"`
	Msg     string  `thrift:"msg,3" frugal:"3,default,string" json:"msg"`
}

func NewBatchGetUserInfoResp() *BatchGetUserInfoResp {
	return &BatchGetUserInfoResp{}
}

func (p *BatchGetUserInfoResp) InitDefault() {
}

func (p *BatchGetUserInfoResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *BatchGetUserInfoResp) GetUsers() (v []*User) {
	return p.Users
}

func (p *BatchGetUserInfoResp) GetMsg() (v string) {
	return p.Msg
}
func (p *BatchGetUserInfoResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *BatchGetUserInfoResp) SetUsers(val []*User) {
	p.Users = val
}
func (p *BatchGetUserInfoResp) SetMsg(val string) {
	p.Msg = val
}

func (p *BatchGetUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchGetUserInfoResp(%+v)", *p)
}

var fieldIDToName_BatchGetUserInfoResp = map[int16]string{
	1: "success",
	2: "users",
	3: "msg",
}

type UserService interface {
	Register(ctx context.Context, req *RegisterReq) (r *RegisterResp, err error)

	Login(ctx context.Context, req *LoginReq) (r *LoginResp, err error)

	GetUserInfo(ctx context.Context, req *GetUserInfoReq) (r *GetUserInfoResp, err error)

	UpdateUserInfo(ctx context.Context, req *UpdateUserInfoReq) (r *UpdateUserInfoResp, err error)

	UpdateAvatar(ctx context.Context, req *UpdateAvatarReq) (r *UpdateAvatarResp, err error)

	UpdateStatus(ctx context.Context, req *UpdateStatusReq) (r *UpdateStatusResp, err error)

	AddFriend(ctx context.Context, req *AddFriendReq) (r *AddFriendResp, err error)

	DeleteFriend(ctx context.Context, req *DeleteFriendReq) (r *DeleteFriendResp, err error)

	GetFriendList(ctx context.Context, req *GetFriendListReq) (r *GetFriendListResp, err error)

	UpdateFriendRemark(ctx context.Context, req *UpdateFriendRemarkReq) (r *UpdateFriendRemarkResp, err error)

	CreateFriendGroup(ctx context.Context, req *CreateFriendGroupReq) (r *CreateFriendGroupResp, err error)

	MoveFriendGroup(ctx context.Context, req *MoveFriendGroupReq) (r *MoveFriendGroupResp, err error)

	GetFriendGroups(ctx context.Context, req *GetFriendGroupsReq) (r *GetFriendGroupsResp, err error)

	BatchGetUserInfo(ctx context.Context, req *BatchGetUserInfoReq) (r *BatchGetUserInfoResp, err error)
}

type UserServiceRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterReq

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *RegisterResp `thrift:"success,0,optional" frugal:"0,optional,RegisterResp" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *RegisterResp

func (p *UserServiceRegisterResult) GetSuccess() (v *RegisterResp) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResp)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Req_DEFAULT *LoginReq

func (p *UserServiceLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return UserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *UserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserServiceLoginResult struct {
	Success *LoginResp `thrift:"success,0,optional" frugal:"0,optional,LoginResp" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *LoginResp

func (p *UserServiceLoginResult) GetSuccess() (v *LoginResp) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResp)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserInfoArgs struct {
	Req *GetUserInfoReq `thrift:"req,1" frugal:"1,default,GetUserInfoReq" json:"req"`
}

func NewUserServiceGetUserInfoArgs() *UserServiceGetUserInfoArgs {
	return &UserServiceGetUserInfoArgs{}
}

func (p *UserServiceGetUserInfoArgs) InitDefault() {
}

var UserServiceGetUserInfoArgs_Req_DEFAULT *GetUserInfoReq

func (p *UserServiceGetUserInfoArgs) GetReq() (v *GetUserInfoReq) {
	if !p.IsSetReq() {
		return UserServiceGetUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserInfoArgs) SetReq(val *GetUserInfoReq) {
	p.Req = val
}

func (p *UserServiceGetUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserInfoResult struct {
	Success *GetUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetUserInfoResp" json:"success,omitempty"`
}

func NewUserServiceGetUserInfoResult() *UserServiceGetUserInfoResult {
	return &UserServiceGetUserInfoResult{}
}

func (p *UserServiceGetUserInfoResult) InitDefault() {
}

var UserServiceGetUserInfoResult_Success_DEFAULT *GetUserInfoResp

func (p *UserServiceGetUserInfoResult) GetSuccess() (v *GetUserInfoResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserInfoResp)
}

func (p *UserServiceGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateUserInfoArgs struct {
	Req *UpdateUserInfoReq `thrift:"req,1" frugal:"1,default,UpdateUserInfoReq" json:"req"`
}

func NewUserServiceUpdateUserInfoArgs() *UserServiceUpdateUserInfoArgs {
	return &UserServiceUpdateUserInfoArgs{}
}

func (p *UserServiceUpdateUserInfoArgs) InitDefault() {
}

var UserServiceUpdateUserInfoArgs_Req_DEFAULT *UpdateUserInfoReq

func (p *UserServiceUpdateUserInfoArgs) GetReq() (v *UpdateUserInfoReq) {
	if !p.IsSetReq() {
		return UserServiceUpdateUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateUserInfoArgs) SetReq(val *UpdateUserInfoReq) {
	p.Req = val
}

func (p *UserServiceUpdateUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserInfoArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserInfoArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateUserInfoResult struct {
	Success *UpdateUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,UpdateUserInfoResp" json:"success,omitempty"`
}

func NewUserServiceUpdateUserInfoResult() *UserServiceUpdateUserInfoResult {
	return &UserServiceUpdateUserInfoResult{}
}

func (p *UserServiceUpdateUserInfoResult) InitDefault() {
}

var UserServiceUpdateUserInfoResult_Success_DEFAULT *UpdateUserInfoResp

func (p *UserServiceUpdateUserInfoResult) GetSuccess() (v *UpdateUserInfoResp) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserInfoResp)
}

func (p *UserServiceUpdateUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserInfoResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserInfoResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateAvatarArgs struct {
	Req *UpdateAvatarReq `thrift:"req,1" frugal:"1,default,UpdateAvatarReq" json:"req"`
}

func NewUserServiceUpdateAvatarArgs() *UserServiceUpdateAvatarArgs {
	return &UserServiceUpdateAvatarArgs{}
}

func (p *UserServiceUpdateAvatarArgs) InitDefault() {
}

var UserServiceUpdateAvatarArgs_Req_DEFAULT *UpdateAvatarReq

func (p *UserServiceUpdateAvatarArgs) GetReq() (v *UpdateAvatarReq) {
	if !p.IsSetReq() {
		return UserServiceUpdateAvatarArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateAvatarArgs) SetReq(val *UpdateAvatarReq) {
	p.Req = val
}

func (p *UserServiceUpdateAvatarArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateAvatarArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateAvatarArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateAvatarArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateAvatarResult struct {
	Success *UpdateAvatarResp `thrift:"success,0,optional" frugal:"0,optional,UpdateAvatarResp" json:"success,omitempty"`
}

func NewUserServiceUpdateAvatarResult() *UserServiceUpdateAvatarResult {
	return &UserServiceUpdateAvatarResult{}
}

func (p *UserServiceUpdateAvatarResult) InitDefault() {
}

var UserServiceUpdateAvatarResult_Success_DEFAULT *UpdateAvatarResp

func (p *UserServiceUpdateAvatarResult) GetSuccess() (v *UpdateAvatarResp) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateAvatarResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateAvatarResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateAvatarResp)
}

func (p *UserServiceUpdateAvatarResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateAvatarResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateAvatarResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateAvatarResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateStatusArgs struct {
	Req *UpdateStatusReq `thrift:"req,1" frugal:"1,default,UpdateStatusReq" json:"req"`
}

func NewUserServiceUpdateStatusArgs() *UserServiceUpdateStatusArgs {
	return &UserServiceUpdateStatusArgs{}
}

func (p *UserServiceUpdateStatusArgs) InitDefault() {
}

var UserServiceUpdateStatusArgs_Req_DEFAULT *UpdateStatusReq

func (p *UserServiceUpdateStatusArgs) GetReq() (v *UpdateStatusReq) {
	if !p.IsSetReq() {
		return UserServiceUpdateStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateStatusArgs) SetReq(val *UpdateStatusReq) {
	p.Req = val
}

func (p *UserServiceUpdateStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateStatusArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateStatusArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateStatusResult struct {
	Success *UpdateStatusResp `thrift:"success,0,optional" frugal:"0,optional,UpdateStatusResp" json:"success,omitempty"`
}

func NewUserServiceUpdateStatusResult() *UserServiceUpdateStatusResult {
	return &UserServiceUpdateStatusResult{}
}

func (p *UserServiceUpdateStatusResult) InitDefault() {
}

var UserServiceUpdateStatusResult_Success_DEFAULT *UpdateStatusResp

func (p *UserServiceUpdateStatusResult) GetSuccess() (v *UpdateStatusResp) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateStatusResp)
}

func (p *UserServiceUpdateStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateStatusResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateStatusResult = map[int16]string{
	0: "success",
}

type UserServiceAddFriendArgs struct {
	Req *AddFriendReq `thrift:"req,1" frugal:"1,default,AddFriendReq" json:"req"`
}

func NewUserServiceAddFriendArgs() *UserServiceAddFriendArgs {
	return &UserServiceAddFriendArgs{}
}

func (p *UserServiceAddFriendArgs) InitDefault() {
}

var UserServiceAddFriendArgs_Req_DEFAULT *AddFriendReq

func (p *UserServiceAddFriendArgs) GetReq() (v *AddFriendReq) {
	if !p.IsSetReq() {
		return UserServiceAddFriendArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceAddFriendArgs) SetReq(val *AddFriendReq) {
	p.Req = val
}

func (p *UserServiceAddFriendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceAddFriendArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAddFriendArgs(%+v)", *p)
}

var fieldIDToName_UserServiceAddFriendArgs = map[int16]string{
	1: "req",
}

type UserServiceAddFriendResult struct {
	Success *AddFriendResp `thrift:"success,0,optional" frugal:"0,optional,AddFriendResp" json:"success,omitempty"`
}

func NewUserServiceAddFriendResult() *UserServiceAddFriendResult {
	return &UserServiceAddFriendResult{}
}

func (p *UserServiceAddFriendResult) InitDefault() {
}

var UserServiceAddFriendResult_Success_DEFAULT *AddFriendResp

func (p *UserServiceAddFriendResult) GetSuccess() (v *AddFriendResp) {
	if !p.IsSetSuccess() {
		return UserServiceAddFriendResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceAddFriendResult) SetSuccess(x interface{}) {
	p.Success = x.(*AddFriendResp)
}

func (p *UserServiceAddFriendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceAddFriendResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAddFriendResult(%+v)", *p)
}

var fieldIDToName_UserServiceAddFriendResult = map[int16]string{
	0: "success",
}

type UserServiceDeleteFriendArgs struct {
	Req *DeleteFriendReq `thrift:"req,1" frugal:"1,default,DeleteFriendReq" json:"req"`
}

func NewUserServiceDeleteFriendArgs() *UserServiceDeleteFriendArgs {
	return &UserServiceDeleteFriendArgs{}
}

func (p *UserServiceDeleteFriendArgs) InitDefault() {
}

var UserServiceDeleteFriendArgs_Req_DEFAULT *DeleteFriendReq

func (p *UserServiceDeleteFriendArgs) GetReq() (v *DeleteFriendReq) {
	if !p.IsSetReq() {
		return UserServiceDeleteFriendArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceDeleteFriendArgs) SetReq(val *DeleteFriendReq) {
	p.Req = val
}

func (p *UserServiceDeleteFriendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceDeleteFriendArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteFriendArgs(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteFriendArgs = map[int16]string{
	1: "req",
}

type UserServiceDeleteFriendResult struct {
	Success *DeleteFriendResp `thrift:"success,0,optional" frugal:"0,optional,DeleteFriendResp" json:"success,omitempty"`
}

func NewUserServiceDeleteFriendResult() *UserServiceDeleteFriendResult {
	return &UserServiceDeleteFriendResult{}
}

func (p *UserServiceDeleteFriendResult) InitDefault() {
}

var UserServiceDeleteFriendResult_Success_DEFAULT *DeleteFriendResp

func (p *UserServiceDeleteFriendResult) GetSuccess() (v *DeleteFriendResp) {
	if !p.IsSetSuccess() {
		return UserServiceDeleteFriendResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceDeleteFriendResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteFriendResp)
}

func (p *UserServiceDeleteFriendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceDeleteFriendResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteFriendResult(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteFriendResult = map[int16]string{
	0: "success",
}

type UserServiceGetFriendListArgs struct {
	Req *GetFriendListReq `thrift:"req,1" frugal:"1,default,GetFriendListReq" json:"req"`
}

func NewUserServiceGetFriendListArgs() *UserServiceGetFriendListArgs {
	return &UserServiceGetFriendListArgs{}
}

func (p *UserServiceGetFriendListArgs) InitDefault() {
}

var UserServiceGetFriendListArgs_Req_DEFAULT *GetFriendListReq

func (p *UserServiceGetFriendListArgs) GetReq() (v *GetFriendListReq) {
	if !p.IsSetReq() {
		return UserServiceGetFriendListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetFriendListArgs) SetReq(val *GetFriendListReq) {
	p.Req = val
}

func (p *UserServiceGetFriendListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetFriendListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetFriendListArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetFriendListArgs = map[int16]string{
	1: "req",
}

type UserServiceGetFriendListResult struct {
	Success *GetFriendListResp `thrift:"success,0,optional" frugal:"0,optional,GetFriendListResp" json:"success,omitempty"`
}

func NewUserServiceGetFriendListResult() *UserServiceGetFriendListResult {
	return &UserServiceGetFriendListResult{}
}

func (p *UserServiceGetFriendListResult) InitDefault() {
}

var UserServiceGetFriendListResult_Success_DEFAULT *GetFriendListResp

func (p *UserServiceGetFriendListResult) GetSuccess() (v *GetFriendListResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetFriendListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetFriendListResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetFriendListResp)
}

func (p *UserServiceGetFriendListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetFriendListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetFriendListResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetFriendListResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateFriendRemarkArgs struct {
	Req *UpdateFriendRemarkReq `thrift:"req,1" frugal:"1,default,UpdateFriendRemarkReq" json:"req"`
}

func NewUserServiceUpdateFriendRemarkArgs() *UserServiceUpdateFriendRemarkArgs {
	return &UserServiceUpdateFriendRemarkArgs{}
}

func (p *UserServiceUpdateFriendRemarkArgs) InitDefault() {
}

var UserServiceUpdateFriendRemarkArgs_Req_DEFAULT *UpdateFriendRemarkReq

func (p *UserServiceUpdateFriendRemarkArgs) GetReq() (v *UpdateFriendRemarkReq) {
	if !p.IsSetReq() {
		return UserServiceUpdateFriendRemarkArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateFriendRemarkArgs) SetReq(val *UpdateFriendRemarkReq) {
	p.Req = val
}

func (p *UserServiceUpdateFriendRemarkArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateFriendRemarkArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateFriendRemarkArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateFriendRemarkArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateFriendRemarkResult struct {
	Success *UpdateFriendRemarkResp `thrift:"success,0,optional" frugal:"0,optional,UpdateFriendRemarkResp" json:"success,omitempty"`
}

func NewUserServiceUpdateFriendRemarkResult() *UserServiceUpdateFriendRemarkResult {
	return &UserServiceUpdateFriendRemarkResult{}
}

func (p *UserServiceUpdateFriendRemarkResult) InitDefault() {
}

var UserServiceUpdateFriendRemarkResult_Success_DEFAULT *UpdateFriendRemarkResp

func (p *UserServiceUpdateFriendRemarkResult) GetSuccess() (v *UpdateFriendRemarkResp) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateFriendRemarkResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateFriendRemarkResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateFriendRemarkResp)
}

func (p *UserServiceUpdateFriendRemarkResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateFriendRemarkResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateFriendRemarkResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateFriendRemarkResult = map[int16]string{
	0: "success",
}

type UserServiceCreateFriendGroupArgs struct {
	Req *CreateFriendGroupReq `thrift:"req,1" frugal:"1,default,CreateFriendGroupReq" json:"req"`
}

func NewUserServiceCreateFriendGroupArgs() *UserServiceCreateFriendGroupArgs {
	return &UserServiceCreateFriendGroupArgs{}
}

func (p *UserServiceCreateFriendGroupArgs) InitDefault() {
}

var UserServiceCreateFriendGroupArgs_Req_DEFAULT *CreateFriendGroupReq

func (p *UserServiceCreateFriendGroupArgs) GetReq() (v *CreateFriendGroupReq) {
	if !p.IsSetReq() {
		return UserServiceCreateFriendGroupArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCreateFriendGroupArgs) SetReq(val *CreateFriendGroupReq) {
	p.Req = val
}

func (p *UserServiceCreateFriendGroupArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCreateFriendGroupArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateFriendGroupArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCreateFriendGroupArgs = map[int16]string{
	1: "req",
}

type UserServiceCreateFriendGroupResult struct {
	Success *CreateFriendGroupResp `thrift:"success,0,optional" frugal:"0,optional,CreateFriendGroupResp" json:"success,omitempty"`
}

func NewUserServiceCreateFriendGroupResult() *UserServiceCreateFriendGroupResult {
	return &UserServiceCreateFriendGroupResult{}
}

func (p *UserServiceCreateFriendGroupResult) InitDefault() {
}

var UserServiceCreateFriendGroupResult_Success_DEFAULT *CreateFriendGroupResp

func (p *UserServiceCreateFriendGroupResult) GetSuccess() (v *CreateFriendGroupResp) {
	if !p.IsSetSuccess() {
		return UserServiceCreateFriendGroupResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceCreateFriendGroupResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateFriendGroupResp)
}

func (p *UserServiceCreateFriendGroupResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCreateFriendGroupResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateFriendGroupResult(%+v)", *p)
}

var fieldIDToName_UserServiceCreateFriendGroupResult = map[int16]string{
	0: "success",
}

type UserServiceMoveFriendGroupArgs struct {
	Req *MoveFriendGroupReq `thrift:"req,1" frugal:"1,default,MoveFriendGroupReq" json:"req"`
}

func NewUserServiceMoveFriendGroupArgs() *UserServiceMoveFriendGroupArgs {
	return &UserServiceMoveFriendGroupArgs{}
}

func (p *UserServiceMoveFriendGroupArgs) InitDefault() {
}

var UserServiceMoveFriendGroupArgs_Req_DEFAULT *MoveFriendGroupReq

func (p *UserServiceMoveFriendGroupArgs) GetReq() (v *MoveFriendGroupReq) {
	if !p.IsSetReq() {
		return UserServiceMoveFriendGroupArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceMoveFriendGroupArgs) SetReq(val *MoveFriendGroupReq) {
	p.Req = val
}

func (p *UserServiceMoveFriendGroupArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceMoveFriendGroupArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceMoveFriendGroupArgs(%+v)", *p)
}

var fieldIDToName_UserServiceMoveFriendGroupArgs = map[int16]string{
	1: "req",
}

type UserServiceMoveFriendGroupResult struct {
	Success *MoveFriendGroupResp `thrift:"success,0,optional" frugal:"0,optional,MoveFriendGroupResp" json:"success,omitempty"`
}

func NewUserServiceMoveFriendGroupResult() *UserServiceMoveFriendGroupResult {
	return &UserServiceMoveFriendGroupResult{}
}

func (p *UserServiceMoveFriendGroupResult) InitDefault() {
}

var UserServiceMoveFriendGroupResult_Success_DEFAULT *MoveFriendGroupResp

func (p *UserServiceMoveFriendGroupResult) GetSuccess() (v *MoveFriendGroupResp) {
	if !p.IsSetSuccess() {
		return UserServiceMoveFriendGroupResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceMoveFriendGroupResult) SetSuccess(x interface{}) {
	p.Success = x.(*MoveFriendGroupResp)
}

func (p *UserServiceMoveFriendGroupResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceMoveFriendGroupResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceMoveFriendGroupResult(%+v)", *p)
}

var fieldIDToName_UserServiceMoveFriendGroupResult = map[int16]string{
	0: "success",
}

type UserServiceGetFriendGroupsArgs struct {
	Req *GetFriendGroupsReq `thrift:"req,1" frugal:"1,default,GetFriendGroupsReq" json:"req"`
}

func NewUserServiceGetFriendGroupsArgs() *UserServiceGetFriendGroupsArgs {
	return &UserServiceGetFriendGroupsArgs{}
}

func (p *UserServiceGetFriendGroupsArgs) InitDefault() {
}

var UserServiceGetFriendGroupsArgs_Req_DEFAULT *GetFriendGroupsReq

func (p *UserServiceGetFriendGroupsArgs) GetReq() (v *GetFriendGroupsReq) {
	if !p.IsSetReq() {
		return UserServiceGetFriendGroupsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetFriendGroupsArgs) SetReq(val *GetFriendGroupsReq) {
	p.Req = val
}

func (p *UserServiceGetFriendGroupsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetFriendGroupsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetFriendGroupsArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetFriendGroupsArgs = map[int16]string{
	1: "req",
}

type UserServiceGetFriendGroupsResult struct {
	Success *GetFriendGroupsResp `thrift:"success,0,optional" frugal:"0,optional,GetFriendGroupsResp" json:"success,omitempty"`
}

func NewUserServiceGetFriendGroupsResult() *UserServiceGetFriendGroupsResult {
	return &UserServiceGetFriendGroupsResult{}
}

func (p *UserServiceGetFriendGroupsResult) InitDefault() {
}

var UserServiceGetFriendGroupsResult_Success_DEFAULT *GetFriendGroupsResp

func (p *UserServiceGetFriendGroupsResult) GetSuccess() (v *GetFriendGroupsResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetFriendGroupsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetFriendGroupsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetFriendGroupsResp)
}

func (p *UserServiceGetFriendGroupsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetFriendGroupsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetFriendGroupsResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetFriendGroupsResult = map[int16]string{
	0: "success",
}

type UserServiceBatchGetUserInfoArgs struct {
	Req *BatchGetUserInfoReq `thrift:"req,1" frugal:"1,default,BatchGetUserInfoReq" json:"req"`
}

func NewUserServiceBatchGetUserInfoArgs() *UserServiceBatchGetUserInfoArgs {
	return &UserServiceBatchGetUserInfoArgs{}
}

func (p *UserServiceBatchGetUserInfoArgs) InitDefault() {
}

var UserServiceBatchGetUserInfoArgs_Req_DEFAULT *BatchGetUserInfoReq

func (p *UserServiceBatchGetUserInfoArgs) GetReq() (v *BatchGetUserInfoReq) {
	if !p.IsSetReq() {
		return UserServiceBatchGetUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceBatchGetUserInfoArgs) SetReq(val *BatchGetUserInfoReq) {
	p.Req = val
}

func (p *UserServiceBatchGetUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceBatchGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceBatchGetUserInfoArgs(%+v)", *p)
}

var fieldIDToName_UserServiceBatchGetUserInfoArgs = map[int16]string{
	1: "req",
}

type UserServiceBatchGetUserInfoResult struct {
	Success *BatchGetUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,BatchGetUserInfoResp" json:"success,omitempty"`
}

func NewUserServiceBatchGetUserInfoResult() *UserServiceBatchGetUserInfoResult {
	return &UserServiceBatchGetUserInfoResult{}
}

func (p *UserServiceBatchGetUserInfoResult) InitDefault() {
}

var UserServiceBatchGetUserInfoResult_Success_DEFAULT *BatchGetUserInfoResp

func (p *UserServiceBatchGetUserInfoResult) GetSuccess() (v *BatchGetUserInfoResp) {
	if !p.IsSetSuccess() {
		return UserServiceBatchGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceBatchGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*BatchGetUserInfoResp)
}

func (p *UserServiceBatchGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceBatchGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceBatchGetUserInfoResult(%+v)", *p)
}

var fieldIDToName_UserServiceBatchGetUserInfoResult = map[int16]string{
	0: "success",
}
